package com.hand.hls.cap.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.Date;


@ExtensionAttribute(disable = true)
@Table(name = "cap_capital_invest_plan_ln")
public class HlsCusCapitalInvestmentPlanLn extends BaseDTO {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequence")
    @SequenceGenerator(name="sequence", sequenceName="cap_capital_invest_plan_ln_s", initialValue=1, allocationSize=1)
    private Long planLineId; //pk

    private Long planHeadId; //pk

    private Long companyId; //公司ID

    @Length(max = 100)
    private String businessType; //业务类型

    @Length(max = 100)
    private String documentCategory; //单据类别

    @Length(max = 100)
    private String documentType; //单据类型

    @Transient
    private String planInfo;
    @Transient
    private String projectStatus;

    @Transient
    private String planStatus;

    private Long contractId; //项目ID

    private Long projectId; //项目ID

    private Date finalPayDate;//最晚支付日期

    @Transient
    private String refFlag;

    @Transient
    private String[] executeStatusStr;
    @Transient
    private Double applyAmountFrom;
    @Transient
    private Double applyAmountTo;
    @Transient
    private Double actualAmountFrom;
    @Transient
    private Double actualAmountTo;
    @Transient
    private Date payDateFrom;
    @Transient
    private Date payDateTo;
    @Transient
    private  Date actualPayDateFrom;
    @Transient
    private Date actualPayDateTo;
    @Transient
    private Date lastInvestmentDate;

    @Transient
    private String projectStatusDesc;
    @Transient
    private String currencyName;
    @Transient
    private String unitName;

    private String cancelReason;

    private String delayReason;

    private String dataType;

    @Transient
    private String approveStatus;
    @Transient
    private Date approveDate;
    @Transient
    private String forPlan;

    @Length(max = 20)
    private String executeStatus; //执行状态(syscode：CAP.EXECUTE_STATUS)

    private Date payDate; //支付日期

    @Length(max = 20)
    private String newOrStock; //新增/存量(syscode：CAP.NEW_OR_STOCK)

    @Transient
    private String newOrStockDesc; //新增/存量

    @Transient
    private String newOrStockN;

    private Double applyInvestmentAmount; //申请投放金额

    private String investmentRate; //投放价格

    private Double actualInvestmentAmount; //实际投放金额

    private Date realPayDate; //实际支付日期

    private String paymentMethod; //投放方式

    private Long financePlanId;

    private Double planAmount;

    @Transient
    private String dataClass;

    @Transient
    private Date lastActualPayDate;

    @Length(max = 2000)
    private String description; //备注


    @Transient
    private String projectNumber;

    @Transient
    private Double leaseItemAmount;

    private String prjType;

    @Transient
    private String projectName;

    @Transient
    private Double financeAmount;

    @Transient
    private String businessTypeDesc;

    @Transient
    private String sellerOrTenant;

    @Transient
    private String buyerOrTenantSec;

    @Transient
    private Date leaseStartDate;

    @Transient
    private Date leaseEndDate;

    @Transient
    private Double creditAmount;

    @Transient
    private Date dateFrom;

    @Transient
    private Date dateTo;

    @Transient
    private String status;

    @Transient
    private String statusArray;

    @Transient
    private String planNumber;
    @Transient
    private String planName;

    @Transient
    private String hlsBusinessType;

    @Transient
    private String hlsDocumentType;

    @Transient
    private String userName;

    @Transient
    private Date validFrom; //开始日

    @Transient
    private Date validTo; //结束日

    @Transient
    private String companyName;

    @Transient
    private String planCycle;

    @Transient
    private String planCycleDesc;

    @Transient
    private Double realAmount;

    @Transient
    private Double executeDegree;

    @Transient
    private Double degreeFrom;

    @Transient
    private Double degreeTo;

    @Transient
    private Double amountFrom;

    @Transient
    private Double amountTo;

    @Transient
    private String sumUp;

    @Transient
    private String payDateDesc;

    @Transient
    private String seq;

    @Transient
    private String creditPlan;

    @Transient
    private String leaseTerm;

    @Transient
    private String contractLeaseTerm;

    @Transient
    private String contractInvestmentRate;

    @Transient
    private String projectManager;

    @Transient
    private String executeStatusDesc;

    @Transient
    private String paymentCondition;

    @Transient
    private String manageCondition;

    @Transient
    private String projectIdN;
    @Transient
    private String businessTypeN;
    @Transient
    private Long tenantId;
    @Transient
    private String tenantIdN;
    @Transient
    private String currency;
    @Transient
    private String projectStatusN;

    public Long getPlanLineId() {
        return planLineId;
    }

    public void setPlanLineId(Long planLineId) {
        this.planLineId = planLineId;
    }

    public Long getPlanHeadId() {
        return planHeadId;
    }

    public void setPlanHeadId(Long planHeadId) {
        this.planHeadId = planHeadId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public String getBusinessType() {
        return businessType;
    }

    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    public String getDocumentCategory() {
        return documentCategory;
    }

    public void setDocumentCategory(String documentCategory) {
        this.documentCategory = documentCategory;
    }

    public String getDocumentType() {
        return documentType;
    }

    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    public String getPlanInfo() {
        return planInfo;
    }

    public void setPlanInfo(String planInfo) {
        this.planInfo = planInfo;
    }

    public String getProjectStatus() {
        return projectStatus;
    }

    public void setProjectStatus(String projectStatus) {
        this.projectStatus = projectStatus;
    }

    public String getPlanStatus() {
        return planStatus;
    }

    public void setPlanStatus(String planStatus) {
        this.planStatus = planStatus;
    }

    public Long getContractId() {
        return contractId;
    }

    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Date getFinalPayDate() {
        return finalPayDate;
    }

    public void setFinalPayDate(Date finalPayDate) {
        this.finalPayDate = finalPayDate;
    }

    public String getRefFlag() {
        return refFlag;
    }

    public void setRefFlag(String refFlag) {
        this.refFlag = refFlag;
    }

    public String[] getExecuteStatusStr() {
        return executeStatusStr;
    }

    public void setExecuteStatusStr(String[] executeStatusStr) {
        this.executeStatusStr = executeStatusStr;
    }

    public Double getApplyAmountFrom() {
        return applyAmountFrom;
    }

    public void setApplyAmountFrom(Double applyAmountFrom) {
        this.applyAmountFrom = applyAmountFrom;
    }

    public Double getApplyAmountTo() {
        return applyAmountTo;
    }

    public void setApplyAmountTo(Double applyAmountTo) {
        this.applyAmountTo = applyAmountTo;
    }

    public Double getActualAmountFrom() {
        return actualAmountFrom;
    }

    public void setActualAmountFrom(Double actualAmountFrom) {
        this.actualAmountFrom = actualAmountFrom;
    }

    public Double getActualAmountTo() {
        return actualAmountTo;
    }

    public void setActualAmountTo(Double actualAmountTo) {
        this.actualAmountTo = actualAmountTo;
    }

    public Date getPayDateFrom() {
        return payDateFrom;
    }

    public void setPayDateFrom(Date payDateFrom) {
        this.payDateFrom = payDateFrom;
    }

    public Date getPayDateTo() {
        return payDateTo;
    }

    public void setPayDateTo(Date payDateTo) {
        this.payDateTo = payDateTo;
    }

    public Date getActualPayDateFrom() {
        return actualPayDateFrom;
    }

    public void setActualPayDateFrom(Date actualPayDateFrom) {
        this.actualPayDateFrom = actualPayDateFrom;
    }

    public Date getActualPayDateTo() {
        return actualPayDateTo;
    }

    public void setActualPayDateTo(Date actualPayDateTo) {
        this.actualPayDateTo = actualPayDateTo;
    }

    public Date getLastInvestmentDate() {
        return lastInvestmentDate;
    }

    public void setLastInvestmentDate(Date lastInvestmentDate) {
        this.lastInvestmentDate = lastInvestmentDate;
    }

    public String getProjectStatusDesc() {
        return projectStatusDesc;
    }

    public void setProjectStatusDesc(String projectStatusDesc) {
        this.projectStatusDesc = projectStatusDesc;
    }

    public String getCurrencyName() {
        return currencyName;
    }

    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public String getCancelReason() {
        return cancelReason;
    }

    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    public String getDelayReason() {
        return delayReason;
    }

    public void setDelayReason(String delayReason) {
        this.delayReason = delayReason;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getApproveStatus() {
        return approveStatus;
    }

    public void setApproveStatus(String approveStatus) {
        this.approveStatus = approveStatus;
    }

    public Date getApproveDate() {
        return approveDate;
    }

    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }

    public String getForPlan() {
        return forPlan;
    }

    public void setForPlan(String forPlan) {
        this.forPlan = forPlan;
    }

    public String getExecuteStatus() {
        return executeStatus;
    }

    public void setExecuteStatus(String executeStatus) {
        this.executeStatus = executeStatus;
    }

    public Date getPayDate() {
        return payDate;
    }

    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    public String getNewOrStock() {
        return newOrStock;
    }

    public void setNewOrStock(String newOrStock) {
        this.newOrStock = newOrStock;
    }

    public String getNewOrStockDesc() {
        return newOrStockDesc;
    }

    public void setNewOrStockDesc(String newOrStockDesc) {
        this.newOrStockDesc = newOrStockDesc;
    }

    public Double getApplyInvestmentAmount() {
        return applyInvestmentAmount;
    }

    public void setApplyInvestmentAmount(Double applyInvestmentAmount) {
        this.applyInvestmentAmount = applyInvestmentAmount;
    }

    public String getInvestmentRate() {
        return investmentRate;
    }

    public void setInvestmentRate(String investmentRate) {
        this.investmentRate = investmentRate;
    }

    public Double getActualInvestmentAmount() {
        return actualInvestmentAmount;
    }

    public void setActualInvestmentAmount(Double actualInvestmentAmount) {
        this.actualInvestmentAmount = actualInvestmentAmount;
    }

    public Date getRealPayDate() {
        return realPayDate;
    }

    public void setRealPayDate(Date realPayDate) {
        this.realPayDate = realPayDate;
    }

    public String getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public Long getFinancePlanId() {
        return financePlanId;
    }

    public void setFinancePlanId(Long financePlanId) {
        this.financePlanId = financePlanId;
    }

    public Double getPlanAmount() {
        return planAmount;
    }

    public void setPlanAmount(Double planAmount) {
        this.planAmount = planAmount;
    }

    public String getDataClass() {
        return dataClass;
    }

    public void setDataClass(String dataClass) {
        this.dataClass = dataClass;
    }

    public Date getLastActualPayDate() {
        return lastActualPayDate;
    }

    public void setLastActualPayDate(Date lastActualPayDate) {
        this.lastActualPayDate = lastActualPayDate;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getProjectNumber() {
        return projectNumber;
    }

    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber;
    }

    public Double getLeaseItemAmount() {
        return leaseItemAmount;
    }

    public void setLeaseItemAmount(Double leaseItemAmount) {
        this.leaseItemAmount = leaseItemAmount;
    }

    public String getPrjType() {
        return prjType;
    }

    public void setPrjType(String prjType) {
        this.prjType = prjType;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Double getFinanceAmount() {
        return financeAmount;
    }

    public void setFinanceAmount(Double financeAmount) {
        this.financeAmount = financeAmount;
    }

    public String getBusinessTypeDesc() {
        return businessTypeDesc;
    }

    public void setBusinessTypeDesc(String businessTypeDesc) {
        this.businessTypeDesc = businessTypeDesc;
    }

    public String getSellerOrTenant() {
        return sellerOrTenant;
    }

    public void setSellerOrTenant(String sellerOrTenant) {
        this.sellerOrTenant = sellerOrTenant;
    }

    public String getBuyerOrTenantSec() {
        return buyerOrTenantSec;
    }

    public void setBuyerOrTenantSec(String buyerOrTenantSec) {
        this.buyerOrTenantSec = buyerOrTenantSec;
    }

    public Date getLeaseStartDate() {
        return leaseStartDate;
    }

    public void setLeaseStartDate(Date leaseStartDate) {
        this.leaseStartDate = leaseStartDate;
    }

    public Date getLeaseEndDate() {
        return leaseEndDate;
    }

    public void setLeaseEndDate(Date leaseEndDate) {
        this.leaseEndDate = leaseEndDate;
    }

    public Double getCreditAmount() {
        return creditAmount;
    }

    public void setCreditAmount(Double creditAmount) {
        this.creditAmount = creditAmount;
    }

    public Date getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public Date getDateTo() {
        return dateTo;
    }

    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatusArray() {
        return statusArray;
    }

    public void setStatusArray(String statusArray) {
        this.statusArray = statusArray;
    }

    public String getPlanNumber() {
        return planNumber;
    }

    public void setPlanNumber(String planNumber) {
        this.planNumber = planNumber;
    }

    public String getPlanName() {
        return planName;
    }

    public void setPlanName(String planName) {
        this.planName = planName;
    }

    public String getHlsBusinessType() {
        return hlsBusinessType;
    }

    public void setHlsBusinessType(String hlsBusinessType) {
        this.hlsBusinessType = hlsBusinessType;
    }

    public String getHlsDocumentType() {
        return hlsDocumentType;
    }

    public void setHlsDocumentType(String hlsDocumentType) {
        this.hlsDocumentType = hlsDocumentType;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Date getValidFrom() {
        return validFrom;
    }

    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    public Date getValidTo() {
        return validTo;
    }

    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getPlanCycle() {
        return planCycle;
    }

    public void setPlanCycle(String planCycle) {
        this.planCycle = planCycle;
    }

    public String getPlanCycleDesc() {
        return planCycleDesc;
    }

    public void setPlanCycleDesc(String planCycleDesc) {
        this.planCycleDesc = planCycleDesc;
    }

    public Double getRealAmount() {
        return realAmount;
    }

    public void setRealAmount(Double realAmount) {
        this.realAmount = realAmount;
    }

    public Double getExecuteDegree() {
        return executeDegree;
    }

    public void setExecuteDegree(Double executeDegree) {
        this.executeDegree = executeDegree;
    }

    public Double getDegreeFrom() {
        return degreeFrom;
    }

    public void setDegreeFrom(Double degreeFrom) {
        this.degreeFrom = degreeFrom;
    }

    public Double getDegreeTo() {
        return degreeTo;
    }

    public void setDegreeTo(Double degreeTo) {
        this.degreeTo = degreeTo;
    }

    public Double getAmountFrom() {
        return amountFrom;
    }

    public void setAmountFrom(Double amountFrom) {
        this.amountFrom = amountFrom;
    }

    public Double getAmountTo() {
        return amountTo;
    }

    public void setAmountTo(Double amountTo) {
        this.amountTo = amountTo;
    }

    public String getSumUp() {
        return sumUp;
    }

    public void setSumUp(String sumUp) {
        this.sumUp = sumUp;
    }

    public String getPayDateDesc() {
        return payDateDesc;
    }

    public void setPayDateDesc(String payDateDesc) {
        this.payDateDesc = payDateDesc;
    }

    public String getSeq() {
        return seq;
    }

    public void setSeq(String seq) {
        this.seq = seq;
    }

    public String getCreditPlan() {
        return creditPlan;
    }

    public void setCreditPlan(String creditPlan) {
        this.creditPlan = creditPlan;
    }

    public String getLeaseTerm() {
        return leaseTerm;
    }

    public void setLeaseTerm(String leaseTerm) {
        this.leaseTerm = leaseTerm;
    }

    public String getContractLeaseTerm() {
        return contractLeaseTerm;
    }

    public void setContractLeaseTerm(String contractLeaseTerm) {
        this.contractLeaseTerm = contractLeaseTerm;
    }

    public String getContractInvestmentRate() {
        return contractInvestmentRate;
    }

    public void setContractInvestmentRate(String contractInvestmentRate) {
        this.contractInvestmentRate = contractInvestmentRate;
    }

    public String getProjectManager() {
        return projectManager;
    }

    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager;
    }

    public String getExecuteStatusDesc() {
        return executeStatusDesc;
    }

    public void setExecuteStatusDesc(String executeStatusDesc) {
        this.executeStatusDesc = executeStatusDesc;
    }

    public String getPaymentCondition() {
        return paymentCondition;
    }

    public void setPaymentCondition(String paymentCondition) {
        this.paymentCondition = paymentCondition;
    }

    public String getManageCondition() {
        return manageCondition;
    }

    public void setManageCondition(String manageCondition) {
        this.manageCondition = manageCondition;
    }

    public String getNewOrStockN() {
        return newOrStockN;
    }

    public void setNewOrStockN(String newOrStockN) {
        this.newOrStockN = newOrStockN;
    }

    public String getProjectIdN() {
        return projectIdN;
    }

    public void setProjectIdN(String projectIdN) {
        this.projectIdN = projectIdN;
    }

    public String getBusinessTypeN() {
        return businessTypeN;
    }

    public void setBusinessTypeN(String businessTypeN) {
        this.businessTypeN = businessTypeN;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getTenantIdN() {
        return tenantIdN;
    }

    public void setTenantIdN(String tenantIdN) {
        this.tenantIdN = tenantIdN;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getProjectStatusN() {
        return projectStatusN;
    }

    public void setProjectStatusN(String projectStatusN) {
        this.projectStatusN = projectStatusN;
    }
}
