<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.16.RELEASE</version>
    </parent>

    <groupId>com.hand.hls</groupId>
    <artifactId>gtzl</artifactId>
    <version>1.0.0-RELEASE</version>
    <name>gtzl</name>
    <packaging>war</packaging>

    <properties>
        <java.version>1.8</java.version>
        <jackson.version>2.10.0</jackson.version>
        <maven.test.skip>true</maven.test.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.hand.hls</groupId>
            <artifactId>leaf-core</artifactId>
            <version>2.1.9-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.8</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.60.sec10</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20180130</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.16</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.16</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlbeans</groupId>
            <artifactId>xmlbeans</artifactId>
            <version>2.6.0</version>
        </dependency>



        <dependency>
            <groupId>org.apache.axis</groupId>
            <artifactId>axis</artifactId>
            <version>1.4</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/axis.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>org.apache.axis</groupId>
            <artifactId>axis-jaxrpc</artifactId>
            <version>1.4</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/jaxrpc.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>commons-discovery</groupId>
            <artifactId>commons-discovery</artifactId>
            <version>0.2</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/commons-discovery-0.2.jar</systemPath>
        </dependency>


        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>1.0.4.v201101211617</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/commons-logging.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>cfca.paperless.base</groupId>
            <artifactId>paperless-base</artifactId>
            <version>4.6.1.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/PaperlessBase-4.6.1.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>PaperlessClient</groupId>
            <artifactId>PaperlessClient</artifactId>
            <version>4.6.1.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/PaperlessClient-4.6.1.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>PaperlessDTO</groupId>
            <artifactId>PaperlessDTO</artifactId>
            <version>4.6.1.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/PaperlessDTO-4.6.1.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>sadk</groupId>
            <artifactId>sadk</artifactId>
            <version>3.7.1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/sadk-3.7.1.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>SealSADK7</groupId>
            <artifactId>SealSADK7</artifactId>
            <version>5.6.4.2</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/SealSADK7-5.6.4.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>logback-cfca</groupId>
            <artifactId>logback-cfca</artifactId>
            <version>4.2.1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/logback-cfca-jdk1.6-4.2.1.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>paperless-sadk-ext-cfca</groupId>
            <artifactId>paperless-sadk-ext-cfca</artifactId>
            <version>3.1.0.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/paperless-sadk-ext-3.1.0.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.apache.axis</groupId>
            <artifactId>axis-saaj</artifactId>
            <version>1.4</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/saaj.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>wsdl4j</groupId>
            <artifactId>wsdl4j</artifactId>
            <version>1.4</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/wsdl4j.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>slf4j</groupId>
            <artifactId>slf4j</artifactId>
            <version>1.7.28</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/slf4j-api-1.7.28.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>officeConvertServlet</groupId>
            <artifactId>officeConvertServlet</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/OfficeConvertServlet.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.5.10</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.hand.hap.boot.MainApplication</mainClass>
                    <!--<skip>true</skip>-->
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.6.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <finalName>gtzl</finalName>
    </build>

    <repositories>
        <repository>
            <id>hls-public</id>
            <url>http://hel.hand-china.com/nexus/content/groups/public/</url>
        </repository>
        <repository>
            <id>RDC thirdparty</id>
            <name>RDC thirdparty Repository</name>
            <url>http://nexus.saas.hand-china.com/content/repositories/thirdparty</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>hls public</id>
            <name>hls public</name>
            <url>http://hel.hand-china.com/nexus/content/groups/public/</url>
        </pluginRepository>
        <pluginRepository>
            <id>RDC thirdparty</id>
            <name>RDC thirdparty Repository</name>
            <url>http://nexus.saas.hand-china.com/content/repositories/thirdparty</url>
        </pluginRepository>
    </pluginRepositories>

</project>
