package com.hand.hls.inv.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

@ExtensionAttribute(disable = true)
@Table(name = "inv_finance_attachment")
public class HlsCusFinanceAttachment extends BaseDTO {

    public static final String FIELD_INV_ATTACHMENT_ID = "invAttachmentId";
    public static final String FIELD_PURCHASE_ID = "purchaseId";
    public static final String FIELD_INV_ATTACHMENT_CATEGORY = "invAttachmentCategory";
    public static final String FIELD_DOCUMENT_NAME = "documentName";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_MAKE_UP = "makeUp";


    @Id
    @GeneratedValue
    private Long invAttachmentId; //投资理财伙伴附件ID

    @NotNull
    private Long purchaseId; //投资理财ID

    @NotEmpty
    @Length(max = 200)
    private String invAttachmentCategory; //投资理财附件类别

    @Length(max = 2000)
    private String documentName; //投资理财名称

    @Length(max = 2000)
    private String description; //说明备注

    @Length(max = 100)
    private String makeUp; //是否补录

    @Length(max = 255)
    private String status;//附件状态

    private Long sourceId;

    @Transient
    private String fileName;
    @Transient
    private Long fileSize;
    @Transient
    private String uploadDate;
    //上传人
    @Transient
    private String uploadPerson;

    //是否是最新的
    @Transient
    private String updateStatus;

    @Transient
    private String fileNames;

    @Transient
    private String fileId;

    @Transient
    private String sourceKey;

    @Transient
    private String sourceType;

    @Transient
    private Long attachmentId;

    @Transient
    private String fileType;

    private String isFinalPrint;//是否最终用印

    private String copies;//份数

    private String stampName;//印章名称

    private String printComment;//用印意见

    private String orgStampName;//申请公章

    private String npStampName;//申请法人章

    public String getOrgStampName() {
        return orgStampName;
    }

    public void setOrgStampName(String orgStampName) {
        this.orgStampName = orgStampName;
    }

    public String getNpStampName() {
        return npStampName;
    }

    public void setNpStampName(String npStampName) {
        this.npStampName = npStampName;
    }

    public String getIsFinalPrint() {
        return isFinalPrint;
    }

    public void setIsFinalPrint(String isFinalPrint) {
        this.isFinalPrint = isFinalPrint;
    }

    public String getCopies() {
        return copies;
    }

    public void setCopies(String copies) {
        this.copies = copies;
    }

    public String getStampName() {
        return stampName;
    }

    public void setStampName(String stampName) {
        this.stampName = stampName;
    }

    public String getPrintComment() {
        return printComment;
    }

    public void setPrintComment(String printComment) {
        this.printComment = printComment;
    }

    public Long getSourceId() {
        return sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public String getFileNames() {
        return fileNames;
    }

    public void setFileNames(String fileNames) {
        this.fileNames = fileNames;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getSourceKey() {
        return sourceKey;
    }

    public void setSourceKey(String sourceKey) {
        this.sourceKey = sourceKey;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public Long getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(String uploadDate) {
        this.uploadDate = uploadDate;
    }

    public String getUploadPerson() {
        return uploadPerson;
    }

    public void setUploadPerson(String uploadPerson) {
        this.uploadPerson = uploadPerson;
    }

    public String getUpdateStatus() {
        return updateStatus;
    }

    public void setUpdateStatus(String updateStatus) {
        this.updateStatus = updateStatus;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setInvAttachmentId(Long invAttachmentId) {
        this.invAttachmentId = invAttachmentId;
    }

    public Long getInvAttachmentId() {
        return invAttachmentId;
    }

    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    public Long getPurchaseId() {
        return purchaseId;
    }

    public void setInvAttachmentCategory(String invAttachmentCategory) {
        this.invAttachmentCategory = invAttachmentCategory;
    }

    public String getInvAttachmentCategory() {
        return invAttachmentCategory;
    }

    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    public String getDocumentName() {
        return documentName;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setMakeUp(String makeUp) {
        this.makeUp = makeUp;
    }

    public String getMakeUp() {
        return makeUp;
    }

}
