package com.hand.hls.lease.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@Data
@ExtensionAttribute(disable=true)
@Table(name = "CON_LEASE_ITEM_INSURANCE")
@Getter
@Setter
public class LeaseItemInsurance extends BaseDTO {

     public static final String FIELD_INSURANCE_ID = "insuranceId";
     public static final String FIELD_INSURANCE_TYPE = "insuranceType";
     public static final String FIELD_INSURANCE_DATE_FROM = "insuranceDateFrom";
     public static final String FIELD_INSURANCE_DATE_TO = "insuranceDateTo";
     public static final String FIELD_INSURANCE_COMPANY = "insuranceCompany";
     public static final String FIELD_INSURANCE_NUMBER = "insuranceNumber";
     public static final String FIELD_INSURANCE_AMOUNT = "insuranceAmount";
     public static final String FIELD_FIRST_BENEFICIARY = "firstBeneficiary";
     public static final String FIELD_CON_LEASE_ITEM_ID = "conLeaseItemId";


     @Id
     @GeneratedValue
     private Long insuranceId;

     @Length(max = 200)
     private String insuranceType;

     private Date insuranceDateFrom;

     private Date insuranceDateTo;

     @Length(max = 200)
     private String insuranceCompany;

     @Length(max = 100)
     private String insuranceNumber;

     private Double insuranceAmount;

     @Length(max = 100)
     private String firstBeneficiary;

     private Long conLeaseItemId;

     @Transient
     private String insuranceTypeN;

     /**
      * 投保人
      */
     private String applicantName;

     /**
      * 被保险人
      */
     private String insuredName;

     @Transient
     private  String contractNumber;
     @Transient
     private  String contractName;
     @Transient
     private  String fullName;

     }
