package com.hand.hls.plm.pli.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "PLM_PLI_UPCOMING")
public class PlmPliUpcoming extends BaseDTO {

    public static final String FIELD_UPCOMING_ID = "upcomingId";
    public static final String FIELD_BP_ID = "bpId";
    public static final String FIELD_BP_NAME = "bpName";
    public static final String FIELD_INSPECTION_TYPE = "inspectionType";
    public static final String FIELD_APPOINTED_DATE = "appointedDate";
    public static final String FIELD_REMIND_DATE = "remindDate";
    public static final String FIELD_ENABLE_FLAG = "enableFlag";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_STATUS = "status";




    @Id
    @GeneratedValue
    private Long upcomingId;

    @NotNull
    private Long bpId;

    @Length(max = 100)
    @NotNull
    private String bpName;

    @Length(max = 100)
    @NotNull
    private String inspectionType;

    @Length(max = 100)
    private String status;

    private Date appointedDate;

    private Date remindDate;

    @Length(max = 100)
    private String enableFlag;

    @Length(max = 2000)
    private String description;

    @Transient
    private String bpCode;

    @Transient
    private String appointedYear;

    @Transient
    private String appointedMonth;

    @Transient
    private String isPlaneCheck;

    @Transient
    private String inspectionTypeN;

    public String getInspectionTypeN() {
        return inspectionTypeN;
    }

    public void setInspectionTypeN(String inspectionTypeN) {
        this.inspectionTypeN = inspectionTypeN;
    }

    public void setUpcomingId(Long upcomingId) {
        this.upcomingId = upcomingId;
    }

    public Long getUpcomingId() {
        return upcomingId;
    }

    public void setBpId(Long bpId) {
        this.bpId = bpId;
    }

    public Long getBpId() {
        return bpId;
    }

    public void setBpName(String bpName) {
        this.bpName = bpName;
    }

    public String getBpName() {
        return bpName;
    }

    public void setInspectionType(String inspectionType) {
        this.inspectionType = inspectionType;
    }

    public String getInspectionType() {
        return inspectionType;
    }

    public void setAppointedDate(Date appointedDate) {
        this.appointedDate = appointedDate;
    }

    public Date getAppointedDate() {
        return appointedDate;
    }

    public void setRemindDate(Date remindDate) {
        this.remindDate = remindDate;
    }

    public Date getRemindDate() {
        return remindDate;
    }

    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    public String getEnableFlag() {
        return enableFlag;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getBpCode() {
        return bpCode;
    }

    public void setBpCode(String bpCode) {
        this.bpCode = bpCode;
    }

    public String getAppointedYear() {
        return appointedYear;
    }

    public void setAppointedYear(String appointedYear) {
        this.appointedYear = appointedYear;
    }

    public String getAppointedMonth() {
        return appointedMonth;
    }

    public void setAppointedMonth(String appointedMonth) {
        this.appointedMonth = appointedMonth;
    }

    public String getIsPlaneCheck() {
        return isPlaneCheck;
    }

    public void setIsPlaneCheck(String isPlaneCheck) {
        this.isPlaneCheck = isPlaneCheck;
    }
}
