server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@//172.17.236.28:1521/orcl
    username: C##gt_dev
    password: gt_dev
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      remove-abandoned: true
      remove-abandoned-timeout: 36000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: handhand
        url-pattern: /druid/*
      max-active: 200
      min-idle: 200
  session:
    store-type: redis
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  http:
    multipart:
      max-file-size: 2048Mb
      max-request-size: 10240Mb
redis:
  ip: ${REDIS_IP:127.0.0.1}
  db: ${REDIS_DB:1}

#db.type property is used for activiti
db:
  type: oracle
  #type: oracle
  #type: mssql
  #type: postgresql
#mybatis.identity property is userd for mybatis Self-increasing primaryKey strategy
mybatis:
  identity: SEQUENCE
  #identity: SEQUENCE

security:
  basic:
    enabled: false

file:
  upload:
    dir: /u01/hls_attachment
    #dir: /root/HLS/app/attachment
#    dir: /data/files

endpoints:
  actuator:
    enabled: false
---
activiti:
  mailServerHost: smtp.126.com
  mailServerPassword: hapdev11
  mailServerUsername: hap_dev@126.com
  mailServerPort: 25
cas:
  service: http://localhost:8080/hap/login/cas
  ssoserver:
    logouturl: https://login.hand-china.com/sso/logout?service=http://localhost:8080/hap
    loginurl: https://login.hand-china.com/sso/login
    url: https://login.hand-china.com/sso
ldap:
  server:
    url: ldap://localhost:389/
  conn:
    password: secret
    userDn: cn=Manager,dc=hand,dc=com
  user:
    search:
      filter: (uid={0})
      base: dc=hand,dc=com
project:
  buildDate: ${project.buildDate}
sys:
  security:
    token:
      validate: false
message:
  provider: redis

leaf:
  uploadFileDirectory: /u01/upload
job:
  autoStartup: true
spring:
  resources:
    static-locations: classpath:/leaf_static,classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources/leaf_static,classpath:/META-INF/resources,servlet context:/
# jacob
jacob:
  start: false
  jacobUrl: http://localhost:8666/leaf_jczl/jacob
  jacobServiceUrl: http://localhost:8088/jacob/jacob
  targetPath: D:/pdf-temp/

custom:
  login:
    loginSwitch: true
    loginUrls: ldap://SZIDC-DC01.gdh.local:389,ldap://SZIDC-DC02.gdh.local:389,ldap://HKGDH-DC01.gdh.local:389,ldap://HKGDH-DC02.gdh.local:389
# 访问接口
intfPlatform:
  base: https://api-gateway.gdhcapital.com.cn
  accessTokenUrl: /oauth/oauth/token?grant_type=client_credentials&client_id=GDHCG-ZB-LBS&client_secret=5F69A44AF618461B&scope=default
  todoSendUrl: /hitf/v2p/rest/invoke/R0RIQ0c6SFpFUk8uVE9fRE86SktQVDAwMg==?access_token=
  toRenewUrl: /hitf/v2p/rest/invoke/R0RIQ0c6SFpFUk8uVE9fRE86SktQVDAwMi4wMQ==?access_token=
  todoSendUrlBefor: /hptl/v1/1/sync-todos/QQ?access_token=
  initializeAttachment: /hfle/v1/1/files/uuid?access_token=
  attachmentUpload: /hfle/v1/1/files/attachment/multipart?access_token=
  getAttachmentByUrl: https://api-gateway.gdhcapital.com.cn/hfle/v1/1/files/


