####ureport2  disable file system######
ureport.disableHttpSessionReportCache=false
ureport.disableFileProvider=true
ureport.fileStoreDir=/u01/web/hls4.0_leaf-yhzl/ureport
ureport.debug=false

#####REDIS INFO#######

redis.sentinel=\
  10.86.20.183:26379,\
  10.86.20.184:26379

#if redis.useSentinel is true, then redis.ip and redis.port is useless
#this value should always be true except local dev test
redis.useSentinel=false

redis.ip=localhost
redis.port=6379
redis.db=1
#redis.password=123456

####APPLICATION DB INFO######
db.jndiName=java:comp/env/jdbc/hls_hap_dev

#db.type property is used for activiti
db.type=oracle
#db.type=oracle
#db.type=mssql
#db.type=hana
#db.type=postgresql

#mybatis.identity=SEQUENCE
mybatis.identity=SEQUENCE

#environment
env.code=SIT



#SIT


#job
job.autoStartup=true

#build number
project.buildDate=${project.buildDate}

#CAS
cas.service=http://localhost:8080/login/cas
cas.ssoserver.loginurl=https://login.hand-china.com/sso/login
cas.ssoserver.url=https://login.hand-china.com/sso
cas.ssoserver.logouturl=https://login.hand-china.com/sso/logout?service=http://localhost:8080

#LDAP
ldap.server.url=ldap://localhost:389/
ldap.conn.userDn=cn=Manager,dc=hand,dc=com
ldap.conn.password=secret
ldap.user.search.base=dc=hand,dc=com
ldap.user.search.filter=(uid={0})

#REDISSON
#  multiple redis such as
#  redisson.server.url=\
#    127.0.0.1:6379,\
#    10.211.103.142:6379

#redisson.server.url=
#redissson.server.password=

# Activiti MailServer
activiti.mailServerHost=smtp.126.com
activiti.mailServerPort=25
activiti.mailServerUsername=hap_dev@126.com
activiti.mailServerPassword=

# Message-Redis
message.provider=redis

# Message-RabbitMQ
#message.provider=rabbitmq
#rabbitmq.host=localhost
#rabbitmq.username=guest
#rabbitmq.password=guest
#rabbitmq.port=5672

#redis.topic.channel.prefix=HAP
leaf.base.dir=classpath:leaf_static/
leaf.config.dir=classpath:leaf_static/WEB-INF/
sys.security.token.validate=false

#form flexible
leaf.form.flexible=true

password.encrypt=true

#���߱༭
#���߱༭��Ӧ��ʱʱ��
files.docservice.timeout=120000
#files.docservice.host.url=http://leafcloud.hand-china.com
#web�ķ��ʵ�ַ
files.docservice.host.url=http://192.168.110.238:8660/leaf_jczl
#�Ƿ�������У�飬������������������ip����У��
files.docservice.enableAccessControl=false
#documentService�������ڵ�ַ Ĭ�϶˿� 8765
files.docservice.url=http://192.168.110.242:8765
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false


