package com.hand.hls.hn.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "PRJ_CHECK_PROJECT_SCHEDULE")
public class PrjCheckProjectSchedule extends BaseDTO {

     public static final String FIELD_PROJECT_SCHEDULE_ID = "projectScheduleId";
     public static final String FIELD_CHECK_ID = "checkId";
     public static final String FIELD_PROJECT_DESC = "projectDesc";
     public static final String FIELD_PROJECT_DESC_N = "projectDescN";
     public static final String FIELD_PLAN_PUT_MONEY = "planPutMoney";
     public static final String FIELD_PUT_MONEY = "putMoney";
     public static final String FIELD_PUT_SCHEDULE = "putSchedule";
     public static final String FIELD_REMARK = "remark";





     @Id
     @GeneratedValue
     private Long projectScheduleId;

     private Long checkId;

     private String projectDesc;
     @Transient
     private String projectDescN;
     private String planPutMoney;
     private String putMoney;
     private String putSchedule;
     private String remark;

     public Long getProjectScheduleId() {
          return projectScheduleId;
     }

     public void setProjectScheduleId(Long projectScheduleId) {
          this.projectScheduleId = projectScheduleId;
     }

     public Long getCheckId() {
          return checkId;
     }

     public void setCheckId(Long checkId) {
          this.checkId = checkId;
     }

     public String getProjectDesc() {
          return projectDesc;
     }

     public void setProjectDesc(String projectDesc) {
          this.projectDesc = projectDesc;
     }

     public String getPlanPutMoney() {
          return planPutMoney;
     }

     public void setPlanPutMoney(String planPutMoney) {
          this.planPutMoney = planPutMoney;
     }

     public String getPutMoney() {
          return putMoney;
     }

     public void setPutMoney(String putMoney) {
          this.putMoney = putMoney;
     }

     public String getPutSchedule() {
          return putSchedule;
     }

     public void setPutSchedule(String putSchedule) {
          this.putSchedule = putSchedule;
     }

     public String getRemark() {
          return remark;
     }

     public void setRemark(String remark) {
          this.remark = remark;
     }

     public String getProjectDescN() {
          return projectDescN;
     }

     public void setProjectDescN(String projectDescN) {
          this.projectDescN = projectDescN;
     }
}
