package com.hand.hls.hn.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@ExtensionAttribute(disable=true)
@Table(name = "PRJ_CHECK_SUBJECT_CHANGE")
public class PrjCheckSubjectChange extends BaseDTO {

     public static final String FIELD_SUBJECT_CHANGE_ID = "subjectChangeId";
     public static final String FIELD_CHECK_ID = "checkId";
     public static final String FIELD_CONTRACT_NUMBER = "contractNumber";
     public static final String FIELD_BP_NAME = "bpName";
     public static final String FIELD_BP_RISK_WARN = "bpRiskWarn";
     public static final String FIELD_GUARANTOR = "guarantor";
     public static final String FIELD_GUARANTOR_RISK_WARN = "guarantorRiskWarn";
     public static final String FIELD_REMARK = "remark";





     @Id
     @GeneratedValue
     private Long subjectChangeId;

     private Long checkId;

     private String contractNumber;
     private String bpName;
     private String bpRiskWarn;
     private String guarantor;
     private String guarantorRiskWarn;
     private String remark;

     @Transient
     private Long bpId;

     @Transient
     private Long projectId;

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Long getBpId() {
        return bpId;
    }

    public void setBpId(Long bpId) {
        this.bpId = bpId;
    }

    public Long getSubjectChangeId() {
          return subjectChangeId;
     }

     public void setSubjectChangeId(Long subjectChangeId) {
          this.subjectChangeId = subjectChangeId;
     }

     public Long getCheckId() {
          return checkId;
     }

     public void setCheckId(Long checkId) {
          this.checkId = checkId;
     }

     public String getContractNumber() {
          return contractNumber;
     }

     public void setContractNumber(String contractNumber) {
          this.contractNumber = contractNumber;
     }

     public String getBpName() {
          return bpName;
     }

     public void setBpName(String bpName) {
          this.bpName = bpName;
     }

     public String getBpRiskWarn() {
          return bpRiskWarn;
     }

     public void setBpRiskWarn(String bpRiskWarn) {
          this.bpRiskWarn = bpRiskWarn;
     }

     public String getGuarantor() {
          return guarantor;
     }

     public void setGuarantor(String guarantor) {
          this.guarantor = guarantor;
     }

     public String getGuarantorRiskWarn() {
          return guarantorRiskWarn;
     }

     public void setGuarantorRiskWarn(String guarantorRiskWarn) {
          this.guarantorRiskWarn = guarantorRiskWarn;
     }

     public String getRemark() {
          return remark;
     }

     public void setRemark(String remark) {
          this.remark = remark;
     }
}
