package com.hand.hls.hn.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@ExtensionAttribute(disable=true)
@Table(name = "PRJ_CHECK_PROJECT_SITUATION")
public class PrjCheckProjectSituation extends BaseDTO {

     public static final String FIELD_PROJECT_SITUATION_ID = "projectSituationId";
     public static final String FIELD_CHECK_ID = "checkId";
     public static final String FIELD_CONTRACT_NUMBER = "contractNumber";
     public static final String FIELD_REMARK = "remark";





     @Id
     @GeneratedValue
     private Long projectSituationId;

     private Long checkId;

     private String contractNumber;
     private String remark;

     @Transient
     private Long projectId;

     @Transient
     private Long refProjectId;

    public Long getRefProjectId() {
        return refProjectId;
    }

    public void setRefProjectId(Long refProjectId) {
        this.refProjectId = refProjectId;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Long getProjectSituationId() {
          return projectSituationId;
     }

     public void setProjectSituationId(Long projectSituationId) {
          this.projectSituationId = projectSituationId;
     }

     public Long getCheckId() {
          return checkId;
     }

     public void setCheckId(Long checkId) {
          this.checkId = checkId;
     }

     public String getContractNumber() {
          return contractNumber;
     }

     public void setContractNumber(String contractNumber) {
          this.contractNumber = contractNumber;
     }

     public String getRemark() {
          return remark;
     }

     public void setRemark(String remark) {
          this.remark = remark;
     }
}
