package com.hand.hls.hn.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "PRJ_LEASE_FACTORY_BUILDING")
public class PrjLeaseFactoryBuilding extends BaseDTO {

     public static final String FIELD_BUILDING_ID = "buildingId";
     public static final String FIELD_PRJ_LEASE_ID = "prjLeaseId";
     public static final String FIELD_BUILDING_STRUCTURE = "buildingStructure";
     public static final String FIELD_BUILDING_STRUCTURE_N = "buildingStructureN";
     public static final String FIELD_BUILDING_FACILITY = "buildingFacility";
     public static final String FIELD_WORKSHOP_LAYOUT = "workshopLayout";
     public static final String FIELD_WORKSHOP_LAYOUT_N = "workshopLayoutN";
     public static final String FIELD_WORKSHOP_CLEAN_FREQUENCY = "workshopCleanFrequency";
     public static final String FIELD_CLEAN_HOURS = "cleanHours";
     public static final String FIELD_WORKSHOP_SAFE_FLAG = "workshopSafeFlag";
     public static final String FIELD_WORKSHOP_SAFE_FLAG_N = "workshopSafeFlagN";




     @Id
     @GeneratedValue
     private Long buildingId;

     private Long prjLeaseId;

     private String buildingStructure;
     private String buildingFacility;
     private String workshopLayout;
     private String workshopCleanFrequency;
     private String cleanHours;
     private String workshopSafeFlag;
     @Transient
     private String workshopSafeFlagN;
     @Transient
     private String workshopLayoutN;
     @Transient
     private String buildingStructureN;
     public Long getBuildingId() {
          return buildingId;
     }

     public void setBuildingId(Long buildingId) {
          this.buildingId = buildingId;
     }

     public Long getPrjLeaseId() {
          return prjLeaseId;
     }

     public void setPrjLeaseId(Long prjLeaseId) {
          this.prjLeaseId = prjLeaseId;
     }

     public String getBuildingStructure() {
          return buildingStructure;
     }

     public void setBuildingStructure(String buildingStructure) {
          this.buildingStructure = buildingStructure;
     }

     public String getBuildingFacility() {
          return buildingFacility;
     }

     public void setBuildingFacility(String buildingFacility) {
          this.buildingFacility = buildingFacility;
     }

     public String getWorkshopLayout() {
          return workshopLayout;
     }

     public void setWorkshopLayout(String workshopLayout) {
          this.workshopLayout = workshopLayout;
     }

     public String getWorkshopCleanFrequency() {
          return workshopCleanFrequency;
     }

     public void setWorkshopCleanFrequency(String workshopCleanFrequency) {
          this.workshopCleanFrequency = workshopCleanFrequency;
     }

     public String getCleanHours() {
          return cleanHours;
     }

     public void setCleanHours(String cleanHours) {
          this.cleanHours = cleanHours;
     }

     public String getWorkshopSafeFlag() {
          return workshopSafeFlag;
     }

     public void setWorkshopSafeFlag(String workshopSafeFlag) {
          this.workshopSafeFlag = workshopSafeFlag;
     }

     public String getWorkshopSafeFlagN() {
          return workshopSafeFlagN;
     }

     public void setWorkshopSafeFlagN(String workshopSafeFlagN) {
          this.workshopSafeFlagN = workshopSafeFlagN;
     }

     public String getWorkshopLayoutN() {
          return workshopLayoutN;
     }

     public void setWorkshopLayoutN(String workshopLayoutN) {
          this.workshopLayoutN = workshopLayoutN;
     }

     public String getBuildingStructureN() {
          return buildingStructureN;
     }

     public void setBuildingStructureN(String buildingStructureN) {
          this.buildingStructureN = buildingStructureN;
     }
}
