package com.hand.hls.hn.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "PRJ_LEASE_INFO")
public class PrjLeaseInfo extends BaseDTO {

     public static final String FIELD_LEASE_INFO_ID = "leaseInfoId";
     public static final String FIELD_PRJ_LEASE_ID = "prjLeaseId";
     public static final String FIELD_WORK_HOURS = "workHours";
     public static final String FIELD_WORKER_NUM = "workerNum";
     public static final String FIELD_WORK_TYPE = "workType";
     public static final String FIELD_PRODUCE_DESC = "produceDesc";
     public static final String FIELD_LEASE_QUALITY_DESC = "leaseQualityDesc";
     public static final String FIELD_LEASE_EXCEPT_FLAG = "leaseExceptFlag";
     public static final String FIELD_EXCEPT_DESC = "exceptDesc";
     public static final String FIELD_MAINTAIN_FREQUENCY_CONTENT = "maintainFrequencyContent";
     public static final String FIELD_CHECK_FREQUENCY_CONTENT = "checkFrequencyContent";
     public static final String FIELD_MAINTAIN_WORKER = "maintainWorker";
     public static final String FIELD_PRACTICE_QUALIFY = "practiceQualify";
     public static final String FIELD_SYSTEM_MADE_FLAG = "systemMadeFlag";
     public static final String FIELD_LEASE_IN_PLACE = "leaseInPlace";
     public static final String FIELD_EQUIP_SAFE_FLAG= "equipSafeFlag";
     public static final String FIELD_STOP_FREQUENCY_CONTENT = "stopFrequencyContent";
     public static final String FIELD_PRODUCER_SAFE_EQUIP = "producerSafeEquip";
     public static final String FIELD_CONCLUSION_SUGGEST = "conclusionSuggest";



     @Id
     @GeneratedValue
     private Long leaseInfoId;

     private Long prjLeaseId;

     private String workHours;
     private String workerNum;
     private String workType;
     private String produceDesc;
     private String leaseQualityDesc;
     private String leaseExceptFlag;
     private String exceptDesc;
     private String maintainFrequencyContent;
     private String checkFrequencyContent;
     private String maintainWorker;
     private String practiceQualify;
     private String systemMadeFlag;
     private String leaseInPlace;
     private String equipSafeFlag;
     private String stopFrequencyContent;
     private String producerSafeEquip;
     private String conclusionSuggest;

     //ASSET_NAME
     private String assetName;
     //SPECIFICATION
    private String specification;
    //MANUFACTURER
    private String manufacturer;
    //ASSET_NUM
    private String assetNum;
    //INSTALLATION_SITE
    private String installationSite;
    private String leaseItemCode;
    private Long leaseItemId;

    public Long getLeaseItemId() {
        return leaseItemId;
    }

    public void setLeaseItemId(Long leaseItemId) {
        this.leaseItemId = leaseItemId;
    }

    public String getLeaseItemCode() {
        return leaseItemCode;
    }

    public void setLeaseItemCode(String leaseItemCode) {
        this.leaseItemCode = leaseItemCode;
    }

    @Transient
    private String venderIdN;

    @Transient
    private String leaseContractSameFlagN;
    @Transient
    private String checkStatusN;

    private String actualPhotoFlag;
    @Transient
    private String actualPhotoFlagN;
    private String leaseContractSameFlag;
    private String checkStatus;

    //DIFFERENT_DESC
    private String differentDesc;

    //INSURE_REASON
    private String insureReason;

    public String getDifferentDesc() {
        return differentDesc;
    }

    public void setDifferentDesc(String differentDesc) {
        this.differentDesc = differentDesc;
    }

    public String getInsureReason() {
        return insureReason;
    }

    public void setInsureReason(String insureReason) {
        this.insureReason = insureReason;
    }

    public String getActualPhotoFlag() {
        return actualPhotoFlag;
    }

    public void setActualPhotoFlag(String actualPhotoFlag) {
        this.actualPhotoFlag = actualPhotoFlag;
    }

    public String getActualPhotoFlagN() {
        return actualPhotoFlagN;
    }

    public void setActualPhotoFlagN(String actualPhotoFlagN) {
        this.actualPhotoFlagN = actualPhotoFlagN;
    }

    public String getCheckStatusN() {
        return checkStatusN;
    }

    public void setCheckStatusN(String checkStatusN) {
        this.checkStatusN = checkStatusN;
    }

    public String getLeaseContractSameFlag() {
        return leaseContractSameFlag;
    }

    public void setLeaseContractSameFlag(String leaseContractSameFlag) {
        this.leaseContractSameFlag = leaseContractSameFlag;
    }

    public String getCheckStatus() {
        return checkStatus;
    }

    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus;
    }

    public String getLeaseContractSameFlagN() {
        return leaseContractSameFlagN;
    }

    public void setLeaseContractSameFlagN(String leaseContractSameFlagN) {
        this.leaseContractSameFlagN = leaseContractSameFlagN;
    }

    public String getVenderIdN() {
        return venderIdN;
    }

    public void setVenderIdN(String venderIdN) {
        this.venderIdN = venderIdN;
    }

    public String getAssetName() {
        return assetName;
    }

    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    public String getSpecification() {
        return specification;
    }

    public void setSpecification(String specification) {
        this.specification = specification;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getAssetNum() {
        return assetNum;
    }

    public void setAssetNum(String assetNum) {
        this.assetNum = assetNum;
    }

    public String getInstallationSite() {
        return installationSite;
    }

    public void setInstallationSite(String installationSite) {
        this.installationSite = installationSite;
    }

    public Long getLeaseInfoId() {
          return leaseInfoId;
     }

     public void setLeaseInfoId(Long leaseInfoId) {
          this.leaseInfoId = leaseInfoId;
     }

     public Long getPrjLeaseId() {
          return prjLeaseId;
     }

     public void setPrjLeaseId(Long prjLeaseId) {
          this.prjLeaseId = prjLeaseId;
     }

     public String getWorkHours() {
          return workHours;
     }

     public void setWorkHours(String workHours) {
          this.workHours = workHours;
     }

     public String getWorkerNum() {
          return workerNum;
     }

     public void setWorkerNum(String workerNum) {
          this.workerNum = workerNum;
     }

     public String getWorkType() {
          return workType;
     }

     public void setWorkType(String workType) {
          this.workType = workType;
     }

     public String getProduceDesc() {
          return produceDesc;
     }

     public void setProduceDesc(String produceDesc) {
          this.produceDesc = produceDesc;
     }

     public String getLeaseQualityDesc() {
          return leaseQualityDesc;
     }

     public void setLeaseQualityDesc(String leaseQualityDesc) {
          this.leaseQualityDesc = leaseQualityDesc;
     }

     public String getLeaseExceptFlag() {
          return leaseExceptFlag;
     }

     public void setLeaseExceptFlag(String leaseExceptFlag) {
          this.leaseExceptFlag = leaseExceptFlag;
     }

     public String getExceptDesc() {
          return exceptDesc;
     }

     public void setExceptDesc(String exceptDesc) {
          this.exceptDesc = exceptDesc;
     }

     public String getMaintainFrequencyContent() {
          return maintainFrequencyContent;
     }

     public void setMaintainFrequencyContent(String maintainFrequencyContent) {
          this.maintainFrequencyContent = maintainFrequencyContent;
     }

     public String getCheckFrequencyContent() {
          return checkFrequencyContent;
     }

     public void setCheckFrequencyContent(String checkFrequencyContent) {
          this.checkFrequencyContent = checkFrequencyContent;
     }

     public String getMaintainWorker() {
          return maintainWorker;
     }

     public void setMaintainWorker(String maintainWorker) {
          this.maintainWorker = maintainWorker;
     }

     public String getPracticeQualify() {
          return practiceQualify;
     }

     public void setPracticeQualify(String practiceQualify) {
          this.practiceQualify = practiceQualify;
     }

     public String getSystemMadeFlag() {
          return systemMadeFlag;
     }

     public void setSystemMadeFlag(String systemMadeFlag) {
          this.systemMadeFlag = systemMadeFlag;
     }

     public String getLeaseInPlace() {
          return leaseInPlace;
     }

     public void setLeaseInPlace(String leaseInPlace) {
          this.leaseInPlace = leaseInPlace;
     }

     public String getEquipSafeFlag() {
          return equipSafeFlag;
     }

     public void setEquipSafeFlag(String equipSafeFlag) {
          this.equipSafeFlag = equipSafeFlag;
     }

     public String getStopFrequencyContent() {
          return stopFrequencyContent;
     }

     public void setStopFrequencyContent(String stopFrequencyContent) {
          this.stopFrequencyContent = stopFrequencyContent;
     }

     public String getProducerSafeEquip() {
          return producerSafeEquip;
     }

     public void setProducerSafeEquip(String producerSafeEquip) {
          this.producerSafeEquip = producerSafeEquip;
     }

     public String getConclusionSuggest() {
          return conclusionSuggest;
     }

     public void setConclusionSuggest(String conclusionSuggest) {
          this.conclusionSuggest = conclusionSuggest;
     }
}
