package com.hand.hls.cont.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "BILL_MANAGEMENT")
@Getter
@Setter
public class HlsCusBillManagement extends BaseDTO {

    public static final String FIELD_BILL_MANAGEMENT_ID = "billManagementId";
    public static final String FIELD_BANK_ID = "bankId";
    public static final String FIELD_BANK_ACCOUNT_ID = "bankAccountId";
    public static final String FIELD_ACCOUNT_NATURE = "accountNature";
    public static final String FIELD_TICKET_TYPE = "ticketType";
    public static final String FIELD_DRAWER = "drawer";
    public static final String FIELD_TICKET_COLLECTOR = "ticketCollector";
    public static final String FIELD_CONTRACT_ID = "contractId";
    public static final String FIELD_TICKET_NUMBER = "ticketNumber";
    public static final String FIELD_BILL_AMOUNT = "billAmount";
    public static final String FIELD_ISSUE_DATE = "issueDate";
    public static final String FIELD_EXPIRY_DATE = "expiryDate";
    public static final String FIELD_BILL_STATUS = "billStatus";
    public static final String FIELD_TRANSFERABLE_FLAG = "transferableFlag";
    public static final String FIELD_WFL_STATUS = "wflStatus";


    @Id
    @GeneratedValue
    private Long billManagementId;

    private Long bankId;

    private Long bankAccountId;

    @Length(max = 30)
    private String accountNature;

    @Length(max = 30)
    private String ticketType;

    @Length(max = 500)
    private String drawer;

    @Length(max = 500)
    private String ticketCollector;

    private Long contractId;

    @Length(max = 500)
    private String ticketNumber;

    private Double billAmount;

    private Date issueDate;


    private Date expiryDate;

    @Length(max = 30)
    private String billStatus;

    @Length(max = 30)
    private String transferableFlag;

    @Length(max = 30)
    private String wflStatus;
    @Transient
    private String fileName;
    @Transient
    private Long fileSize;

    @Transient
    private String filePath;
    @Transient
    private String uploadDate;
    @Transient
    private String bankAccountTypeN;
    @Transient
    private String bankNameN;

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(String uploadDate) {
        this.uploadDate = uploadDate;
    }

    public String getUploadPerson() {
        return uploadPerson;
    }

    public void setUploadPerson(String uploadPerson) {
        this.uploadPerson = uploadPerson;
    }

    public Long getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    @Transient
    private String wflStatusDesc;
    //上传人

    public String getWflStatusDesc() {
        return wflStatusDesc;
    }

    public void setWflStatusDesc(String wflStatusDesc) {
        this.wflStatusDesc = wflStatusDesc;
    }

    @Transient
    private String uploadPerson;
    @Transient
    private String[] fileIds;

    @Transient
    private Long attachmentId;

    @Transient
    private String fileId;

    public String[] getFileIds() {
        return fileIds;
    }

    public void setFileIds(String[] fileIds) {
        this.fileIds = fileIds;
    }

    public String[] getFileTypeArr() {
        return fileTypeArr;
    }

    public void setFileTypeArr(String[] fileTypeArr) {
        this.fileTypeArr = fileTypeArr;
    }

    public String getBillManagementBatchId() {
        return billManagementBatchId;
    }

    public void setBillManagementBatchId(String billManagementBatchId) {
        this.billManagementBatchId = billManagementBatchId;
    }

    @Transient
    private String[] fileTypeArr;

    private String billManagementBatchId;
    @Transient
    private String bankName;
    @Transient
    private String bankAccountName;

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankAccountName() {
        return bankAccountName;
    }

    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    public String getBankAccountNum() {
        return bankAccountNum;
    }

    public void setBankAccountNum(String bankAccountNum) {
        this.bankAccountNum = bankAccountNum;
    }

    public String getBankAccountTypeDesc() {
        return bankAccountTypeDesc;
    }

    public void setBankAccountTypeDesc(String bankAccountTypeDesc) {
        this.bankAccountTypeDesc = bankAccountTypeDesc;
    }

    public String getTicketTypeN() {
        return ticketTypeN;
    }

    public void setTicketTypeN(String ticketTypeN) {
        this.ticketTypeN = ticketTypeN;
    }

    public String getContractName() {
        return contractName;
    }

    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    public String getContractNumber() {
        return contractNumber;
    }

    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    public String getBillStatusN() {
        return billStatusN;
    }

    public void setBillStatusN(String billStatusN) {
        this.billStatusN = billStatusN;
    }

    public String getTransferableFlagN() {
        return transferableFlagN;
    }

    public void setTransferableFlagN(String transferableFlagN) {
        this.transferableFlagN = transferableFlagN;
    }

    @Transient
    private String bankAccountNum;
    @Transient
    private String bankAccountTypeDesc;
    @Transient
    private String ticketTypeN;

    @Transient
    private String contractName;

    @Transient
    private String contractNumber;
    @Transient
    private String billStatusN;
    @Transient
    private String transferableFlagN;

    public void setBillManagementId(Long billManagementId) {
        this.billManagementId = billManagementId;
    }

    public Long getBillManagementId() {
        return billManagementId;
    }

    public void setBankId(Long bankId) {
        this.bankId = bankId;
    }

    public Long getBankId() {
        return bankId;
    }

    public void setBankAccountId(Long bankAccountId) {
        this.bankAccountId = bankAccountId;
    }

    public Long getBankAccountId() {
        return bankAccountId;
    }

    public void setAccountNature(String accountNature) {
        this.accountNature = accountNature;
    }

    public String getAccountNature() {
        return accountNature;
    }

    public void setTicketType(String ticketType) {
        this.ticketType = ticketType;
    }

    public String getTicketType() {
        return ticketType;
    }

    public void setDrawer(String drawer) {
        this.drawer = drawer;
    }

    public String getDrawer() {
        return drawer;
    }

    public void setTicketCollector(String ticketCollector) {
        this.ticketCollector = ticketCollector;
    }

    public String getTicketCollector() {
        return ticketCollector;
    }

    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    public Long getContractId() {
        return contractId;
    }

    public void setTicketNumber(String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }

    public String getTicketNumber() {
        return ticketNumber;
    }

    public void setBillAmount(Double billAmount) {
        this.billAmount = billAmount;
    }

    public Double getBillAmount() {
        return billAmount;
    }

    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    public Date getIssueDate() {
        return issueDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }

    public String getBillStatus() {
        return billStatus;
    }

    public void setTransferableFlag(String transferableFlag) {
        this.transferableFlag = transferableFlag;
    }

    public String getTransferableFlag() {
        return transferableFlag;
    }

    public void setWflStatus(String wflStatus) {
        this.wflStatus = wflStatus;
    }

    public String getWflStatus() {
        return wflStatus;
    }

}
