package com.hand.hls.cont.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable = true)
@Table(name = "CON_CONTRACT_PAYMENT_PT")
public class HlsCusConContractPaymentPt extends BaseDTO {

    public static final String FIELD_CONTRACT_PAYMENT_PT_ID = "contractPaymentPtId";
    public static final String FIELD_CONTRACT_ID = "contractId";
    public static final String FIELD_SATISFY_FLAG = "satisfyFlag";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_PAYMENT_NAME = "paymentName";


    @Id
    @GeneratedValue
    private Long contractPaymentPtId;

    private Long contractId;

    @Length(max = 255)
    private String satisfyFlag;

    @Length(max = 500)
    private String description;

    @Length(max = 255)
    private String paymentName;
    @Length(max = 255)
    private String meetFlag;

    private String practicableSituation;
    private String ifPracticable;
    private String ifImmunity;

    public String getMeetFlag() {
        return meetFlag;
    }

    public void setMeetFlag(String meetFlag) {
        this.meetFlag = meetFlag;
    }

    public void setContractPaymentPtId(Long contractPaymentPtId) {
        this.contractPaymentPtId = contractPaymentPtId;
    }

    public Long getContractPaymentPtId() {
        return contractPaymentPtId;
    }

    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    public Long getContractId() {
        return contractId;
    }

    public void setSatisfyFlag(String satisfyFlag) {
        this.satisfyFlag = satisfyFlag;
    }

    public String getSatisfyFlag() {
        return satisfyFlag;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setPaymentName(String paymentName) {
        this.paymentName = paymentName;
    }

    public String getPaymentName() {
        return paymentName;
    }

    public String getPracticableSituation() {
        return practicableSituation;
    }

    public void setPracticableSituation(String practicableSituation) {
        this.practicableSituation = practicableSituation;
    }

    public String getIfPracticable() {
        return ifPracticable;
    }

    public void setIfPracticable(String ifPracticable) {
        this.ifPracticable = ifPracticable;
    }

    public String getIfImmunity() {
        return ifImmunity;
    }

    public void setIfImmunity(String ifImmunity) {
        this.ifImmunity = ifImmunity;
    }
}
