package com.hand.hls.cont.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "con_contract")
@Getter
@Setter
public class HlsCusConContract extends ConContract {

    @Id
    @GeneratedValue
    private Long contractId;

    @NotNull
    private Long companyId;

    private Long projectId;

    private Long changeReqId;

    private Long quotationId;

    private String contractTextStatus;
    @Transient
    private String contractTextStatusN;
    @Transient
    private String annualPayTimesN;
    @Transient
    private String insuranceFlag;
    @Transient
    private String insuranceFlagN;
    @Transient
    private String leaseStartDateTo;
    @Transient
    private String leaseStartDateFrom;
    @Transient
    private String industryN;
    @Transient
    private String bpIdTenantN;
    @Transient
    private String manufacturerIdN;
    @Transient
    private String manufacturerCode;
    @Transient
    private String reviewLevelN;
    @Transient
    private String divisionN;
    @Transient
    private String employeeName;
    @Transient
    private String enterpriseScaleN;
    @Transient
    private String manufacturerBpName;
    @Transient
    private String factoryBpName;
    @Transient
    private String alipayStatus;//代扣签约状态
    @Transient
    private String alipayStatusN;//代扣签约状态
    @Transient
    private String venderBpName;
    @Transient
    private String sellerBpName;
    @Transient
    private String tenantBpName;
    @Transient
    private String bpClassN;
    @Transient
    private String enterpriseScale;
    @Transient
    private String legalPerson;
    @Transient
    private String cardNum;
    @Transient
    private String prjCreationDate;
    @Transient
    private String projectStatusN;
    @Transient
    private String signStatusN;
    @Transient
    private String paymentReqStatusN;
    @Transient
    private String leaseStartDateN;
    @Transient
    private String definitionName;
    @Transient
    private String priceListN;
    @Transient
    private String graceFlagN;

    private String businessConfirmStatus;

    @Transient
    private String retrievedBatchNumber;

    @Transient
    private String signTypeN;
    private String signType;

    @Transient
    private String businessConfirmStatusN;
    @Transient
    private String dealerBizCfmStatus;
    @Transient
    private String dealerBizCfmStatusN;

    @NotEmpty
    @Length(max = 100)
    private String documentType;
    @Transient
    private String documentTypeN;

    @NotEmpty
    @Length(max = 100)
    private String documentCategory;

    @NotEmpty
    @Length(max = 100)
    private String businessType;

    @Length(max = 100)
    private String contractNumber;

    @Length(max = 200)
    private String contractName;

    @Length(max = 100)
    private String contractStatus;

    @Transient
    private String baseContractStatus;


    @Length(max = 100)
    private String leaseChannel;
    @Transient
    private String leaseChannelN;

    private Long bpAccountId; //扣款账户

    @Length(max = 100)
    private String division;

    @Length(max = 1000)
    private String authorityRuleString;

    private Date signDate;

    private Date inceptionOfLease;

    private Long employeeId;

    private Long unitId;

    private Date leaseStartDate;

    private String priceList;//报价方案

    private String rentingFrequency;//还租频率

    private Date firstPayDate;

    private Date lastPayDate;

    private Date leaseEndDate;

    private Date originalRecallDate;

    private Date leaseCardRecallDate;

    private Date earlyTerminationDate;

    private Double conTerminationMoney;

    private Date terminationDate;

    private Date assignmentDate;

    private Long leaseTimes;

    private Long annualPayTimes;

    private Double leaseTerm;

    private Long payType;

    @Length(max = 10)
    private String currency;

    private Long taxTypeId;

    @Length(max = 1)
    private String vatFlag;

    private Double vatRate;

    private Double leaseItemAmount;

    private Double vatInput;

    private Long vatInputTaxTypeId;

    private Double vatInputTaxTypeRate;

    private Double downPaymentRatio;

    private Double downPayment;

    private Double netDownPayment;

    private Double vatDownPayment;

    private Double financeAmount;

    private Double netFinanceAmount;

    private Double vatFinanceAmount;

    private Double totalRental;

    private Double netTotalRental;

    private Double vatTotalRental;

    private Double totalInterest;

    private Double netTotalInterest;

    private Double vatTotalInterest;

    private Double leaseChargeRatio;

    private Double leaseCharge;

    private Double netLeaseCharge;

    private Double vatLeaseCharge;

    private Double leaseMgtFeeRatio;

    private Double leaseMgtFee;

    private Double netLeaseMgtFee;

    private Double comCostRate;

    private Double vatLeaseMgtFee;

    @Length(max = 30)
    private String leaseMgtFeeRule;

    private Double depositRatio;

    private Double deposit;

    @Length(max = 30)
    private String depositDeduction;

    private Double residualRatio;

    private Double residualValue;

    private Double netResidualValue;

    private Double vatResidualValue;

    private Double balloonRatio;

    private Double balloon;

    private Double netBalloon;

    private Double vatBalloon;

    @Length(max = 30)
    private String baseRateType;
    @Transient
    private String baseRateTypeN;

    private Double baseRate;

    private Double intRate;

    private Double intRateImplicit;

    @Length(max = 30)
    private String intRateType;

    private Double irr;

    private Double irrAfterTax;

    private Double pmt;
    @Transient
    private Double plusFinanceAmount;

    private Double pmtFirst;

    private Double annualMeanRate;

    @Length(max = 30)
    private String receivedStatus;

    @Length(max = 30)
    private String overdueStatus;

    @Length(max = 30)
    private String billingMethod;

    @Length(max = 30)
    private String billingStatus;

    @Length(max = 30)
    private String bizDayConvention;

    @Length(max = 30)
    private String billingProfile;

    @Length(max = 30)
    private String penaltyProfile;

    @Length(max = 100)
    private String floatingWay;

    private Double floatingWayRate;

    @Length(max = 100)
    private String floatingRangeMethod; //调息范围规则
    @Transient
    private String floatingRangeMethodN;

    private Double contractAmount; //合同金额

    private Long tenantId; //承租人ID

    private Double penaltyRate; //罚息率

    @Length(max = 255)
    private String inspectFrenquency; //贷后检查频率

    @Length(max = 255)
    private String prepaymentMethod; //提前还款方式

    @Length(max = 255)
    private String isInsure; //是否投保

    @Length(max = 255)
    private String writeOffAbleFlag; //可否核销

    private Long returnAccount; //回款账户

    private String dataClass;//合同类型(NORMAL/CHANGE_REQ/HISTORY)

    private Long refContractId;//合同变更指向原合同ID


    private String historyReason;//历史数据来源（HLS.HISTORY_REASON）

    private String absShowFlag;//ABS出表标志(Y:出表、N:不出表、C:默认)

    private Date estimateRentingDate;//预计起租日

    private String taxTypeCode;//税率类型

    private Date dayEndDate;

    private Long interestYearDays;//年计息天数

    private Double riskReserveRatio;//风险金计提
    @Transient
    private Long riskReserveRatioId;//风险准备金率ID
    @Transient
    private String receivedAmount; //期末业务余额

    private Long gracePeriod; //豁免期天数

    private Long overdueMaxDays;

    private String interestAmortizationMethod;//利息摊销方式

    private String offBalanceSheetFlag; //表外标志，逾期90天

    private String stampDuty;
    private String stampDutyAccruedAmount;
    private String postFlag;
    private String purStampDuty;
    private String purPostFlag;
    private String purStampDutyAccruedAmount;

    private Long mortgageInstanceId;


    private String printStatus;

    @Transient
    private String inceptionOfLeaseTo;
    @Transient
    private String inceptionOfLeaseFrom;

    private Double xirr;

    private Double xirrNet;

    private String fiveClassificationResult;

    private String leaseItemType;

    @Transient
    private String fiveClassificationResultN;

    @Transient
    private String paymentMethod;
    @Transient
    private String amortizationMethod;

    @Transient
    private String interestAmortizationMethodN;//利息摊销方式

    @Transient
    private String paymentMethodN;

    @Transient
    private String amortizationMethodN;

    @Transient
    private Date applyPayDate;

    @Transient
    private Double netDueAmount;

    @Transient
    private Double dueAmount;
    @Transient
    private Double itemNum;
    @Transient
    private Double contractDiscount;
    @Transient
    private Double backLeaseCharge;
    @Transient
    private Double backRental;
    @Transient
    private Double contractBack;
    @Transient
    private Double itemAmount;
    @Transient
    private Double discountRental;
    @Transient
    private Double leaseSumAmount;
    @Transient
    private Double receiveLeaseCharge;
    @Transient
    private Double remainingMargin;
    @Transient
    private Double remainingExposure;
    @Transient
    private String deductFlag;
    @Transient
    private String tenantDealerFlag;
    @Transient
    private String graceTypeN;
    @Transient
    private String repayFlagN;

    @Transient
    private Double payAmount;
    @Transient
    private String currentOverdueStatus;
    @Transient
    private String historyOverdueStatus;

    @Transient
    private Double currentOverdueAmount;
    @Transient
    private Double remainingRent;
    @Transient
    private Double discountAmount;
    @Transient
    private Double intRateReply;
    @Transient
    private Double intRateFloatRate;
    @Transient
    private String prePaymentsStatus;
    @Transient
    private String lpCellPhone;
    @Transient
    private String graceMonth;
    @Transient
    private String changeTypeN;
    @Transient
    private String leaseEndDateN;
    @Transient
    private String contractStatusDesc;//合同状态描述
    /**
     * 质押标志
     */
    private String pledgeFlag;
    @Transient
    private String pledgeFlagN;

    @Transient
    private String internalBpN;

    @Transient
    private String bpName;//承租人名称

    @Transient
    private String businessTypeDesc;//业务类型描述

    @Transient
    private String documentTypeDesc;//单据类型描述

    @Transient
    private String divisionDesc;//产品线描述

    @Transient
    private String projectNumber;//项目编号

    @Transient
    private String projectNumberN;

    @Transient
    private String projectName;//项目名称

    @Transient
    private String params;//查询参数

    @Transient
    private String collectFlag;

    @Transient
    private Long bpId;//付款对象

    @Transient
    private Long transforBpId;

    @Transient
    private String bpBankAccountNum;//付款对象账户

    @Transient
    private Long bpBankAccountId;//付款对象账户ID
    @Transient
    private String bpBankAccountIdN;//付款对象账户ID

    @Transient
    private String bpBankName;//付款对象银行名称

    @Transient
    private String bpBankBranchName;//付款对象支行名称

    @Transient
    private String bpBankAccountName;//付款对象账户名称


    @Transient
    private String description;//付款头备注

    @Transient
    private Long cashflowId;//付款现金流ID

    @Transient
    private Double paymentAmount;//付款申请金额

    @Transient
    private Date paymentReqDate;//付款申请日期

    @Transient
    private Long paymentReqId;//付款申请ID

    @Transient
    private Long paymentReqLnId;//付款申请行ID

    @Transient
    private String paymentReqNumber;//付款申请编号

    @Transient
    private Double amount;//申请金额

    @Transient
    private String paymentReqStatusDesc;//付款申请状态

    @Transient
    private String returnAccountNum;//回款账户

    @Transient
    private String returnAccountName;//回款账户名称

    @Transient
    private String cfItemDesc;//现金流类型

    @Transient
    private Double unreceivedPrincipal;

    @Transient
    private Double unreceivedInterest;

    @Transient
    private String absFlag;

    @Transient
    private String approvalNumber;

    @Transient
    private String tenantName;
    @Transient
    private int overdueTimes;
    @Transient
    private int overdueDays;
    @Transient
    private Double overduePenalty;
    @Transient
    private Double leftRent;
    @Transient
    private int fineCount;
    @Transient
    private String fineReduceStatusN;
    @Transient
    private Double leftAmount;

    @Transient
    private Date writeOffDate;


    @Transient
    private Double deductAmount;
    @Transient
    private String salBpName;

    @Transient
    private String buyBpName;

    private String interStatus;

    private String interInfo;

    @Transient
    private String projectAssistantName;
    private Date inceptDate;
    private String inceptWflStatus;

    private Double preServiceCharge;
    private Double derateAmount;
    private Double preCleanTotalMoney;

    @Transient
    private String message;

    @Transient
    private String dateStr;

    @Transient
    private String dateStr2;
    @Transient
    private String term;
    @Transient
    private String sourceDocCategory;

    @Transient
    private String paymentReqStatus;
    @Transient
    private String cfItems;

    @Transient
    private String writeOffFlags;

    @Transient
    private Double amtFrom;

    @Transient
    private Double amtTo;
    private Double residualPrincipal;//提前还款剩余本金
    @Transient
    private Double residualPenalty;//提前还款剩余罚息
    @Transient
    private Boolean success;
    private Double residualInterest;
    @Transient
    private Long writeOffId;
    @Transient
    private Double cshWriteOffAmount;
    @Transient
    private Double taxTypeRate;
    @Transient
    private Long cfItem;
    @Transient
    private Date transactionDate;
    @Transient
    private Date dueDate;
    @Transient
    private String unitName;//部门名称
    @Transient
    private Double amtOne;//第一季度投放
    @Transient
    private Double amtTwo;//第二季度投放
    @Transient
    private Double amtThree;//第三季度投放
    @Transient
    private Double amtFour;//第四季度投放
    @Transient
    private Double amtFive;//第五季度投放

    private Long conPaymentAccountId;//租赁回款账户id
    @Transient
    private String backBankAccountName;
    @Transient
    private String conPaymentAccountNumber;
    @Transient
    private Long sourceDocLineId;

    @Transient
    private String sourceDocLineIdN;
    /*
    文本生成字段，文本类型，名称，代码
     */
    @Transient
    private String docDocumentType;
    @Transient
    private String templetCode;
    @Transient
    private String docDocumentName;
    @Transient
    private String deductFlagDesc;

    @Transient
    private String deductFlagN;

    @Transient
    private Date firstRentalPaymentDate;

    @Transient
    private Long paymentDay;
    //资金投放计划行ID
    private Long planLnId;
    @Transient
    private String planName;
    @Transient
    private String planNumber;

    @Transient
    private Double totalConDueAmount;
    @Transient
    private Double totalConInterest;
    @Transient
    private Date paymentCompletedDate;
    @Transient
    private Double sumAmountPaid;
    //投保人
    @Transient
    private String insuranceFeeMethod;

    @Transient
    private String whetherInsuranceN;
    @Transient
    private String whetherInsurance;
    @Transient
    private String insurancePeople;

    @Transient
    private String bizType;

    @Transient
    private String shareType;

    @Transient
    private String cfType;
    @Transient
    private String hostProjectManagerN;
    @Transient
    private String insureCategory;

    @Transient
    private String hostUnitName;

    @Transient
    private String queryInfo;
    @Transient
    private Date proposedLaunchDate;
    @Transient
    private Long fundingPlanId;

    @Transient
    private String fundingPlanNumber;

    private Double loanTotalAmount;
    @Transient
    private Double loanNetAmount;

    private String fineReduceStatus;

    private String taxStructure;

    private Long hostProjectManager;

    private Long hostUnitId;

    private Long assistProjectManager;

    private Long assistUnitId;

    private String inceptFlag;

    private String penaltyCalcMethod;

    private String leaseItemProperty;

    @Transient
    private String bpBankAccountBpName;

    @Transient
    private String loanInitialLease;

    @Transient
    private Double newBaseRate;

    @Transient
    private String paymentNumber;
    @Transient
    private String contractStatusN;
    @Transient
    private String currencyN;
    @Transient
    private Double financeAmountFrom;
    @Transient
    private Double financeAmountTo;
    @Transient
    private Double leaseChargeFrom;
    @Transient
    private Double leaseChargeTo;
    @Transient
    private Double depositFrom;
    @Transient
    private Double depositTo;

    @Transient
    private String businessTypeN;

    @Transient
    private String tenantIdN;

    @Transient
    private Date firstReleaseDate;

    @Transient
    private Double stampTax;

    @Transient
    private Double stampTaxFee;

    @Transient
    private String periodName;

    @Transient
    private Long taxSeq;

    private String stampDutyFlag;

    @Transient
    private Date leaseAccountDate;

    @Transient
    private Date leaseDateAdjust;

    private String finLoanInitialLease;

    @Transient
    private String tenantOrgCode;

    @Transient
    private String tenantCreditCode;

    @Transient
    private String customerNumber;

    @Transient
    private String tenantPartyN;

    @Transient
    private String tenantPlatformN;

    @Transient
    private String provinceN;

    @Transient
    private String tenantIndustry1;

    @Transient
    private String tenantIndustry2;

    @Transient
    private String tenantIndustry4;

    @Transient
    private String tenantBpFinancialType;

    @Transient
    private String tenantEnterpriseScale;

    @Transient
    private String listedCompanyN;

    @Transient
    private String commonBpName;

    @Transient
    private String commonOrgCode;

    @Transient
    private String commonCreditCode;

    @Transient
    private String commonCustomerNumber;

    @Transient
    private String commonPartyN;

    @Transient
    private String commonPlatformN;

    @Transient
    private String commonProvinceN;

    @Transient
    private String commonIndustry1;

    @Transient
    private String commonIndustry2;

    @Transient
    private String commonIndustry4;

    @Transient
    private String commonBpFinancialType;

    @Transient
    private String commonEnterpriseScale;

    @Transient
    private String commonListedCompanyN;

    @Transient
    private String guarantorBpName;

    @Transient
    private String guarantorOrgCode;

    @Transient
    private String guarantorCreditCode;

    @Transient
    private String guarantorCustomerNumber;

    @Transient
    private String guarantorPartyN;

    @Transient
    private String guarantorPlatformN;

    @Transient
    private String guarantorProvinceN;

    @Transient
    private String guarantorIndustry1;

    @Transient
    private String guarantorIndustry2;

    @Transient
    private String guarantorIndustry4;

    @Transient
    private String guarantorBpFinancialType;

    @Transient
    private String guarantorEnterpriseScale;

    @Transient
    private String guarantorListedCompanyN;

    @Transient
    private String groupBpName;

    @Transient
    private String groupIndustry1;

    @Transient
    private String groupIndustry2;

    @Transient
    private String groupIndustry4;

    @Transient
    private String groupBpFinancialType;

    @Transient
    private String groupEnterpriseScale;

    @Transient
    private Double leaseMonth;

    @Transient
    private Double remainingTerm;

    @Transient
    private Double balanceDeposit;

    @Transient
    private String assureMeans;

    @Transient
    private String floatingRate;

    @Transient
    private String inceptionN;

    @Transient
    private String marketingUnitName;

    @Transient
    private String assistProjectManagerN;


    @Transient
    private Double assetValueTotal;

    @Transient
    private Double pledgeAssetValueTotal;

    @Transient
    private Double netAssetValueTotal;

    @Transient
    private String mortgageName;

    @Transient
    private String mortgageCategories1;

    @Transient
    private String mortgageCategories2;

    @Transient
    private String pledgeName;

    @Transient
    private String pledgeCategories1;

    @Transient
    private String pledgeCategories2;

    @Transient
    private String leaseName;

    @Transient
    private String assetTypesN;

    @Transient
    private String assetTypesSubN;

    @Transient
    private String nineClasses;

    @Transient
    private String fiveCategoriesN;

    @Transient
    private String payMethond;

    @Transient
    private String usedCashFlow;

    @Transient
    private String manageRequirements;

    @Transient
    private String gropCode;

    @Transient
    private String detailAssureMeans;

    @Transient
    private String mortgageCurrentValue;

    @Transient
    private String pledgeCurrentValue;

    @Transient
    private String leaseCurrentValue;

    @Transient
    private String currentDuration;

    @Transient
    private String assessmentClass;

    @Transient
    private String insurance;

    @Transient
    private String examinationDuration;

    @Transient
    private String bpCode;

    @Transient
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dueDateFrom;   // 到期日从
    @Transient
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dueDateTo;   // 到期日到

    @Transient
    private String bpClass;

    private Date lprLinkDate;

    private Date nextAdjustmentDate;

    @Transient
    private String offBalanceSheetFlagN;

    @Transient
    private String assistUnitName ;

    @Transient
    private Double offBalanceSheetAmount ;

    @Transient
    private Double originalObsAmount ;
    @Transient
    private Date pointInTime ;

    private Long companySpv ;

    @Transient
    private Double residualDeposit ;

    @Transient
    private String financialLeaseStatusN;

    @Transient
    private String prjContractNumber;

    @Transient
    private String vcContractNumber;

    @Transient
    private String vcContractName;

    @Transient
    private Date monthDay;

    @Transient
    private Date yearDay;

    private String easCode;

    private String easBpCode;

    private String easBpName;
    @Transient
    private  String virtualContractName;
    @Transient
    private  String virtualContractNumber;
    @Transient
    private String companySpvN;
    @Transient
    private String contractCurrency;
    @Transient
    private Double totalDueAmount;
    @Transient
    private Double totalReceivedAmount;
    @Transient
    private Double overdueAmount;
    @Transient
    private Double penaltyAmount;
    @Transient
    private Double receivedPenaltyAmount;
    @Transient
    private String employeeIdN;
    @Transient
    private String unitIdN;

    @Transient
    private Long refProjectId;

    @Transient
    private String remindCategory;

    @Transient
    private Long userId;

    @Transient
    private Date changeDate;

    @Transient
    private Date actualPayDate;
    @Transient
    private Double actualHdPayAmount;
    @Transient
    private String leaseOrganizationN;
    @Transient
    private String lessorName;

    @Transient
    private String groupCustomers;
    @Transient
    private String isLowRisk;

    @Transient
    private Double receivedReceiptAmount;
    @Transient
    private Double paiedAmount;

    @Transient
    private Double unpaiedAmount;

    @Transient
    private Date actualHdPayDate;

    @Transient
    private String payTypes;

    @Transient
    private String groupCustomersN;

    @Transient
    private String yearTimes;


    @Transient
    private Date expireDate;
    @Transient
    private Double signAmountTotal;
    @Transient
    private Double prjFinanceAmount;
    @Transient
    private String creditFlag;
    @Transient
    private String creditFlagN;

    @Transient
    private String economicInduClassifyN;


    @Transient
    private String approvalTerm;
    @Transient
    private String approvalNote;
    @Transient
    private String chargeMethod;
    @Transient
    private String guarMethod;
    @Transient
    private String depositMethod;
    @Transient
    private String foundingMethod;
    @Transient
    private String repaymentMethod;

    @Transient
    private String conditionTypeN;
    @Transient
    private String conditionType;
    @Transient
    private String approvalTypeN;
    @Transient
    private String approvalType;
    @Transient
    private String conditionContent;
    @Transient
    private Date approvalDate;



    @Transient
    private Double sumPayAmount;
    @Transient
    private String receiptType;
    @Transient
    private String receiptTypeN;
    @Transient
    private Double taxAmount;
    @Transient
    private Double unreceivedReceiptAmount;

    @Transient
    private String receiptRequest;
    @Transient
    private String approvalNoteNewa;
    @Transient
    private String approvalNoteNewb;
    @Transient
    private String approvalNoteNewc;
    @Transient
    private Double surplusPrincipal;
    @Transient
    private Double leaseItemAmountOrg;
    @Transient
    private Date signDateFrom;
    @Transient
    private Date signDateTo;
    @Transient
    private String inceptFlagN;
    @Transient
    private String loanInitialLeaseN;
    @Transient
    private String contractNumberP;
    @Transient
    private String contractNameP;

    @Transient
    private String year;

    private String industryType;
    @Transient
    private String industryTypeN;
    @Transient
    private String repaymentStatus;
    @Transient
    private String conStatus;
    @Transient
    private String productConclusion;
    @Transient
    private String registerCertNum;

    private String city;
    @Transient
    private String cityN;
    @Transient
    private String leaseItemIdN;
    @Transient
    private Double originalAssetValue;
    @Transient
    private Double price;
    @Transient
    private Double remainingPrincipal;
    @Transient
    private String itemInfo;
    @Transient
    private String mortgagePledge;
    @Transient
    private String guarantee;
    @Transient
    private String cshBankAccountName;


    /*融资租赁主要业务分地区统计表参数*/
    @Transient
    private String area;

    @Transient
    private String areaN;

    @Transient
    private Double sublease;

    @Transient
    private Double lease;

    @Transient
    private Double leaseBack;

    @Transient
    private Double generalOperatingLease;

    @Transient
    private Double genericDevice;

    @Transient
    private Double specializedDevice;

    @Transient
    private Double transportationDevice;

    @Transient
    private Double electronicsDevice;

    @Transient
    private Double electricalDevice;

    @Transient
    private Double landHousesStructures;

    @Transient
    private Double otherLeasehold;
    @Transient
    private String title;
    @Transient
    private Double financialLeasing;

    @Transient
    private Double zjLoanTotalAmount;
    @Transient
    private Double zrLoanTotalAmount;
    @Transient
    private Double qtLoanTotalAmount;
    @Transient
    private Double writeOffDueAmount;
    @Transient
    private Double zjWriteOffDueAmount;
    @Transient
    private Double zcWriteOffDueAmount;
    @Transient
    private Double fhWriteOffDueAmount;
    @Transient
    private Double hxWriteOffDueAmount;
    @Transient
    private Double qtWriteOffDueAmount;

    @Transient
    private String leaseItemName;
    @Transient
    private Double historyPrincipal;
    @Transient
    private Double withdrawalAmount;
    @Transient
    private Double principal;
    @Transient
    private Double electrical;


    /*融资租赁公司主要业务融资投向统计表参数*/
    @Transient
    private String economicComponent;

    @Transient
    private String economicComponentN;

    @Transient
    private Double financingTotal;

    @Transient
    private Double largeScale;

    @Transient
    private Double medium;

    @Transient
    private Double smallSized;

    @Transient
    private Double smallOnly;

    @Transient
    private Double miniature;

    @Transient
    private Double miniatureOnly;
    @Transient
    private Double resultPrincipal;
    @Transient
    private Double riskWithdrawalAmount;
    @Transient
    private String isLowRiskN;
    /*融资租赁公司主要业务综合融资成本统计表 参数*/

    @Transient
    private String itemType;//租赁物类别

    @Transient
    private String itemTypeN;

    @Transient
    private Double outstandingPrincipal;//剩余本金

    @Transient
    private Double receivedInterest; //利息总额

    @Transient
    private Double receivedPrincipal;

    /*地方金融集中度统计表*/
    @Transient
    private Double credit; //信用风险敞口

    /*地方金融组织最大五家关联方关联交易统计表*/
    @Transient
    private Double numContractAmount; // 所在集团其他融资

    @Transient
    private Double numDeposit; //所在集团合格质物

    @Transient
    private Double numCredit; //所在集团信用风险敞口

    /*融资收益分配表参数*/
    @Transient
    private Double times; //期数

    @Transient
    private Date endDate; //起租日

    @Transient
    private Double refN01;//现金流

    @Transient
    private Double refN02; //租金

    @Transient
    private Double refN03;//确认的融资收入

    @Transient
    private Double refN04;//租赁投资净额减少额

    @Transient
    private Double refN05;//租赁投资净额余额

    @Transient
    private Double refN06;

    @Transient
    private Double refN07;//确认的融资收入(不含税)

    @Transient
    private Double refN08;//确认的销项税额

    @Transient
    private Double refN09;//月度实际利率

    @Transient
    private Double yearDays;

    @Transient
    private Date startDate;

    @Transient
    private Double days;

    @Transient
    private Date finIncomeDate;

    private String depositDeductionChangedFlag;

    @Transient
    private Double yearReceivedPrincipal;
    @Transient
    private Double yearReceivedInterest;
    @Transient
    private Double yearTotalReceivedAmount;
    @Transient
    private String bpIdVenderN;
    private Long bpIdVender;
    private Long factoryId;  // 主机厂
    @Transient
    private String factoryIdN;

    private Long virtualAccountId;
    private String virtualAccountNum;
    private String virtualAccount;
    private Long downloadVersion;
    private Long manufacturerId;
    private String sapStatus;

    private String substituteReceiptFlag;

    @Transient
    private String quotationNumber;

    /**
     * 付款对象
     */
    private Long paymentBpId;
    @Transient
    private String paymentBpIdN;
    /**
     * 付款对象类型
     */
    private String paymentBpType;
    @Transient
    private String paymentBpTypeN;
    /**
     * 退回日期
     */
    @Transient
    private Date returnDate;

    /**
     * 退回原因
     */
    @Transient
    private String returnReason;

    /**
     * 退回说明
     */
    @Transient
    private String returnDescription;

    @Transient
    private Long[] contractIds;

    private Long ccrStartTimes;
    private Long ccrOutstandingTimes;
    private Double ccrFee;

    /**
     * 是否自动抵扣
     */
    @Transient
    private String autoDeductFlag;
    @Transient
    private String autoDeductFlagN;

    private String depositDeductMethod;
    @Transient
    private String depositDeductMethodN;
    @Transient
    private String mobile;
    @Transient
    private String rentPlanNoticeFlag;
    @Transient
    private String rentPlanNoticeFlagN;
    @Transient
    private String venderSignType;
    @Transient
    private String venderSignTypeN;
    @Transient
    private String manufacturerSignType;
    @Transient
    private String manufacturerSignTypeN;
    @Transient
    private String dealerSignType;
    @Transient
    private String dealerSignTypeN;

    private String secondHandFlag;
    @Transient
    private String secondHandFlagN;
    @Transient
    private String secondHandFlagPre;
    @Transient
    private String secondHandFlagPreN;

    private String legalContractNumber;

    private Long projectAssistant2;

    private Double proposerEmployeeRatio;

    private Double projectAssistantRatio;

    private Double projectAssistant2Ratio;

    private Long riskHost;
    private Double riskHostRatio;
    private Long riskAssistantFirst;
    private Long riskAssistantSecond;
    private Double riskAssistantFirstRatio;
    private Double riskAssistantSecondRatio;
    @Transient
    private String projectAssistant2Name;
    @Transient
    private String projectAssistant2N;
    @Transient
    private String riskHostN;
    @Transient
    private String riskAssistantFirstN;
    @Transient
    private String riskAssistantSecondN;

    private Long legalHost;
    private Double legalHostRatio;
    private Long legalAssistantFirst;
    private Long legalAssistantSecond;
    private Double legalAssistantFirstRatio;
    private Double legalAssistantSecondRatio;
    @Transient
    private String legalHostN;
    @Transient
    private String legalAssistantFirstN;
    @Transient
    private String legalAssistantSecondN;


    private String mortgageStatus;

    @Transient
    private String mortgageStatusN;


    private Date mortgageApprovedDate;

    @Transient
    private Long processInstanceId;

    @Transient
    private String documentName;

    @Transient
    private Date uploadDate;

    @Transient
    private String idCardNo;

    @Transient
    private String phone;

    @Transient
    private String frameNumber;

    @Transient
    private String brandC;

    @Transient
    private String modelC;

    @Transient
    private String colorC;

    @Transient
    private Double listPrice;

    @Transient
    private Double contractAttachmentId;

    @Transient
    private Double totalRentalAmount;

    @Transient
    private Double remainRentalAmount;

    @Transient
    private Double remainPrincipal;

    @Transient
    private Double penalty;

    @Transient
    private String currentOverdueStatusN;

    @Transient
    private String leaseItemTypeN;

    @Transient
    private String terminateType;

    @Transient
    private String terminateTypeN;


    private String zdwRegisterStatus;

    @Transient
    private String zdwRegisterStatusN;

    private String pledgePerson;

    private String pledgeLocation;

    private String pledgeInstitution;

    private Date pledgeDate;

    private String pledgeDescription;

    @Transient
    private Long writeOffStatusC;
    @Transient
    private String inceptTypeN;
    @Transient
    private String inceptType;
    @Transient
    private String paymentApprovedStatus;
    @Transient
    private String paymentApprovedStatusN;
    @Transient
    private String driverAndApplicant;
    private Date loanApprovedDate;  //放款申请通过时间
    @Transient
    private String virContractNumber; //保理合同编号
    @Transient
    private Double loanLeaseItemAmount; //放款金额

    private String factoringType; //保理类型
    @Transient
    private String factoringTypeN;
    private String factoringRecourse; //追索类型
    @Transient
    private String factoringRecourseN;
    private String factoringOpen; //明暗类型
    @Transient
    private String factoringOpenN;
    private String industry; //业务板块
    private String factoringCategory; //保理类别
    @Transient
    private String factoringCategoryN;
    private String purposeOfFunds;

}
