package com.hand.hls.fct.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ExtensionAttribute(disable = true)
@Table(name = "hls_credit_line")
public class HlsCusHlsCreditLine extends BaseDTO {
    public static final String FIELD_DELAY_FROM = "delayFrom";
    public static final String FIELD_DELAY_TO = "delayTo";
    public static final String FIELD_FIRST_WITHDRAW_DATE = "firstWithdrawDate";
    public static final String FIELD_COMPETENT_DEPT = "competentDept";
    public static final String FIELD_FINANCE_TYPE = "financeType";
    @Id
    @GeneratedValue
    private Long creditLineId;
    private String creditLineNumber;
    private String creditLineName;
    private Long bpId;
    @Transient
    private String bpIdN;
    private Long companyId;
    private String documentType;
    @Transient
    private String documentTypeN;
    private String documentCategory;
    private String businessType;
    private Long proposerUserId;
    private Long proposerEmployeeAssignId;
    private Long proposerEmployeeId;
    private String sourceDocumentCategory;
    private Long sourceDocumentId;
    private String creditLineStatus;
    private String currencyCode;
    @Transient
    private String currencyCodeN;
    private Double creditLineAmt;
    private Double creditExposureAmt;
    private Long creditLineQty;
    private Long creditExposureQty;
    private Date validFrom;
    private Date validTo;
    private String description;
    private Long projectAssistant;
    @Transient
    private String projectAssistantN;
    @Transient
    private String projectAssistantName;
    @Transient
    private String creditLineStatusValue;
    @Transient
    private String creditLineCount;
    @Transient
    private Long creditLineCountPercent;
    @Transient
    private String creditObjName;
    @Transient
    private String creditObjectName;
    @Transient
    private Date beginDate;
    @Transient
    private Date endDate;
    @Transient
    private String limitFrom;
    @Transient
    private String limitTo;
    @Transient
    private String date_startup;
    @Transient
    private String date_out;
    @Transient
    private String limit_from;
    @Transient
    private String limit_to;
    @Transient
    private String credit_object_name;
    @Transient
    private String clientName;
    @Transient
    private String clientCode;
    @Transient
    private Long creditUsedAmt;
    @Transient
    private String bpType;
    @Transient
    private Long changeVersion;
    @Transient
    private Date changeDate;
    @Transient
    private String contractNumber;
    @Transient
    private String contractName;
    @Transient
    private HlsCusHlsCreditLine hlsCreditLine;
    @Transient
    private Long creditLineHId;
    @Transient
    private String projectManager;
    @Transient
    private String unitName;
    @Transient
    private String companyName;
    @Transient
    private String bpCode;
    @Transient
    private String bpName;
    @Transient
    private String currencyName;
    @Transient
    private String fileName;
    @Transient
    private String uploadDate;
    @Transient
    private String managerName;
    @Transient
    private String documentDesc;
    @Transient
    private String bpDescription;
    @Transient
    private String creditLineStatusDesc;
    @Transient
    private String fctCreditLineStatus;
    private Date delayFrom; //延期从
    private Date delayTo; //延期到
    private Date firstWithdrawDate; //首次提款日
    @Length(max = 100)
    private String competentDept;
    @Length(max = 100)
    private String financeType;

    @Transient
    private Long finStatementHdId;

    /**
     * 提款余额
     */
    private Double withdrawBalance;

    private String cancelFlag;

    private Long sourceCreditLineId;

    private Long term;

    @Transient
    private Long creditContractId;

    @Transient
    private String sourceCreditFlag;

    @Transient
    private Double creditPreemptionAmt;

    @Transient
    private Double creditUsedAmount;
    @Transient
    private Double preemptionAmt;

    private Long chanceId;//授信立项ID

    private String creditProjectDesc;//项目情况概述

    private Long projectAssistantAssignsId;//协办项目经理ID

    private Long unitId;//部门ID

    @Transient
    private String creditLineNameN;

    @Transient
    private String reviewType;

    public String getReviewType() {
        return reviewType;
    }

    public void setReviewType(String reviewType) {
        this.reviewType = reviewType;
    }

}
