package com.hand.hls.fct.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "hls_credit_line_chance_mp")
public class HlsCreditLineChanceMp extends BaseDTO {

     public static final String FIELD_CHANCE_MP_ID = "chanceMpId";
     public static final String FIELD_CHANCE_ID = "chanceId";
     public static final String FIELD_LEASE_ITEM_ID = "leaseItemId";
     public static final String FIELD_PLEDGE_NAME = "pledgeName";
     public static final String FIELD_LEASE_ITEM_TYPE = "leaseItemType";
     public static final String FIELD_PATTERN = "pattern";
     public static final String FIELD_MORTGAGOR = "mortgagor";
     public static final String FIELD_PLEDGE_STATE = "pledgeState";
     public static final String FIELD_ORIGINAL_ASSET_VALUE_TOTAL = "originalAssetValueTotal";
     public static final String FIELD_ASSET_VALUE_TOTAL = "assetValueTotal";


     @Id
     @GeneratedValue
     private Long chanceMpId; //抵质押物主键

     private Long chanceId; //立项ID

     private Long leaseItemId; //租赁物ID

     @Length(max = 100)
     private String pledgeName; //抵(质)押物名称

     @Length(max = 50)
     private String leaseItemType; //抵质押属性

     @Length(max = 50)
     private String pattern; //抵质押分类

     private Long mortgagor; //抵押人/出质人

     @Length(max = 50)
     private String pledgeState; //抵质押状态

     private Long originalAssetValueTotal; //购置价/资产价值

     private Long assetValueTotal; //市场价值/评估价值
    @Transient
    private String leaseItemIdN;
    @Transient
    private String leaseItemTypeN;
    @Transient
    private String patternN;

    @Transient
    private String mortgagorN;
    @Transient
    private String pledgeStateN;

    private String leaseItemCode;

    public String getLeaseItemCode() {
        return leaseItemCode;
    }

    public void setLeaseItemCode(String leaseItemCode) {
        this.leaseItemCode = leaseItemCode;
    }

    public String getLeaseItemIdN() {
        return leaseItemIdN;
    }

    public void setLeaseItemIdN(String leaseItemIdN) {
        this.leaseItemIdN = leaseItemIdN;
    }

    public String getLeaseItemTypeN() {
        return leaseItemTypeN;
    }

    public void setLeaseItemTypeN(String leaseItemTypeN) {
        this.leaseItemTypeN = leaseItemTypeN;
    }

    public String getPatternN() {
        return patternN;
    }

    public void setPatternN(String patternN) {
        this.patternN = patternN;
    }

    public String getMortgagorN() {
        return mortgagorN;
    }

    public void setMortgagorN(String mortgagorN) {
        this.mortgagorN = mortgagorN;
    }

    public String getPledgeStateN() {
        return pledgeStateN;
    }

    public void setPledgeStateN(String pledgeStateN) {
        this.pledgeStateN = pledgeStateN;
    }

    public void setChanceMpId(Long chanceMpId){
         this.chanceMpId = chanceMpId;
     }

     public Long getChanceMpId(){
         return chanceMpId;
     }

     public void setChanceId(Long chanceId){
         this.chanceId = chanceId;
     }

     public Long getChanceId(){
         return chanceId;
     }

     public void setLeaseItemId(Long leaseItemId){
         this.leaseItemId = leaseItemId;
     }

     public Long getLeaseItemId(){
         return leaseItemId;
     }

     public void setPledgeName(String pledgeName){
         this.pledgeName = pledgeName;
     }

     public String getPledgeName(){
         return pledgeName;
     }

     public void setLeaseItemType(String leaseItemType){
         this.leaseItemType = leaseItemType;
     }

     public String getLeaseItemType(){
         return leaseItemType;
     }

     public void setPattern(String pattern){
         this.pattern = pattern;
     }

     public String getPattern(){
         return pattern;
     }

     public void setMortgagor(Long mortgagor){
         this.mortgagor = mortgagor;
     }

     public Long getMortgagor(){
         return mortgagor;
     }

     public void setPledgeState(String pledgeState){
         this.pledgeState = pledgeState;
     }

     public String getPledgeState(){
         return pledgeState;
     }

     public void setOriginalAssetValueTotal(Long originalAssetValueTotal){
         this.originalAssetValueTotal = originalAssetValueTotal;
     }

     public Long getOriginalAssetValueTotal(){
         return originalAssetValueTotal;
     }

     public void setAssetValueTotal(Long assetValueTotal){
         this.assetValueTotal = assetValueTotal;
     }

     public Long getAssetValueTotal(){
         return assetValueTotal;
     }

     }
