package com.hand.hls.fct.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Data;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HLS_CREDIT_LINE_CHANCE_CONDITION")
@Data
public class HlsCreditLineChanceCondition extends BaseDTO {

     public static final String FIELD_CONDITION_ID = "conditionId";
     public static final String FIELD_CHANCE_ID = "chanceId";
     public static final String FIELD_CONTENT = "content";


     @Id
     @GeneratedValue
     private Long conditionId;

     private Long chanceId;

     @Length(max = 1024)
     private String content;

     private String stage;




     }
