package com.hand.hls.fct.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ExtensionAttribute(disable = true)
@Table(name = "fct_project")
public class HlsCusFctProject extends BaseDTO {

    public static final String HLS_CUS_FCT_PROJECT = "hlsCusFctProject";
    public static final String QUOTATION_ID = "quotationId";
    @Id
    @GeneratedValue
    private Long projectId;
    private Long companyId;
    @Length(
            max = 100
    )
    private String documentType;
    @Length(
            max = 100
    )
    private String documentCategory;
    @Length(
            max = 100
    )
    private String businessType;
    @Length(
            max = 255
    )
    private String projectNumber;
    @Length(
            max = 2000
    )
    private String projectName;
    @Length(
            max = 100
    )
    private String projectStatus;
    private Long creditLineId;
    private Long creditComprehensiveId;
    private Long employeeAssignId;
    private Long employeeId;
    private Long unitId;
    @Length(
            max = 2000
    )
    private String description;
    @Length(
            max = 100
    )
    private String currency;
    @Length(
            max = 1000
    )
    private String authorityRuleString;
    private String contractStatus;
    private Double penaltyRate;
    private String creditStatus;
    private Long projectAssistant;
    private Double principalPenaltyRate;
    @Transient
    private Long managerId;
    @Transient
    private String prjStatusValue;
    @Transient
    private String prjCount;
    @Transient
    private Long prjCountPercent;
    @Transient
    private String prjNameCode;
    @Transient
    private String bpNameCode;
    @Transient
    private String bpName;
    @Transient
    private String bpCode;
    @Transient
    private String userName;
    @Transient
    private String businessDesc;
    @Transient
    private String documentDesc;
    @Transient
    private String busTypeStatusList;
    @Transient
    private String factorTypeStatusList;
    @Transient
    private String projectManager;
    @Transient
    private String projectAssistantName;
    @Transient
    private String basicDealsNumber;
    @Transient
    private Long basicTrxId;
    @Transient
    private String unitName;
    @Transient
    private Double creditLineAmt;
    @Transient
    private Double creditExposureAmt;
    @Transient
    private String managerName;
    @Transient
    private Double creditAvailableAmt;
    @Transient
    private String isOccupied;
    @Transient
    private String projectStatusDesc;
    @Transient
    private String creditLineName;
    @Transient
    private String limitDesc;
    @Transient
    private String documentTypeDesc;
    @Transient
    private String businessTypeDesc;
    @Transient
    private String documentCategoryDesc;
    @Transient
    private String creditTypeDesc;
    @Transient
    private String employeeName;
    @Transient
    private String creditStatusDesc;
    @Transient
    private String companyName;
    @Transient
    private Date validFrom;
    @Transient
    private Date validTo;
    @Transient
    private String queryCondition;
    @Transient
    private String creditLineStatus;
    @Transient
    private Long quotationId;
    @Transient
    private Long finStatementId;
    @Transient
    private Long signApprovalId;
    @Transient
    private String prjAttId;
    @Transient
    private Double creditUsedAmount;

    private Long chanceId; //保理立项ID

    private String dataType;

    private String creditCondition;//授信条件

    private String paymentCondition;//放款条件

    private String manageCondition;//管理条件

    private String fiveClassificationResult;

    private String isPoolFactor;//是否持保理

    private Double hostRatio;//主办占比

    private Double assistantRatio;//协办占比
    /**
     * 合同制作状态
     */
    private String createContractStatus;

    /**
     * 签约描述
     */
    private String signDescription;
    /**
     * 签约日期
     */
    private Date signDate;

    /**
     * 保证合同：年-流水号;
     */
    private String factoringNumber;

    @Transient
    private String message;
    @Transient
    private Boolean success;
    @Transient
    private String projectTrxStatus;
    @Transient
    private Long paymentReqId;
    @Transient
    private Double paymentReqAmount;
    @Transient
    private Long quotationIdNew;
    @Transient
    private String contractChangeType;
    @Transient
    private Double trxArAmount;
    @Transient
    private Double trxAmountFrom;
    @Transient
    private Double trxAmountTo;
    @Transient
    private String meetingVoteResult;
    @Transient
    private String changeHistory;
    @Transient
    private String cancelPersonName;
    @Transient
    private String postLoanInsFrequencyDesc;
    @Transient
    private String motherSource;
    @Transient
    private String otherSource;
    @Transient
    private String legalForm;
    @Transient
    private String year;
    @Transient
    private Long days;
    @Transient
    private Double compensationDiscount;
    @Transient
    private String rateValidTo;
    @Transient
    private String applyPayDate;
    @Transient
    private Double amountPaid;
    @Transient
    private Double amountRest;
    @Transient
    private Long seqNum;


    public String getTouchCreatedDate() {
        return touchCreatedDate;
    }

    public void setTouchCreatedDate(String touchCreatedDate) {
        this.touchCreatedDate = touchCreatedDate;
    }

    @Transient
    private String touchCreatedDate;
    private Long creditBpId;
    private String contractNumber;

    private String contractName;

    private String approvalNumber;

    private Double approvalAmount;//批复金额
    //项目中合同已用额度
    @Transient
    private Double usedAmt;


    @Length(max = 100)
    private String fundRestreamMethod; //回款方式

    private String documentStyle; //单据类型

    private Double creditAmount; //授信总额度

    private String creditPlan;

    private Double creditExposureAmount;//已用额度

    private String creditType; //额度类型


    public String getTouchContractStatus() {
        return touchContractStatus;
    }

    public void setTouchContractStatus(String touchContractStatus) {
        this.touchContractStatus = touchContractStatus;
    }

    @Transient
    private String touchContractStatus;

    private Long projectAssistantAssignsId;//协办项目经理员工分配ID

    @Length(max = 100)
    private String postLoanInsFrequency; //贷后检查频率

    @Length(max = 100)
    private String fctLoanAccountId; //保理商放款账户ID

    @Length(max = 100)
    private String fctPaymentAccountId; //保理商回款账户ID

    @Length(max = 2000)
    private String prjAdvDevelopmentPro; //项目优势、风险及发展前景

    @Length(max = 2000)
    private String appUsageFlowDirection; //申请授信用途及流向

    @Length(max = 4000)
    private String repSourceFutureCfAnalysis; //还款来源及未来现金流分析（资金用途）

    @Length(max = 2000)
    private String otherInformation; //其他重要信息

    private Double repayGuaranteeAmount; //还款保证额度的金额

    private String repayGuaranteeType; //还款保证额度的届满日

    @Transient
    private String repayGuaranteeTypeDesc; //还款保证额度的届满日

    private Date repayGuaranteeDate; //还款保证额度的届满日

    private Date trxAmountDate;

    private String latestUseDateExist;

    private Date latestUseDate;

    private String dataClass;

    private Long refProjectId;

    private Long changeReqId;

    private Date buyBackDate;

    private Double buyBackRate;

    private Double addDownIntRate;

    private Date cancelDate;//撤销日期

    private String cancelReason;//撤销原因

    private Long cancelPerson;//合同撤销申请人

    private String cancelStatus;//合同撤销申请状态

    private String accountStatus;//应收账款变更审批状态

    private Date accountUpdateDate;//应收账款最新更新时间

    private String accountUpdateReason;//应收账款更新重要情况说明

    private String meetingStatus;

    private Long guarantorSum; //保证流水号

    private Long pledgorSum; //质押流水号

    private Long mortgagorSum; //抵押流水号

    @Transient
    private String createContractStatusDesc;

    @Transient
    private String contractStatusDesc;

    @Transient
    private String currencyName;

    @Transient
    private String fundRestreamMethodDesc;

    @Transient
    private String name;

    @Transient
    private Double financeAmount;

    @Transient
    private Long positionId;

    @Transient
    private String fctLoanAccount; //保理商放款账户

    @Transient
    private String fctLoanAccountNumber; //保理商放款账号

    @Transient
    private String fctPaymentAccount; //保理商回款账户

    @Transient
    private String fctPaymentAccountNumber; //保理商回款账号

    @Transient
    private String changeDescription;
    @Transient
    private Long changeReqUserId;
    @Transient
    private Date changeReqDate;
    @Transient
    private Long projectSumCount;
    @Transient
    private Long currentMonthAppend;
    @Transient
    private Long projectIdNew;
    @Transient
    private Long projectIdOld;
    @Transient
    private String params;//查询参数
    @Transient
    private Long contractId;
    @Transient
    private Double creditWriteOffAmt;
    @Transient
    private Long bpId;

    @Transient
    private String documentTypeArray;
    @Transient
    private Long yearFrom;
    @Transient
    private Long yearTo;//年份到
    @Transient
    private String dateFrom;//投放时间从
    @Transient
    private String dateTo;
    @Transient
    private String dateValidFrom;//到期日从
    @Transient
    private String dateValidTo;
    @Transient
    private String amountBetween;
    @Transient
    private Double amountFrom;
    @Transient
    private Double amountTo;
    /**
     * 项目额度
     */
    @Transient
    private Double projectAmount;

    @Transient
    private String creditValidFlag;
    @Transient
    private String wflFlag;
    @Transient
    private String wflFlagP;

    @Transient
    private String documentStyleDesc;

    @Transient
    private Long changeCount;

    @Transient
    private Long projectRefCount;

    @Transient
    private String proposerEmployeeName;
    @Transient
    private String projectAssistantNameN;

    @Transient
    private String proposerEmployeePart;


}
