package com.hand.hls.docx4J;

public interface Docx4jConstants {
    String UNDERLINE_TYPE_SINGLE = "SINGLE";
    String UNDERLINE_TYPE_DOUBLE = "DOUBLE";
    String FONT_WINGDINGS = "Wingdings 2";
    String TAG_R = "R";

    String BOOKMARK_TYPE_TABLE = "TABLE";
    String BOOKMARK_TYPE_FORMTABLE = "FORM_TABLE";
    String BOOKMARK_TYPE_TABLE_ROW_REPEAT = "TABLE_ROW_REPEAT";
    String BOOKMARK_TYPE_DYNAMICTABLE = "DYNAMIC_TABLE";
    String BOOKMARK_TYPE_TEXT = "TEXT";
    String BOOKMARK_TYPE_TEXTAREA = "TEXT_AREA";
    String BOOKMARK_TYPE_WATERMARK = "WATERMARK";

}
