package com.hand.hls.pam.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "hls_lease_build_deliver_info")
public class HlsLeaseBuildDeliverInfo extends BaseDTO {

     public static final String FIELD_BUILD_DELIVER_INFO_ID = "buildDeliverInfoId";
     public static final String FIELD_STATISTICAL_TIME = "statisticalTime";
     public static final String FIELD_STATISTICAL_WAY = "statisticalWay";
     public static final String FIELD_LEASE_ITEM_ID = "leaseItemId";
     public static final String FIELD_STATISTICAL_MAN = "statisticalMan";
     public static final String FIELD_COMPLETION_SCHEDUIE = "completionScheduie";
     public static final String FIELD_LEASE_ACCEPTANCE = "leaseAcceptance";
     public static final String FIELD_YDELIVERY_STATUS = "ydeliveryStatus";
     public static final String FIELD_RECEIVING_STATUS = "receivingStatus";
     public static final String FIELD_DOCUMENT_NUM = "documentNum";
     public static final String FIELD_DECRIPTION = "decription";


     @Id
     @GeneratedValue
     private Long buildDeliverInfoId; //主键ID

     private Date statisticalTime; //统计时间

     private Long statisticalWay; //统计方式

     private Long leaseItemId; //租赁物id


     private Long employeeId; //统计人员

     @Length(max = 200)
     private String completionScheduie; //完工进度

     @Length(max = 200)
     private String leaseAcceptance; //租赁物验收

     @Length(max = 200)
     private String ydeliveryStatus; //发货状态

     @Length(max = 200)
     private String receivingStatus; //收货状态

     @Length(max = 200)
     private String documentNum; //物流单据编号

     @Length(max = 200)
     private String decription; //物流说明
     @Transient
     private String employeeIdN;

     public void setBuildDeliverInfoId(Long buildDeliverInfoId){
         this.buildDeliverInfoId = buildDeliverInfoId;
     }

     public Long getBuildDeliverInfoId(){
         return buildDeliverInfoId;
     }

     public void setStatisticalTime(Date statisticalTime){
         this.statisticalTime = statisticalTime;
     }

     public Date getStatisticalTime(){
         return statisticalTime;
     }

     public void setStatisticalWay(Long statisticalWay){
         this.statisticalWay = statisticalWay;
     }

     public Long getStatisticalWay(){
         return statisticalWay;
     }

     public void setLeaseItemId(Long leaseItemId){
         this.leaseItemId = leaseItemId;
     }

     public Long getLeaseItemId(){
         return leaseItemId;
     }

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public String getEmployeeIdN() {
        return employeeIdN;
    }

    public void setEmployeeIdN(String employeeIdN) {
        this.employeeIdN = employeeIdN;
    }

    public void setCompletionScheduie(String completionScheduie){
         this.completionScheduie = completionScheduie;
     }

     public String getCompletionScheduie(){
         return completionScheduie;
     }

     public void setLeaseAcceptance(String leaseAcceptance){
         this.leaseAcceptance = leaseAcceptance;
     }

     public String getLeaseAcceptance(){
         return leaseAcceptance;
     }

     public void setYdeliveryStatus(String ydeliveryStatus){
         this.ydeliveryStatus = ydeliveryStatus;
     }

     public String getYdeliveryStatus(){
         return ydeliveryStatus;
     }

     public void setReceivingStatus(String receivingStatus){
         this.receivingStatus = receivingStatus;
     }

     public String getReceivingStatus(){
         return receivingStatus;
     }

     public void setDocumentNum(String documentNum){
         this.documentNum = documentNum;
     }

     public String getDocumentNum(){
         return documentNum;
     }

     public void setDecription(String decription){
         this.decription = decription;
     }

     public String getDecription(){
         return decription;
     }

     }
