package com.hand.hls.pam.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HLS_LEASE_ITEM_DETAIL")
@Getter
@Setter
public class HlsLeaseItemDetail extends BaseDTO {

     public static final String FIELD_LEASE_ITEM_DETAIL_ID = "leaseItemDetailId";
     public static final String FIELD_LEASE_ITEM_ID = "leaseItemId";
     public static final String FIELD_LEASE_FULL_NAME = "leaseFullName";
     public static final String FIELD_PURCHASE_CONTRACT_NUMBER = "purchaseContractNumber";
     public static final String FIELD_DETAIL_TYPE = "detailType";
     public static final String FIELD_QUANTITY = "quantity";
     public static final String FIELD_CERTIFICATE_SERIAL_NUMBER = "certificateSerialNumber";
     public static final String FIELD_VENDER_NAME = "venderName";
     public static final String FIELD_PURCHASE_PRICE = "purchasePrice";
     public static final String FIELD_RECORDED_TIME = "recordedTime";
     public static final String FIELD_CREDITED_AMOUNT = "creditedAmount";
     public static final String FIELD_DEPRECIATED = "depreciated";
     public static final String FIELD_NET_ASSET_VALUE = "netAssetValue";
     public static final String FIELD_EVALUATION_VALUE = "evaluationValue";
     public static final String FIELD_REMAINING_SERVICE_LIFE = "remainingServiceLife";
     public static final String FIELD_IF_PLEDGE = "ifPledge";
     public static final String FIELD_IF_INSURE = "ifInsure";
     public static final String FIELD_IF_REDUCE_EXEMPT_TAX = "ifReduceExemptTax";
     public static final String FIELD_RENTAL_PLACE = "rentalPlace";
     public static final String FIELD_AIRCRAFT_MANUFACTURER = "aircraftManufacturer";
     public static final String FIELD_AIRPLANE_MODEL = "airplaneModel";
     public static final String FIELD_ENGINE = "engine";
     public static final String FIELD_INTERNATIONAL_REGISTRATION_MSN = "internationalRegistrationMsn";
     public static final String FIELD_MTOW = "mtow";
     public static final String FIELD_MAX_RANGE = "maxRange";
     public static final String FIELD_UOM = "uom";
     public static final String FIELD_ORIGINAL_ASSET_VALUE = "originalAssetValue";
     public static final String FIELD_STAKE = "stake";
     public static final String FIELD_DETAIL_LENGTH = "detailLength";
     public static final String FIELD_AREA = "area";
     public static final String FIELD_LOCATED = "located";
     public static final String FIELD_REAL_ESTATE_NUMBER = "realEstateNumber";


     @Id
     @GeneratedValue
     private Long leaseItemDetailId;

     private Long leaseItemId;

     @Length(max = 2000)
     private String leaseFullName;

     @Length(max = 500)
     private String purchaseContractNumber;

     @Length(max = 500)
     private String detailType;

     @Length(max = 500)
     private String quantity;

     @Length(max = 500)
     private String certificateSerialNumber;

     @Length(max = 500)
     private String venderName;

     private Double purchasePrice;

     private Date recordedTime;

     private Double creditedAmount;

     @Length(max = 2000)
     private String depreciated;

     private Double netAssetValue;

     private Double evaluationValue;

     private Long remainingServiceLife;

     @Length(max = 50)
     private String ifPledge;

     @Length(max = 50)
     private String ifInsure;

     @Length(max = 50)
     private String ifReduceExemptTax;

     @Length(max = 2000)
     private String rentalPlace;

     @Length(max = 2000)
     private String aircraftManufacturer;

     @Length(max = 800)
     private String airplaneModel;

     @Length(max = 800)
     private String engine;

     @Length(max = 800)
     private String internationalRegistrationMsn;

     private Double mtow;

     private Double maxRange;

     @Length(max = 500)
     private String uom;

     private Double originalAssetValue;

     @Length(max = 500)
     private String stake;

     private Double detailLength;

     private Double area;

     @Length(max = 2000)
     private String located;

     @Length(max = 800)
     private String realEstateNumber;

     private String assetTypes;

     @Transient
     private String ifPledgeN;

    @Transient
    private String ifInsureN;

    @Transient
    private String ifReduceExemptTaxN;
    //LEASE_MORTGAGOR
    private String leaseMortgagor;
    //PRICE
    private Double price;
    //REGISTRATION_AGENCY
    private String registrationAgency;
    //MORTGAGE_DATE_FROM
    private Date mortgageDateFrom;
    //MORTGAGE_DATE_TO
    private Date mortgageDateTo;
    //
    private String patternDet;

    private String pattern;
    private String pledgeState;
    private String mortgagor;

    //PLEDGE_CONTRACT_NUM
    private String pledgeContractNum;
    //PLEDGE_ASSET_VALUE
    private Long pledgeAssetValue;
    //PLEDGE_ASSET_DEC
    private String pledgeAssetDec;

    @Transient
    private String leaseItemCode;
    @Transient
    private String fullName;
    @Transient
    private String leaseItemTypeN;
//    @Transient
    private String patternN;
    @Transient
    private String mortgagorN;
//    @Transient
    private String pledgeStateN;
    @Transient
    private Double assetValueTotal;
    @Transient
    private Double originalAssetValueTotal;

    @Transient
    private String  projectNumber;

    @Transient
    private String  contractNumber;



    public String getLeaseMortgagor() {
        return leaseMortgagor;
    }

    public void setLeaseMortgagor(String leaseMortgagor) {
        this.leaseMortgagor = leaseMortgagor;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getRegistrationAgency() {
        return registrationAgency;
    }

    public void setRegistrationAgency(String registrationAgency) {
        this.registrationAgency = registrationAgency;
    }

    public Date getMortgageDateFrom() {
        return mortgageDateFrom;
    }

    public void setMortgageDateFrom(Date mortgageDateFrom) {
        this.mortgageDateFrom = mortgageDateFrom;
    }

    public Date getMortgageDateTo() {
        return mortgageDateTo;
    }

    public void setMortgageDateTo(Date mortgageDateTo) {
        this.mortgageDateTo = mortgageDateTo;
    }

    public String getPatternDet() {
        return patternDet;
    }

    public void setPatternDet(String patternDet) {
        this.patternDet = patternDet;
    }

    public String getPledgeContractNum() {
        return pledgeContractNum;
    }

    public void setPledgeContractNum(String pledgeContractNum) {
        this.pledgeContractNum = pledgeContractNum;
    }

    public Long getPledgeAssetValue() {
        return pledgeAssetValue;
    }

    public void setPledgeAssetValue(Long pledgeAssetValue) {
        this.pledgeAssetValue = pledgeAssetValue;
    }

    public String getPledgeAssetDec() {
        return pledgeAssetDec;
    }

    public void setPledgeAssetDec(String pledgeAssetDec) {
        this.pledgeAssetDec = pledgeAssetDec;
    }

    public void setLeaseFullName(String leaseFullName){
         this.leaseFullName = leaseFullName;
     }

     public String getLeaseFullName(){
         return leaseFullName;
     }

     public void setPurchaseContractNumber(String purchaseContractNumber){
         this.purchaseContractNumber = purchaseContractNumber;
     }

     public String getPurchaseContractNumber(){
         return purchaseContractNumber;
     }

     public void setDetailType(String detailType){
         this.detailType = detailType;
     }

     public String getDetailType(){
         return detailType;
     }

     public void setQuantity(String quantity){
         this.quantity = quantity;
     }

     public String getQuantity(){
         return quantity;
     }

     public void setCertificateSerialNumber(String certificateSerialNumber){
         this.certificateSerialNumber = certificateSerialNumber;
     }

     public String getCertificateSerialNumber(){
         return certificateSerialNumber;
     }

     public void setVenderName(String venderName){
         this.venderName = venderName;
     }

     public String getVenderName(){
         return venderName;
     }


     public void setRecordedTime(Date recordedTime){
         this.recordedTime = recordedTime;
     }

     public Date getRecordedTime(){
         return recordedTime;
     }


     public void setDepreciated(String depreciated){
         this.depreciated = depreciated;
     }

     public String getDepreciated(){
         return depreciated;
     }

     public void setIfPledge(String ifPledge){
         this.ifPledge = ifPledge;
     }

     public String getIfPledge(){
         return ifPledge;
     }

     public void setIfInsure(String ifInsure){
         this.ifInsure = ifInsure;
     }

     public String getIfInsure(){
         return ifInsure;
     }

     public void setIfReduceExemptTax(String ifReduceExemptTax){
         this.ifReduceExemptTax = ifReduceExemptTax;
     }

     public String getIfReduceExemptTax(){
         return ifReduceExemptTax;
     }

     public void setRentalPlace(String rentalPlace){
         this.rentalPlace = rentalPlace;
     }

     public String getRentalPlace(){
         return rentalPlace;
     }

     public void setAircraftManufacturer(String aircraftManufacturer){
         this.aircraftManufacturer = aircraftManufacturer;
     }

     public String getAircraftManufacturer(){
         return aircraftManufacturer;
     }

     public void setAirplaneModel(String airplaneModel){
         this.airplaneModel = airplaneModel;
     }

     public String getAirplaneModel(){
         return airplaneModel;
     }

     public void setEngine(String engine){
         this.engine = engine;
     }

     public String getEngine(){
         return engine;
     }

     public void setInternationalRegistrationMsn(String internationalRegistrationMsn){
         this.internationalRegistrationMsn = internationalRegistrationMsn;
     }

     public String getInternationalRegistrationMsn(){
         return internationalRegistrationMsn;
     }


     public void setUom(String uom){
         this.uom = uom;
     }

     public String getUom(){
         return uom;
     }


     public void setStake(String stake){
         this.stake = stake;
     }

     public String getStake(){
         return stake;
     }


     public void setLocated(String located){
         this.located = located;
     }

     public String getLocated(){
         return located;
     }

     public void setRealEstateNumber(String realEstateNumber){
         this.realEstateNumber = realEstateNumber;
     }

     public String getRealEstateNumber(){
         return realEstateNumber;
     }

    public Long getLeaseItemDetailId() {
        return leaseItemDetailId;
    }

    public void setLeaseItemDetailId(Long leaseItemDetailId) {
        this.leaseItemDetailId = leaseItemDetailId;
    }

    public Long getLeaseItemId() {
        return leaseItemId;
    }

    public void setLeaseItemId(Long leaseItemId) {
        this.leaseItemId = leaseItemId;
    }

    public Double getPurchasePrice() {
        return purchasePrice;
    }

    public void setPurchasePrice(Double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    public Double getCreditedAmount() {
        return creditedAmount;
    }

    public void setCreditedAmount(Double creditedAmount) {
        this.creditedAmount = creditedAmount;
    }

    public Double getNetAssetValue() {
        return netAssetValue;
    }

    public void setNetAssetValue(Double netAssetValue) {
        this.netAssetValue = netAssetValue;
    }

    public Double getEvaluationValue() {
        return evaluationValue;
    }

    public void setEvaluationValue(Double evaluationValue) {
        this.evaluationValue = evaluationValue;
    }

    public Long getRemainingServiceLife() {
        return remainingServiceLife;
    }

    public void setRemainingServiceLife(Long remainingServiceLife) {
        this.remainingServiceLife = remainingServiceLife;
    }

    public Double getMtow() {
        return mtow;
    }

    public void setMtow(Double mtow) {
        this.mtow = mtow;
    }

    public Double getMaxRange() {
        return maxRange;
    }

    public void setMaxRange(Double maxRange) {
        this.maxRange = maxRange;
    }

    public Double getOriginalAssetValue() {
        return originalAssetValue;
    }

    public void setOriginalAssetValue(Double originalAssetValue) {
        this.originalAssetValue = originalAssetValue;
    }

    public Double getDetailLength() {
        return detailLength;
    }

    public void setDetailLength(Double detailLength) {
        this.detailLength = detailLength;
    }

    public Double getArea() {
        return area;
    }

    public void setArea(Double area) {
        this.area = area;
    }

    public String getAssetTypes() {
        return assetTypes;
    }

    public void setAssetTypes(String assetTypes) {
        this.assetTypes = assetTypes;
    }

    public String getIfPledgeN() {
        return ifPledgeN;
    }

    public void setIfPledgeN(String ifPledgeN) {
        this.ifPledgeN = ifPledgeN;
    }

    public String getIfInsureN() {
        return ifInsureN;
    }

    public void setIfInsureN(String ifInsureN) {
        this.ifInsureN = ifInsureN;
    }

    public String getIfReduceExemptTaxN() {
        return ifReduceExemptTaxN;
    }

    public void setIfReduceExemptTaxN(String ifReduceExemptTaxN) {
        this.ifReduceExemptTaxN = ifReduceExemptTaxN;
    }

    private Double  netBookValue ;

    private Long  remainUseMonth ;

    private String specificationModel;

    private Long serialNumber;

    private String leaseCategory;
    private Double mortgagePledgeAmount;
    private String mortgagePledgeExplain;
    private String description;

    public Double getNetBookValue() {
        return netBookValue;
    }

    public void setNetBookValue(Double netBookValue) {
        this.netBookValue = netBookValue;
    }

    public Long getRemainUseMonth() {
        return remainUseMonth;
    }

    public void setRemainUseMonth(Long remainUseMonth) {
        this.remainUseMonth = remainUseMonth;
    }

    public String getSpecificationModel() {
        return specificationModel;
    }

    public void setSpecificationModel(String specificationModel) {
        this.specificationModel = specificationModel;
    }

    public Long getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    public String getLeaseCategory() {
        return leaseCategory;
    }

    public void setLeaseCategory(String leaseCategory) {
        this.leaseCategory = leaseCategory;
    }

    public Double getMortgagePledgeAmount() {
        return mortgagePledgeAmount;
    }

    public void setMortgagePledgeAmount(Double mortgagePledgeAmount) {
        this.mortgagePledgeAmount = mortgagePledgeAmount;
    }

    public String getMortgagePledgeExplain() {
        return mortgagePledgeExplain;
    }

    public void setMortgagePledgeExplain(String mortgagePledgeExplain) {
        this.mortgagePledgeExplain = mortgagePledgeExplain;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
