package com.hand.hls.pam.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import groovy.transform.NotYetImplemented;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "WARRANT_STOCK_HD")
@Getter
@Setter
public class HlsWarrantStockHd extends BaseDTO {

     public static final String FIELD_WARRANT_STOCK_ID = "warrantStockId";
     public static final String FIELD_STOCK_TYPE = "stockType";
     public static final String FIELD_RETURN_DATE = "returnDate";
     public static final String FIELD_HD_ID = "hdId";
     public static final String FIELD_STOCK_DESCRIPTION = "stockDescription";


     @Id
     @GeneratedValue
     private Long warrantStockId;

     @Length(max = 200)
     private String stockType;

     private Date returnDate;

     private Long hdId;

     @Length(max = 2000)
     private String stockDescription;

     private Long applicantId;

     private Long applicantUnit ;

     private Date applicantDate;

     private String applicantNumber;

     private String approveStatus;

     private Long projectId;


    private String contractName;

    private String contractNumber;

     @Transient
     private String  applicantName;
     @Transient
     private String  unitName;
     @Transient
     private String stockTypeN;
     @Transient
     private String hdIdN;
     @Transient
     private String approveStatusN;

     @Transient
     private String bpName;

     @Transient
     private String warrantStatus;

     @Transient
     private Long warrantId;

     @Transient
     private String warrantStatusN;

     @Transient
     private String warrantName;

     @Transient
     private Long allocationId;

     @Transient
     private String paymentFlag;

     private Long  stockManager;

     private Long applicantEmploy;


     public void setWarrantStockId(Long warrantStockId){
         this.warrantStockId = warrantStockId;
     }

     public Long getWarrantStockId(){
         return warrantStockId;
     }

     public void setStockType(String stockType){
         this.stockType = stockType;
     }

     public String getStockType(){
         return stockType;
     }

     public void setReturnDate(Date returnDate){
         this.returnDate = returnDate;
     }

     public Date getReturnDate(){
         return returnDate;
     }

     public void setHdId(Long hdId){
         this.hdId = hdId;
     }

     public Long getHdId(){
         return hdId;
     }

     public void setStockDescription(String stockDescription){
         this.stockDescription = stockDescription;
     }

     public String getStockDescription(){
         return stockDescription;
     }

    public Long getApplicantId() {
        return applicantId;
    }

    public void setApplicantId(Long applicantId) {
        this.applicantId = applicantId;
    }

    public Long getApplicantUnit() {
        return applicantUnit;
    }

    public void setApplicantUnit(Long applicantUnit) {
        this.applicantUnit = applicantUnit;
    }

    public Date getApplicantDate() {
        return applicantDate;
    }

    public void setApplicantDate(Date applicantDate) {
        this.applicantDate = applicantDate;
    }


    public String getApplicantNumber() {
        return applicantNumber;
    }

    public void setApplicantNumber(String applicantNumber) {
        this.applicantNumber = applicantNumber;
    }


    public String getApproveStatus() {
        return approveStatus;
    }

    public void setApproveStatus(String approveStatus) {
        this.approveStatus = approveStatus;
    }

    public String getApplicantName() {
        return applicantName;
    }

    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public String getStockTypeN() {
        return stockTypeN;
    }

    public void setStockTypeN(String stockTypeN) {
        this.stockTypeN = stockTypeN;
    }

    public String getHdIdN() {
        return hdIdN;
    }

    public void setHdIdN(String hdIdN) {
        this.hdIdN = hdIdN;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public String getContractName() {
        return contractName;
    }

    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    public String getContractNumber() {
        return contractNumber;
    }

    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    public String getApproveStatusN() {
        return approveStatusN;
    }

    public void setApproveStatusN(String approveStatusN) {
        this.approveStatusN = approveStatusN;
    }

    public String getBpName() {
        return bpName;
    }

    public void setBpName(String bpName) {
        this.bpName = bpName;
    }

    public String getWarrantStatus() {
        return warrantStatus;
    }

    public void setWarrantStatus(String warrantStatus) {
        this.warrantStatus = warrantStatus;
    }

    public Long getWarrantId() {
        return warrantId;
    }

    public void setWarrantId(Long warrantId) {
        this.warrantId = warrantId;
    }

    public String getWarrantStatusN() {
        return warrantStatusN;
    }

    public void setWarrantStatusN(String warrantStatusN) {
        this.warrantStatusN = warrantStatusN;
    }


    public String getWarrantName() {
        return warrantName;
    }

    public void setWarrantName(String warrantName) {
        this.warrantName = warrantName;
    }

    public Long getAllocationId() {
        return allocationId;
    }

    public void setAllocationId(Long allocationId) {
        this.allocationId = allocationId;
    }

    public String getPaymentFlag() {
        return paymentFlag;
    }

    public void setPaymentFlag(String paymentFlag) {
        this.paymentFlag = paymentFlag;
    }

    public Long getStockManager() {
        return stockManager;
    }

    public void setStockManager(Long stockManager) {
        this.stockManager = stockManager;
    }

    public Long getApplicantEmploy() {
        return applicantEmploy;
    }

    public void setApplicantEmploy(Long applicantEmploy) {
        this.applicantEmploy = applicantEmploy;
    }
}
