package com.hand.hls.pam.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "lease_asset_hd")
public class LeaseAssetHd extends BaseDTO {

     public static final String FIELD_ASSET_HD_ID = "assetHdId";
     public static final String FIELD_ASSET_NUMBER = "assetNumber";
     public static final String FIELD_MODIFY_DATE = "modifyDate";
     public static final String FIELD_MODIFY_PERSON = "modifyPerson";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_MODIFY_UNIT = "modifyUnit";
     public static final String FIELD_ASSET_STATUS = "assetStatus";


     @Id
     @GeneratedValue
     private Long assetHdId;

     @Length(max = 500)
     private String assetNumber; //重估编号

     private Date modifyDate; //维护时间

     @Length(max = 100)
     private String modifyPerson; //维护人

     @Length(max = 2147483647)
     private String description; //备注

     @Length(max = 100)
     private String modifyUnit; //维护部门

     @Length(max = 200)
     private String assetStatus; //状态
    @Transient
    private String modifyPersonN;
    @Transient
    private String assetStatusN;
    @Transient
    private String modifyUnitN;
    private Long processInstanceId;

    private String authorityRuleString;

    public String getAuthorityRuleString() {
        return authorityRuleString;
    }

    public void setAuthorityRuleString(String authorityRuleString) {
        this.authorityRuleString = authorityRuleString;
    }

    public Long getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(Long processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    public String getModifyUnitN() {
        return modifyUnitN;
    }

    public void setModifyUnitN(String modifyUnitN) {
        this.modifyUnitN = modifyUnitN;
    }

    public void setAssetHdId(Long assetHdId){
         this.assetHdId = assetHdId;
     }

     public Long getAssetHdId(){
         return assetHdId;
     }

     public void setAssetNumber(String assetNumber){
         this.assetNumber = assetNumber;
     }

     public String getAssetNumber(){
         return assetNumber;
     }

     public void setModifyDate(Date modifyDate){
         this.modifyDate = modifyDate;
     }

     public Date getModifyDate(){
         return modifyDate;
     }

     public void setModifyPerson(String modifyPerson){
         this.modifyPerson = modifyPerson;
     }

     public String getModifyPerson(){
         return modifyPerson;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setModifyUnit(String modifyUnit){
         this.modifyUnit = modifyUnit;
     }

     public String getModifyUnit(){
         return modifyUnit;
     }

     public void setAssetStatus(String assetStatus){
         this.assetStatus = assetStatus;
     }

     public String getAssetStatus(){
         return assetStatus;
     }

    public String getModifyPersonN() {
        return modifyPersonN;
    }

    public void setModifyPersonN(String modifyPersonN) {
        this.modifyPersonN = modifyPersonN;
    }

    public String getAssetStatusN() {
        return assetStatusN;
    }

    public void setAssetStatusN(String assetStatusN) {
        this.assetStatusN = assetStatusN;
    }
}
