package com.hand.hls.abs.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Data;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @author ferry
 * @date 2018-12-03
 * @description ABS 资产包-合同 pojo
 */

@Data
@ExtensionAttribute(disable = true)
@Table(name = "ct_abs_property_contract")
public class HlsCusAbsPropertyContract extends BaseDTO {


    @Id
    @GeneratedValue
    private Long propertyContractId; //pk

    @NotNull
    private Long contractId; //租赁合同id

    private BigDecimal totalPrincipal; // 应收本金

    private BigDecimal totalInterest;  // 应收利息

    private BigDecimal uncollectedPrincipal; // 未收本金

    private BigDecimal uncollectedInterest;  // 未收利息

    private BigDecimal receivedInterest;  // 已收利息

    private BigDecimal netReceivedInterest;  // 不含税已收利息

    private BigDecimal receivedPrincipal;  // 已收本金

    @Length(max = 1)
    private String overDue; //是否逾期(Y/N)

    @Length(max = 20)
    private String documentType;  // 单据类别(CON_CONTRACT/FCT_CONTRACT)

    private Long projectId;   // ABS立项id

    private Long productId;  // ABS产品id

    @Transient
    private String contractName;   // 合同名称

    @Transient
    private String contractNumber;  // 合同编号

    @Transient
    private String useStatus;   // 合同使用状态

    @Transient
    private String propertyNumber;   // 资产包编号

    @Transient
    private String bpName;   // 承租人

    @Transient
    private String projectName;  // 项目名称

    @Transient
    private String projectNumber;   // 项目编号

    @Transient
    private Date projectDate;   // 打包日期

    @Transient
    private String createPerson;   // 创建人

    @Transient
    private String param;

    @Transient
    private Long[] propertyContractIds;

    @Transient
    private Long[] contractIds;

    @Transient
    private String dateStr;
    @Transient
    private String dateStr2;   // 日期字符串格式
}

