package com.hand.hls.abs.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.math.BigDecimal;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "CT_ABS_PRODUCT_BUYBACK")
@Getter
@Setter
public class HlsCusAbsProductBuyback extends BaseDTO {

     public static final String FIELD_BUYBACK_ID = "buybackId";
     public static final String FIELD_PRODUCT_ID = "productId";
     public static final String FIELD_BUYBACK_COMPANY_ID = "buybackCompanyId";
     public static final String FIELD_STRUCTURE_ID = "structureId";
     public static final String FIELD_BANK_ACCOUNT_ID = "bankAccountId";
     public static final String FIELD_BUYBACK_AMOUNT = "buybackAmount";
     public static final String FIELD_BUYBACK_DATE = "buybackDate";
     public static final String FIELD_BUYBACK_REASON = "buybackReason";


     @Id
     @GeneratedValue
     private Long buybackId;

     private Long productId;

     private Long buybackCompanyId;

     private Long structureId;

     private Long bankAccountId;

     private BigDecimal buybackAmount;

     private Date buybackDate;

     @Length(max = 200)
     private String buybackReason;

     private BigDecimal receiverAmount;

     private Long cfItem;

     private Long cfType;

     private Long absBankAccountId;

     @Transient
     private String outBankAccountName;

     @Transient
     private String outBankAccountNum;

     @Transient
     private String outBankBranchName;

     @Transient
     private String inBankAccountName;

     @Transient
     private String inBankAccountNum;

     @Transient
     private String inBankBranchName;

     @Transient
     private String companyFullName;

     @Transient
     private String projectGrade;

     @Transient
     private BigDecimal  surplusCashPrincipal;

}
