package com.hand.hls.taa.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "jc_transfer_application")
public class JcTransferApplication extends BaseDTO {

     public static final String FIELD_TRANSFER_APPLICATION_ID = "transferApplicationId";
     public static final String FIELD_TRANSFER_APPLICATION_NUMBER = "transferApplicationNumber";
     public static final String FIELD_EMPLOYEE_ID = "employeeId";
     public static final String FIELD_UNIT_ID = "unitId";
     public static final String FIELD_APPLICATION_DATE = "applicationDate";
     public static final String FIELD_STATUS = "status";


     @Id
     @GeneratedValue
     private Long transferApplicationId;

     @Length(max = 100)
     private String transferApplicationNumber; //转账申请编号

     private Long employeeId; //经办人

     private Long unitId; //经办部门

     private Date applicationDate; //申请日期

     @Length(max = 255)
     private String status; //审批状态

    @Transient
    private String employeeIdN;
    @Transient
    private String unitIdN;
    @Transient
    private String statusN;
    private Long processInstanceId;
    @Transient
    private String authority;

    public String getAuthority() {
        return authority;
    }

    public void setAuthority(String authority) {
        this.authority = authority;
    }

    public Long getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(Long processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    public String getEmployeeIdN() {
        return employeeIdN;
    }

    public void setEmployeeIdN(String employeeIdN) {
        this.employeeIdN = employeeIdN;
    }

    public String getUnitIdN() {
        return unitIdN;
    }

    public void setUnitIdN(String unitIdN) {
        this.unitIdN = unitIdN;
    }

    public String getStatusN() {
        return statusN;
    }

    public void setStatusN(String statusN) {
        this.statusN = statusN;
    }

    public void setTransferApplicationId(Long transferApplicationId){
         this.transferApplicationId = transferApplicationId;
     }

     public Long getTransferApplicationId(){
         return transferApplicationId;
     }

     public void setTransferApplicationNumber(String transferApplicationNumber){
         this.transferApplicationNumber = transferApplicationNumber;
     }

     public String getTransferApplicationNumber(){
         return transferApplicationNumber;
     }

     public void setEmployeeId(Long employeeId){
         this.employeeId = employeeId;
     }

     public Long getEmployeeId(){
         return employeeId;
     }

     public void setUnitId(Long unitId){
         this.unitId = unitId;
     }

     public Long getUnitId(){
         return unitId;
     }

     public void setApplicationDate(Date applicationDate){
         this.applicationDate = applicationDate;
     }

     public Date getApplicationDate(){
         return applicationDate;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     }
