package com.hand.hls.wfl.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

@ExtensionAttribute(disable=true)
@Table(name = "wfl_appoint_approver")
public class HlsCusWflAppointApprover extends BaseDTO {

     public static final String FIELD_APPROVER_ID = "approverId";
     public static final String FIELD_PROCESS_INSTANCE_ID = "processInstanceId";
     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_USER_ALLOCATION_ID = "userAllocationId";
     public static final String FIELD_SOURCE_ID = "sourceId";
     public static final String FIELD_SOURCE_TABLE = "sourceTable";
     public static final String FIELD_SID_CODE = "sidCode";


     /**
     *pk
     */
     @Id
     @GeneratedValue
     private Long approverId;

     /**
     *工作流实例ID
     */
     private Long processInstanceId;

     /**
     *指派人ID
     */
     @NotNull
     private Long userId;

     /**
     *被指派审批人(sys_user_allocation.allocation_id)
     */
     @NotNull
     private Long userAllocationId;

     /**
     *来源表ID=business_key
     */
     @Length(max = 200)
     private String sourceId;

     /**
     *来源表
     */
     @Length(max = 200)
     private String sourceTable;

     @Length(max = 255)
     private String sidCode;


    @Transient
    private String userAllocationIdN;

    public String getUserAllocationIdN() {
        return userAllocationIdN;
    }

    public void setUserAllocationIdN(String userAllocationIdN) {
        this.userAllocationIdN = userAllocationIdN;
    }

    public void setApproverId(Long approverId){
         this.approverId = approverId;
     }

     public Long getApproverId(){
         return approverId;
     }

     public void setProcessInstanceId(Long processInstanceId){
         this.processInstanceId = processInstanceId;
     }

     public Long getProcessInstanceId(){
         return processInstanceId;
     }

     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     public void setUserAllocationId(Long userAllocationId){
         this.userAllocationId = userAllocationId;
     }

     public Long getUserAllocationId(){
         return userAllocationId;
     }

     public void setSourceId(String sourceId){
         this.sourceId = sourceId;
     }

     public String getSourceId(){
         return sourceId;
     }

     public void setSourceTable(String sourceTable){
         this.sourceTable = sourceTable;
     }

     public String getSourceTable(){
         return sourceTable;
     }

     public void setSidCode(String sidCode){
         this.sidCode = sidCode;
     }

     public String getSidCode(){
         return sidCode;
     }

     }
