package com.hand.hls.ecif.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hls.bp.dto.HlsBpMaster;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable=true)
@Table(name = "WS_BP_MASTER_REQUEST_RECORDS")
public class HlsCusBpMasterRequestRecords extends BaseDTO {

     public static final String FIELD_BP_RECORD_ID = "bpRecordId";
     public static final String FIELD_OPRTN_IND = "oprtnInd";
     public static final String FIELD_CST_NO = "cstNo";
     public static final String FIELD_CST_NM_S = "cstNmS";
     public static final String FIELD_IDENT_NO = "identNo";
     public static final String FIELD_INST_IDENT_TP = "instIdentTp";
     public static final String FIELD_UNIFD_SOCL_CRDT_CD = "unifdSoclCrdtCd";
     public static final String FIELD_CST_TP = "cstTp";
     public static final String FIELD_OVRS_CST_CHIN_NM = "ovrsCstChinNm";
     public static final String FIELD_RGSTRTN_CTY_AND_DSTC_CD = "rgstrtnCtyAndDstcCd";
     public static final String FIELD_MAINCORPRTNACTVCTYORDSTCCD = "maincorprtnactvctyordstccd";
     public static final String FIELD_CST_LO_NATL_STD_IDY = "cstLoNatlStdIdy";
     public static final String FIELD_SWIFTNO = "swiftno";
     public static final String FIELD_ENTP_ATCH_RLTNP = "entpAtchRltnp";
     public static final String FIELD_ECNM_TP = "ecnmTp";
     public static final String FIELD_LGL_RPRS_NM = "lglRprsNm";
     public static final String FIELD_CORPRTN_SCOP1 = "corprtnScop1";
     public static final String FIELD_CRDT_CST_FLG = "crdtCstFlg";
     public static final String FIELD_ORG_CUST_TYPE = "orgCustType";
     public static final String FIELD_BUSINESS_DATE = "businessDate";


     @Id
     @GeneratedValue
     private Long bpRecordId;

     private Long bpId;

     @Length(max = 100)
     private String oprtnInd;

     @Length(max = 100)
     private String cstNo;

     @Length(max = 500)
     private String cstNmS;

     @Length(max = 100)
     private String identNo;

     @Length(max = 100)
     private String instIdentTp;

     @Length(max = 100)
     private String unifdSoclCrdtCd;

     @Length(max = 100)
     private String cstTp;

     @Length(max = 100)
     private String ovrsCstChinNm;

     @Length(max = 100)
     private String rgstrtnCtyAndDstcCd;

     @Length(max = 100)
     private String maincorprtnactvctyordstccd;

     @Length(max = 100)
     private String cstLoNatlStdIdy;

     @Length(max = 100)
     private String swiftno;

     @Length(max = 100)
     private String entpAtchRltnp;

     @Length(max = 100)
     private String ecnmTp;

     @Length(max = 100)
     private String lglRprsNm;

     @Length(max = 2000)
     private String corprtnScop1;

     @Length(max = 100)
     private String crdtCstFlg;

     @Length(max = 100)
     private String orgCustType;

     @Length(max = 100)
     private String businessDate;

     private String code;

     private String msg;


    @Transient
    @Children
    List<HlsBpMaster> hlsBpMasterList;


    @Transient
    private Long outboundId;

    @Transient
    private String cstTpC;

    @Transient
    private String cstTpN;

    @Transient
    private String rgstrtnCtyAndDstcCdC;

    @Transient
    private String rgstrtnCtyAndDstcCdN;

    @Transient
    private String maincorprtnactvctyordstccdC;

    @Transient
    private String maincorprtnactvctyordstccdN;

    @Transient
    private String cstLoNatlStdIdyC;

    @Transient
    private String cstLoNatlStdIdyN;

    @Transient
    private String entpAtchRltnpC;

    @Transient
    private String entpAtchRltnpN;

    @Transient
    private String ecnmTpC;

    @Transient
    private String ecnmTpN;

    @Transient
    private String crdtCstFlgC;

    @Transient
    private String crdtCstFlgN;

    @Transient
    private String orgCustTypeN;

    @Transient
    private String orgCustTypeC;

    @Transient
    private String instIdentTpC;

    @Transient
    private String instIdentTpN;

    @Transient
    private String dataType;

    @Transient
    private Long projectId;

    @Transient
    private String isFirstSuccess;

    private String operator;

    private String updateDate;

    private String lastUpdatedTe;

    private String updateSource;

    private String dataSource;

    private String ecifCreateDate;

    private String changeDate;

    private String operatorType;

    private String operatorUser;

    private Date requestDate;

    @Transient
    private String beforeCstLoNatlStdIdy;

    @Transient
    private String beforeOvrsCstChinNm;

    @Transient
    private String beforeSwiftno;

    public static String getFieldBpRecordId() {
        return FIELD_BP_RECORD_ID;
    }

    public String getBeforeCstLoNatlStdIdy() {
        return beforeCstLoNatlStdIdy;
    }

    public void setBeforeCstLoNatlStdIdy(String beforeCstLoNatlStdIdy) {
        this.beforeCstLoNatlStdIdy = beforeCstLoNatlStdIdy;
    }

    public String getBeforeOvrsCstChinNm() {
        return beforeOvrsCstChinNm;
    }

    public void setBeforeOvrsCstChinNm(String beforeOvrsCstChinNm) {
        this.beforeOvrsCstChinNm = beforeOvrsCstChinNm;
    }

    public String getBeforeSwiftno() {
        return beforeSwiftno;
    }

    public void setBeforeSwiftno(String beforeSwiftno) {
        this.beforeSwiftno = beforeSwiftno;
    }

    public String getChangeDate() {
        return changeDate;
    }

    public void setChangeDate(String changeDate) {
        this.changeDate = changeDate;
    }

    public String getOperatorType() {
        return operatorType;
    }

    public void setOperatorType(String operatorType) {
        this.operatorType = operatorType;
    }

    public String getOperatorUser() {
        return operatorUser;
    }

    public void setOperatorUser(String operatorUser) {
        this.operatorUser = operatorUser;
    }

    public Date getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    public String getEcifCreateDate() {
        return ecifCreateDate;
    }

    public void setEcifCreateDate(String ecifCreateDate) {
        this.ecifCreateDate = ecifCreateDate;
    }

    public String getIsFirstSuccess() {
        return isFirstSuccess;
    }

    public void setIsFirstSuccess(String isFirstSuccess) {
        this.isFirstSuccess = isFirstSuccess;
    }

    public String getInstIdentTpC() {
        return instIdentTpC;
    }

    public void setInstIdentTpC(String instIdentTpC) {
        this.instIdentTpC = instIdentTpC;
    }

    public String getInstIdentTpN() {
        return instIdentTpN;
    }

    public void setInstIdentTpN(String instIdentTpN) {
        this.instIdentTpN = instIdentTpN;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Long getOutboundId() {
        return outboundId;
    }

    public void setOutboundId(Long outboundId) {
        this.outboundId = outboundId;
    }

    public List<HlsBpMaster> getHlsBpMasterList() {
        return hlsBpMasterList;
    }

    public void setHlsBpMasterList(List<HlsBpMaster> hlsBpMasterList) {
        this.hlsBpMasterList = hlsBpMasterList;
    }

    public Long getBpId() {
        return bpId;
    }

    public void setBpId(Long bpId) {
        this.bpId = bpId;
    }

    public void setBpRecordId(Long bpRecordId){
         this.bpRecordId = bpRecordId;
     }

     public Long getBpRecordId(){
         return bpRecordId;
     }

     public void setOprtnInd(String oprtnInd){
         this.oprtnInd = oprtnInd;
     }

     public String getOprtnInd(){
         return oprtnInd;
     }

     public void setCstNo(String cstNo){
         this.cstNo = cstNo;
     }

     public String getCstNo(){
         return cstNo;
     }

     public void setCstNmS(String cstNmS){
         this.cstNmS = cstNmS;
     }

     public String getCstNmS(){
         return cstNmS;
     }

     public void setIdentNo(String identNo){
         this.identNo = identNo;
     }

     public String getIdentNo(){
         return identNo;
     }

     public void setInstIdentTp(String instIdentTp){
         this.instIdentTp = instIdentTp;
     }

     public String getInstIdentTp(){
         return instIdentTp;
     }

     public void setUnifdSoclCrdtCd(String unifdSoclCrdtCd){
         this.unifdSoclCrdtCd = unifdSoclCrdtCd;
     }

     public String getUnifdSoclCrdtCd(){
         return unifdSoclCrdtCd;
     }

     public void setCstTp(String cstTp){
         this.cstTp = cstTp;
     }

     public String getCstTp(){
         return cstTp;
     }

     public void setOvrsCstChinNm(String ovrsCstChinNm){
         this.ovrsCstChinNm = ovrsCstChinNm;
     }

     public String getOvrsCstChinNm(){
         return ovrsCstChinNm;
     }

     public void setRgstrtnCtyAndDstcCd(String rgstrtnCtyAndDstcCd){
         this.rgstrtnCtyAndDstcCd = rgstrtnCtyAndDstcCd;
     }

     public String getRgstrtnCtyAndDstcCd(){
         return rgstrtnCtyAndDstcCd;
     }

     public void setMaincorprtnactvctyordstccd(String maincorprtnactvctyordstccd){
         this.maincorprtnactvctyordstccd = maincorprtnactvctyordstccd;
     }

     public String getMaincorprtnactvctyordstccd(){
         return maincorprtnactvctyordstccd;
     }

     public void setCstLoNatlStdIdy(String cstLoNatlStdIdy){
         this.cstLoNatlStdIdy = cstLoNatlStdIdy;
     }

     public String getCstLoNatlStdIdy(){
         return cstLoNatlStdIdy;
     }

     public void setSwiftno(String swiftno){
         this.swiftno = swiftno;
     }

     public String getSwiftno(){
         return swiftno;
     }

     public void setEntpAtchRltnp(String entpAtchRltnp){
         this.entpAtchRltnp = entpAtchRltnp;
     }

     public String getEntpAtchRltnp(){
         return entpAtchRltnp;
     }

     public void setEcnmTp(String ecnmTp){
         this.ecnmTp = ecnmTp;
     }

     public String getEcnmTp(){
         return ecnmTp;
     }

     public void setLglRprsNm(String lglRprsNm){
         this.lglRprsNm = lglRprsNm;
     }

     public String getLglRprsNm(){
         return lglRprsNm;
     }

     public void setCorprtnScop1(String corprtnScop1){
         this.corprtnScop1 = corprtnScop1;
     }

     public String getCorprtnScop1(){
         return corprtnScop1;
     }

     public void setCrdtCstFlg(String crdtCstFlg){
         this.crdtCstFlg = crdtCstFlg;
     }

     public String getCrdtCstFlg(){
         return crdtCstFlg;
     }

     public void setOrgCustType(String orgCustType){
         this.orgCustType = orgCustType;
     }

     public String getOrgCustType(){
         return orgCustType;
     }

     public void setBusinessDate(String businessDate){
         this.businessDate = businessDate;
     }

     public String getBusinessDate(){
         return businessDate;
     }


    public String getCstTpC() {
        return cstTpC;
    }

    public void setCstTpC(String cstTpC) {
        this.cstTpC = cstTpC;
    }

    public String getCstTpN() {
        return cstTpN;
    }

    public void setCstTpN(String cstTpN) {
        this.cstTpN = cstTpN;
    }

    public String getRgstrtnCtyAndDstcCdC() {
        return rgstrtnCtyAndDstcCdC;
    }

    public void setRgstrtnCtyAndDstcCdC(String rgstrtnCtyAndDstcCdC) {
        this.rgstrtnCtyAndDstcCdC = rgstrtnCtyAndDstcCdC;
    }

    public String getRgstrtnCtyAndDstcCdN() {
        return rgstrtnCtyAndDstcCdN;
    }

    public void setRgstrtnCtyAndDstcCdN(String rgstrtnCtyAndDstcCdN) {
        this.rgstrtnCtyAndDstcCdN = rgstrtnCtyAndDstcCdN;
    }

    public String getMaincorprtnactvctyordstccdC() {
        return maincorprtnactvctyordstccdC;
    }

    public void setMaincorprtnactvctyordstccdC(String maincorprtnactvctyordstccdC) {
        this.maincorprtnactvctyordstccdC = maincorprtnactvctyordstccdC;
    }

    public String getMaincorprtnactvctyordstccdN() {
        return maincorprtnactvctyordstccdN;
    }

    public void setMaincorprtnactvctyordstccdN(String maincorprtnactvctyordstccdN) {
        this.maincorprtnactvctyordstccdN = maincorprtnactvctyordstccdN;
    }

    public String getCstLoNatlStdIdyC() {
        return cstLoNatlStdIdyC;
    }

    public void setCstLoNatlStdIdyC(String cstLoNatlStdIdyC) {
        this.cstLoNatlStdIdyC = cstLoNatlStdIdyC;
    }

    public String getCstLoNatlStdIdyN() {
        return cstLoNatlStdIdyN;
    }

    public void setCstLoNatlStdIdyN(String cstLoNatlStdIdyN) {
        this.cstLoNatlStdIdyN = cstLoNatlStdIdyN;
    }

    public String getEntpAtchRltnpC() {
        return entpAtchRltnpC;
    }

    public void setEntpAtchRltnpC(String entpAtchRltnpC) {
        this.entpAtchRltnpC = entpAtchRltnpC;
    }

    public String getEntpAtchRltnpN() {
        return entpAtchRltnpN;
    }

    public void setEntpAtchRltnpN(String entpAtchRltnpN) {
        this.entpAtchRltnpN = entpAtchRltnpN;
    }

    public String getEcnmTpC() {
        return ecnmTpC;
    }

    public void setEcnmTpC(String ecnmTpC) {
        this.ecnmTpC = ecnmTpC;
    }

    public String getEcnmTpN() {
        return ecnmTpN;
    }

    public void setEcnmTpN(String ecnmTpN) {
        this.ecnmTpN = ecnmTpN;
    }

    public String getCrdtCstFlgC() {
        return crdtCstFlgC;
    }

    public void setCrdtCstFlgC(String crdtCstFlgC) {
        this.crdtCstFlgC = crdtCstFlgC;
    }

    public String getCrdtCstFlgN() {
        return crdtCstFlgN;
    }

    public void setCrdtCstFlgN(String crdtCstFlgN) {
        this.crdtCstFlgN = crdtCstFlgN;
    }

    public String getOrgCustTypeN() {
        return orgCustTypeN;
    }

    public void setOrgCustTypeN(String orgCustTypeN) {
        this.orgCustTypeN = orgCustTypeN;
    }

    public String getOrgCustTypeC() {
        return orgCustTypeC;
    }

    public void setOrgCustTypeC(String orgCustTypeC) {
        this.orgCustTypeC = orgCustTypeC;
    }


    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public String getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    public String getLastUpdatedTe() {
        return lastUpdatedTe;
    }

    public void setLastUpdatedTe(String lastUpdatedTe) {
        this.lastUpdatedTe = lastUpdatedTe;
    }

    public String getUpdateSource() {
        return updateSource;
    }

    public void setUpdateSource(String updateSource) {
        this.updateSource = updateSource;
    }

    public String getDataSource() {
        return dataSource;
    }

    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
}
