function HLS_FORMATMONEY(v, p) {
    return Leaf.formatNumber(v, p);
}

function HLS_FORMATMONEY_ZERO_FILL(v, p) {
    return Leaf.formatNumber(v, p).replace(/0*$/g, '').replace(/\.$/, '');
}

function ON_GRID_COMBOBOX_FOCUS(combobox) {
    if (!combobox.optionDataSet.isLoaded) {
        combobox.optionDataSet.isLoaded = true;
        combobox.optionDataSet.query();
    }
}

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_CON_GRID_PROCESS'] = function(datas) {
    for (var i = 0;i < datas.length;i++) {
        var temp = datas[i];
        for (var name in temp.data) {
            var temp_record = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').find('column_name', name);
            if (temp_record) {
                if (temp_record.get('validation_type') == 'NUMBERFIELD') {
                    temp.data[name] = isNaN(temp.data[name]) == true ? temp.data[name] : parseFloat(parseFloat(temp.data[name]).toFixed(parseInt(temp_record.get('precision_num'))));
                }
            }
        }
    }
    return datas;
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SEEDETAIL_COLUMN_LN'] = function(value, record, name) {
    var editor_record = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').find('column_name', name),
        precision = parseInt(editor_record.get('precision_num')),
        validation_type = editor_record.get('validation_type');
    if ((validation_type == 'NUMBERFIELD' || validation_type == 'PERCENTFIELD') && !Ext.isEmpty(value)) {
        var temp_value = null;
        if (editor_record.get('allow_format') == 'TRUE') {
            if (precision) {
                if (editor_record.get('zero_fill') == 'TRUE') {
                    temp_value = HLS_FORMATMONEY(value, precision);
                } else {
                    temp_value = HLS_FORMATMONEY_ZERO_FILL(value, precision);
                }
            } else {
                temp_value = HLS_FORMATMONEY(value);
            }
        } else {
            if (precision && editor_record.get('allow_decimal') == 'TRUE') {
                if (editor_record.get('zero_fill') == 'TRUE') {
                	if(validation_type=='PERCENTFIELD'){
        				temp_value = parseFloat(mul(value,100)).toFixed(precision)+'%';
        			}else{
                    	temp_value = parseFloat(value).toFixed(precision);
                    }
                } else {
                	if(validation_type=='PERCENTFIELD'){
                		temp_value = parseFloat(mul(value,100)).toFixed(precision).replace(/0*$/g, '').replace(/\.$/, '')+'%';
                	}else{
                    	temp_value = parseFloat(value).toFixed(precision).replace(/0*$/g, '').replace(/\.$/, '');
                    }
                }
            } else {
                if (editor_record.get('allow_decimal') == 'TRUE') {
                	if(validation_type=='PERCENTFIELD'){
                    	temp_value = mul(value,100)+'%';
                    }else{
                    	temp_value = value;
                    }
                } else {
                	if(validation_type=='PERCENTFIELD'){
                    	temp_value = parseFloat(mul(value,100)).toFixed(0)+'%';
                	}else{
                		temp_value = parseFloat(parseFloat(value).toFixed(0));
                	}
                }
            }
        }
    } else if (validation_type == 'DATEPICKER') {
        temp_value = Leaf.formatDate(value);
    } else {
        temp_value = value;
    }
    window['${@layout_code}_renderer_model'](temp_value, record, name, editor_record);
    if (editor_record.get('renderer_flag') == 'Y') {
        return window['${@layout_code}_dynamic_link_renderer'](temp_value, record, name, editor_record, '${/parameter/@bp_seq}');
    } else {
        return temp_value;
    }

};
            
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SEEDETAIL_LN_PICTURE'] = function(value, record, name) {
    var pic = window['${@layout_code}_dynamic_pic_renderer'](record, name,'${/parameter/@bp_seq}');
    if (pic) {
        return pic;
    } else {
        return '';
    }
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_RENDERER'] = function(value, record, name) {	
	 var config_record = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').find('column_name', name);
	 if(config_record.get('validation_type') == 'BUTTON'){
	 	return window['${@layout_code}_dynamic_button_renderer'](value, record, name,config_record,'${/parameter/@bp_seq}');
	 }else{
     	return window['${@layout_code}_dynamic_link_renderer'](value, record, name,config_record,'${/parameter/@bp_seq}');
	 }
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_GRID_QUERY'] = function() {
    $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_ds').query();
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SEE_DETAIL_EDITOR'] = function(record, name) {
    var config_record = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').find('column_name', name);
    if(!config_record){
    	name = GET_CONFIG_COLUMN_NAME(name);
    	config_record = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').find('column_name', name);
    }
    if (config_record) {
        var editor = '${/parameter/@bp_seq}${@layout_code}_${@tab_code}_' + name + '_id';
        if (config_record.get('readonly_input_mode')=='TRUE'&&config_record.get('validation_type')!='TEXTAREA') {
            return '';
        }
        if (!record.isNew && config_record.get('input_mode') == 'REQUIRED_ONLY_ADD') {
            return '';
        } else {
            return editor;
        }
    }else{
    	return '';
    }
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_GRID_OBJECT_FOCUS'] = function(object) {
    var config_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds'),
        name = GET_CONFIG_COLUMN_NAME(object.binder.name),
        display_name = object.binder.name,
        record = object.record || object.binder.ds.create();
    var config_record = config_ds.find('column_name', name);
    var lov_cascade_para1 = config_record.get('lov_cascade_para1'),
        lov_cascade_para2 = config_record.get('lov_cascade_para2'),
        lov_cascade_para3 = config_record.get('lov_cascade_para3'),
        field = record.getField(display_name);
    if (object instanceof $L.Lov) {
        if (config_record.get('validation_type') == 'LOV' || config_record.get('validation_type') == 'LOV_C'|| config_record.get('validation_type') == 'LOV_D'|| config_record.get('validation_type') == 'LOV_D_C') {
            field.setLovPara('column_name', name);
            field.setLovPara('tab_code', config_record.get('tab_code'));
            field.setLovPara('config_id', config_record.get('config_id'));
            field.setLovPara('layout_code', config_record.get('layout_code'));
        }
        SETOBJECTPARA('LOV', '', field, lov_cascade_para1, record);
        SETOBJECTPARA('LOV', '', field, lov_cascade_para2, record);
        SETOBJECTPARA('LOV', '', field, lov_cascade_para3, record);
    } else if (object instanceof $L.ComboBox) {
        var combobox_ds = object.optionDataSet;
        combobox_ds.setQueryParameter('column_name', name);
        combobox_ds.setQueryParameter('tab_code', config_record.get('tab_code'));
        combobox_ds.setQueryParameter('layout_code', config_record.get('layout_code'));
        SETOBJECTPARA('COMBOBOX', combobox_ds, field, lov_cascade_para1, record);
        SETOBJECTPARA('COMBOBOX', combobox_ds, field, lov_cascade_para2, record);
        SETOBJECTPARA('COMBOBOX', combobox_ds, field, lov_cascade_para3, record);
        combobox_ds.query();
    }
    window['${/parameter/@bp_seq}${@layout_code}_on_cp_object_focus'](object,'${@tab_code}','${/parameter/@bp_seq}');
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SHOW_DOCUMENT_HISTORY'] = function(show_document_history_ds,base_ds){
    if(show_document_history_ds != null && base_ds != null){
        window['${@layout_code}_${@tab_code}_show_document_history_ds_load'] = function(history_ds){
            show_document_history_ds.un('load',window['${@layout_code}_${@tab_code}_show_document_history_ds_load']);
            var history_records = history_ds.getAll();
            var base_records = base_ds.getAll();
            for(var i = 0; i < base_records.length; i++){
                var base_record = base_records[i];
                var row_add_flag = true;
                for(var j = 0; j < history_records.length; j++){
                    var  history_record = history_records[j];
                    if(base_record.get('${@base_table_pk}'.toLowerCase()) == history_record.get('${@base_table_pk}'.toLowerCase())){
                        row_add_flag = false;
                        for(var v in base_record.data){
                            var old_val = base_record.data[v];
                            var new_val = history_record.data[v];
                            if(old_val instanceof Date){
                                old_val = old_val.getTime();
                                new_val = (new Date(new_val)).getTime();
                            }
                            if(old_val != new_val){
                                var grid_id  = '${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_layout_grid_id';
                                if($(grid_id).findColByName(v.toLowerCase())){
                                    base_record.getField(v).setPropertity('tooltip', history_record.data[v]);
                                    Ext.get(grid_id).select('tr[_row='+base_record.id+'] td[dataindex=' + v.toLowerCase() + ']').setStyle({
                                        background:'#FF9965'
                                    });
                                }
                            }
                        }
                    }
                }
                if(row_add_flag){
                    var grid_id  = '${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_layout_grid_id';
                    Ext.get(grid_id).select('tr[_row='+base_record.id+']').setStyle({
                        background:'#FF9965'
                    });
                }
            }
        };
        show_document_history_ds.on('load',window['${@layout_code}_${@tab_code}_show_document_history_ds_load']);
        show_document_history_ds.query();
    }
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SHOW_HISTORY']=function(show_history_ds,base_ds){
	if('${/parameter/@show_history_flag}' == 'Y'&&base_ds.getAll().length){
		var records=base_ds.getAll();
		for(var i=0;i<records.length;i++){
			var record=records[i];
			Leaf.request({
				url:'${/request/@context_path}/autocrud/layout.server_doc_layout_show_history/query',
				para:{
					table_name:'${@base_table}'||'ERROR',
					table_pk_value:record.get('${@base_table_pk}'.toLowerCase()),
					layout_code:'${@layout_code}',
					tab_code:'${@tab_code}'
				},
				success:function(res){
					var current_base_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_ds');
					var current_records= current_base_ds.getAll();
					for(var j=0;j<current_records.length;j++){
						var current_record = current_records[j];
						if(res.result && res.result.record && res.result.record.length){
						   for(var i=0;i<res.result.record.length;i++){
						   	  var history_record = res.result.record[i];
						   	  if(current_record.get('${@base_table_pk}'.toLowerCase())==history_record['table_pk_value']){
						   	  	 for(var name in current_record.data){
						   	  	 	if(GET_CONFIG_COLUMN_NAME(name).toUpperCase()==history_record['column_name']){
						   	  	 		var grid_id  = '${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_layout_grid_id';
										if($(grid_id).findColByName(name.toLowerCase())){
											current_record.getField(name).setPropertity('tooltip', history_record['from_value']);
											Ext.get(grid_id).select('tr[_row='+current_record.id+'] td[dataindex=' + name.toLowerCase() + ']').setStyle({
							                    background:'#FF9965'
							                });
						                }
						                continue;
						   	  	 	}
						   	  	 }
						   	  }
						   }
						}
					}
				},
				scope:this
			});
		}
	}
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_CHILD_ONREADY'] = function() {
    window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_initFlag'] = false;
    if('${@base_table}'&&'${@parent_table}'&&'${@query_source}'){
	    var base_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_ds');
	    var parent_ds = $('${@repeat_bp_seq}${@layout_code}_${@parent_table_tab_code}_${@parent_table}_ds');
	    
	    function base_ds_load(ds){
	    	base_ds.un('load',base_ds_load);
	    	if('${/parameter/@show_history_flag}' == 'Y'){
		    	var show_history_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_show_history_ds');
	        	window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SHOW_HISTORY'](show_history_ds,base_ds);
        	}
            if('${/parameter/@show_document_history_flag}'=='Y'){
                var show_document_history_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_show_document_history_ds');
                window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SHOW_DOCUMENT_HISTORY'](show_document_history_ds,ds);
            }
	    }
	    
	   	function base_ds_query(){
	   		base_ds.setQueryParameter('${@parent_base_table_pk}', parent_ds.getCurrentRecord().get('${@parent_base_table_pk}'));
	        base_ds.on('load',base_ds_load);
            base_ds.query();
	   	}
	    parent_ds.on('indexchange', function(ds,record) {
            if(!record.isNew&&window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_initFlag']){
	        	base_ds_query();
            }else{
                window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_initFlag'] = true;
            }
	    });
	    if(parent_ds.getAll().length && parent_ds.getCurrentRecord() && !parent_ds.getCurrentRecord().isNew){
	    	base_ds_query();
	    }
    }
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ONREADY'] = function() {
    var base_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_ds');
    function base_ds_load(ds){
    	base_ds.un('load',base_ds_load);
    	if('${/parameter/@show_history_flag}' == 'Y'){
	    	var show_history_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_show_history_ds');
	    	window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SHOW_HISTORY'](show_history_ds,base_ds);
    	}
        if('${/parameter/@show_document_history_flag}'=='Y'){
            var show_document_history_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_show_document_history_ds');
            window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SHOW_DOCUMENT_HISTORY'](show_document_history_ds,ds);
        }
    }
    if('${@auto_query}'!='N'){
	    base_ds.on('load',base_ds_load);
	    base_ds.query();
    }
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_BEFORECREATE'] = function(ds) {
    var line_record = ds.getCurrentRecord();
    var config_records = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').getAll();
    var result;
    if(window['${@layout_code}_on_layout_dynamic_grid_beforecreate']) {
        result = window['${@layout_code}_on_layout_dynamic_grid_beforecreate'](ds, line_record, config_records, '${/parameter/@bp_seq}');
    }
    return result == null ? true:result;
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_ADD'] = function(ds) {
    var line_record = ds.getCurrentRecord(),
        parent_table_tab_code = '${@parent_table_tab_code}',
        parent_table = '${@parent_table}',
        parent_base_table_pk = '${@parent_base_table_pk}';
    var config_records = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').getAll();
	var parent_ds_id = '${@repeat_bp_seq}${@layout_code}_'+ parent_table_tab_code + '_' + parent_table + '_ds';
	var head_record = '';
    if(parent_table && $L.CmpManager.get(parent_ds_id)){
	    head_record = $(parent_ds_id).getCurrentRecord();
	    if (head_record&&head_record.get(parent_base_table_pk)) {
	        line_record.set(parent_base_table_pk, head_record.get(parent_base_table_pk));
	        if ('${@base_table}'.toUpperCase() == 'PRJ_QUOTATION') {
	            line_record.set('document_id', head_record.get(parent_base_table_pk));
	        }
	    }
    }
    if(!line_record.get('document_category')){
    	line_record.set('document_category', '${/parameter/@document_category}');
    }
    line_record.set('bp_seq', '${/parameter/@bp_seq}');
    for (var i = 0;i < config_records.length;i++) {
        var config_record = config_records[i],
            validation_type = config_record.get('validation_type'),
            column_name = config_record.get('column_name'),
            display_name = config_record.get('column_name') + '_n';
        if (head_record && config_record.get('copy_from_parent_tab') == 'Y') {
            line_record.set(column_name, head_record.get(column_name));
            line_record.set(display_name, head_record.get(display_name));
        }
        if (validation_type == 'LOV' || validation_type == 'LOV_C' || validation_type == 'TREE' || validation_type == 'TREE_C') {
            var documentMapping;
            if (config_record.get('lov_return_vcode') == 'Y') {
                documentMapping = [{
                    from: 'value_code',
                    to: column_name
                }, {
                    from: 'value_code',
                    to: column_name
                }];
                line_record.getField(column_name).setMapping(documentMapping);
            } else {
                documentMapping = [{
                    from: 'value_code',
                    to: column_name
                }, {
                    from: 'value_name',
                    to: display_name
                }];
                line_record.getField(display_name).setMapping(documentMapping);
            }
        } else if (validation_type == 'COMBOBOX' || validation_type == 'COMBOBOX_C') {
            var combobox_field;
            var combobox_documentmapping;
            if (config_record.get('lov_return_vcode') == 'Y') {
                combobox_field = line_record.getField(column_name);
                combobox_field.setPropertity('displayfield', 'value_code');
                line_record.getField(column_name).setMapping(combobox_documentmapping);
            } else {
                combobox_field = line_record.getField(display_name);
                combobox_field.setPropertity('displayfield', 'value_name');
                line_record.getField(display_name).setMapping(combobox_documentmapping);
            }
        }
    }
    window['${@layout_code}_on_layout_dynamic_grid_add'](ds, line_record , config_records,'${/parameter/@bp_seq}');
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_LOAD'] = function(ds) {
    var records = ds.getAll();
    var config_records = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').getAll();
    if (records.length) {
        for (var i = 0;i < records.length;i++) {
            var line_record = records[i];
            for (var j = 0;j < config_records.length;j++) {
                var config_record = config_records[j],
                    validation_type = config_record.get('validation_type'),
                    column_name = config_record.get('column_name'),
                    display_name = config_record.get('column_name') + '_n',
                    field_bak_flag = config_record.get('field_bak_flag');
                if (validation_type == 'LOV' || validation_type == 'LOV_C' || validation_type == 'TREE' || validation_type == 'TREE_C') {
                    var documentMapping;
                    if (config_record.get('lov_return_vcode') == 'Y') {
                        documentMapping = [{
                            from: 'value_code',
                            to: column_name
                        }, {
                            from: 'value_code',
                            to: column_name
                        }];
                        line_record.getField(column_name).setMapping(documentMapping);
                    } else {
                        documentMapping = [{
                            from: 'value_code',
                            to: column_name
                        }, {
                            from: 'value_name',
                            to: display_name
                        }];
                        line_record.getField(display_name).setMapping(documentMapping);
                    }
                } else if (validation_type == 'COMBOBOX' || validation_type == 'COMBOBOX_C') {
                    var combobox_field;
                    var combobox_documentmapping;
                    if (config_record.get('lov_return_vcode') == 'Y') {
                        combobox_field = line_record.getField(column_name);
                        combobox_field.setPropertity('displayfield', 'value_code');
                    } else {
                        combobox_field = line_record.getField(display_name);
                        combobox_field.setPropertity('displayfield', 'value_name');
                    }
                }
                if(field_bak_flag=='Y'){
		           var bak_name=column_name+'_bak';
		           line_record.set(bak_name,line_record.get(column_name)||'LAYOUT_FIELD_VALUE_INIT_NULL',true);
		        }
            }
            window['${@layout_code}_on_layout_dynamic_grid_load'](ds, line_record,config_records,'${/parameter/@bp_seq}');
        }
        if('${/parameter/@show_history_flag}'=='Y'){
	        var show_history_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_show_history_ds');
	    	window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SHOW_HISTORY'](show_history_ds,ds);
    	}
        if('${/parameter/@show_document_history_flag}'=='Y'){
            var show_document_history_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_${@base_table}_show_document_history_ds');
            window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_SHOW_DOCUMENT_HISTORY'](show_document_history_ds,ds);
        }
    }else{
    	window['${@layout_code}_on_layout_dynamic_grid_load'](ds, '',config_records,'${/parameter/@bp_seq}');
    }
};
window['${/parameter/@bp_seq}${/parameter/@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_INDEXCHANGE'] = function(ds,record) {
	var form_ds_id = '${/parameter/@bp_seq}${/parameter/@layout_code}_${@ref_tab_code}_${@base_table}_ds';
    if ($L.CmpManager.get(form_ds_id)) {
        var form_ds = $(form_ds_id);
        if (record.get('${@base_table_pk}'.toLowerCase())) {
            form_ds.setQueryParameter('${@base_table_pk}'.toLowerCase(), record.get('${@base_table_pk}'.toLowerCase()));
            form_ds.query();
        }
    }
    window['${@layout_code}_on_layout_dynamic_grid_indexchange'](ds,record,'${/parameter/@bp_seq}');
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_UPDATE'] = function(ds, record, name, value, old_value) {
    window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_CLEAR_LOVPARA'](ds, record, name, value, old_value);
    window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_FIELD_JAVASCRIPT'](ds, record, name, value, old_value);
    window['${@layout_code}_on_layout_dynamic_update'](ds, record, name, value, old_value,'${/parameter/@bp_seq}');
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_CLEAR_LOVPARA'] = function(ds, record, name, value, old_value) {
    if (Ext.isEmpty(value)) {
        var query_name = GET_CONFIG_COLUMN_NAME(name),
            field = record.getField(name),
            config_records = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds').getAll();
        var current_field_value;
        for (var i = 0;i < config_records.length;i++) {
            var config_record = config_records[i];
            var lov_cascade_para1 = config_record.get('lov_cascade_para1'),
                lov_cascade_para2 = config_record.get('lov_cascade_para2'),
                lov_cascade_para3 = config_record.get('lov_cascade_para3');
            SET_CLEAR_LOVPARA_EMPTY(query_name, lov_cascade_para1, record, config_record);
            SET_CLEAR_LOVPARA_EMPTY(query_name, lov_cascade_para2, record, config_record);
            SET_CLEAR_LOVPARA_EMPTY(query_name, lov_cascade_para3, record, config_record);
        }
        var current_field = record.getField(name),
            current_lovpara = current_field.get('lovpara');
        var current_loadpara_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_lov_getmapping_ds');

        function on_lov_getmapping_load(load_ds) {
            var lov_records = load_ds.getAll();
            for (var j = 0;j < lov_records.length;j++) {
                var lov_record = lov_records[j],
                    mapping = current_field.get('mapping'),
                    exists_flag = false,
                    lov_name = lov_record.data['name'].toLowerCase();
                if(mapping) {
                    for (var i = 0,
                             mapping_length = mapping.length; i < mapping_length; i++) {
                        if ((exists_flag = (lov_name == mapping[i]['from']))) {
                            break;
                        }
                    }
                    if (!exists_flag) {
                        record.set(lov_name, '');
                    }
                    current_field.setMapping(mapping);
                }
            }
            current_loadpara_ds.un('load', on_lov_getmapping_load);
            window['${/parameter/@bp_seq}${@layout_code}_unlock_layout_dynamic_window']();
        }
        for (var lov_para_name in current_lovpara) {
            current_loadpara_ds.setQueryParameter(lov_para_name, record.get(lov_para_name));
        }
        current_loadpara_ds.setQueryParameter('layout_code', '${@layout_code}');
        current_loadpara_ds.setQueryParameter('tab_code', '${@tab_code}');
        current_loadpara_ds.setQueryParameter('column_name', query_name);
        window['${/parameter/@bp_seq}${@layout_code}_lock_layout_dynamic_window']();
        current_loadpara_ds.on('load', on_lov_getmapping_load);
        current_loadpara_ds.query();
    }
    for (var show_name in record.data) {
        var show_field = record.getField(show_name);
        var lovpara_field = show_field.get('lovpara');
        if (lovpara_field && lovpara_field[name]) {
            record.set(show_name, '');
            var save_name = GET_CONFIG_COLUMN_NAME(show_name);
            if (save_name != show_name) {
                record.set(save_name, '');
            }
        }
    }
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_FIELD_JAVASCRIPT'] = function(ds, record, name, value, old_value, fromLoad) {
    var config_ds = $('${/parameter/@bp_seq}${@layout_code}_${@tab_code}_con_layout_config_ds');
    var config_record = config_ds.find('column_name', name);
    var parent_record='';
    var layout_code = '${@layout_code}',
        tab_code = '${@tab_code}';
    if ('${@parent_table_tab_code}'&&'${@parent_table}') {
        parent_record = $('${@repeat_bp_seq}${@layout_code}_${@parent_table_tab_code}_${@parent_table}_ds').getAt(0);
    }
    if (config_record && config_record.get('field_javascript')) {
        eval(config_record.get('field_javascript'));
    }
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_QUERY'] = function(ds, qpara) {
    if('${@parent_table}'&&'${@parent_base_table_pk}'){
    	var parent_ds = $('${@repeat_bp_seq}${@layout_code}_${@parent_table_tab_code}_${@parent_table}_ds');
    	if(parent_ds.getCurrentRecord()){
    	   qpara['${@parent_base_table_pk}'] = parent_ds.getCurrentRecord().get('${@parent_base_table_pk}');
    	}
    }
    window['${@layout_code}_on_layout_dynamic_grid_query'](ds, qpara,'${/parameter/@bp_seq}');
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_SELECT'] = function(ds, record) {
    window['${@layout_code}_on_layout_dynamic_grid_select'](ds,record,'${/parameter/@bp_seq}');
};

window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_UNSELECT'] = function(ds, record) {
    window['${@layout_code}_on_layout_dynamic_grid_unselect'](ds,record,'${/parameter/@bp_seq}');
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_BEFORE_REMOVE'] = function(ds, record) {
    return window['${@layout_code}_on_layout_dynamic_grid_brfore_remove'](ds,record,'${/parameter/@bp_seq}');
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_GRID_REMOVE'] = function(ds, record) {
    window['${@layout_code}_on_layout_dynamic_grid_remove'](ds,record,'${/parameter/@bp_seq}');
};
window['${/parameter/@bp_seq}${@layout_code}_${@tab_code}_ON_LAYOUT_DYNAMIC_INNER_DOCUMENT_HISTORY_QUERY'] = function(ds,param) {
    window['${@layout_code}_on_layout_dynamic_document_history_query'](ds,param,'${@tab_code}');
}