package com.hand.hls.eas.dto;

/**Auto Generated By Hap Code Generator**/

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class HlsCusCredentialsData{

    private String sourceSYS;

    private String companyNumber;

    private String bookedDate;

    private String bizDate;


    private String periodYear;

    private String periodNumber;

    private String voucherType;

    private String attaches;


    private String description;

    private String voucherNumber;

    private String entrySeq;

    private String voucherAbstract;


    private String accountNumber;

    private String currencyNumber;

    private String localRate;

    private String entryDC;

//    @JsonIgnore
//    private String profitCenterNumber;

    private String originalAmount;

    private String qty;

    private String measurement;

    private String price;


    private String debitAmount;

    private String creditAmount;

    private String creator;

    private String auditor;


    private String poster;

    private String asstSeq;

    private String asstActType1;

    private String asstActNumber1;

    private String asstActName1;

    private String asstActType2;

    private String asstActNumber2;

    private String asstActName2;

    private String asstActType3;

    private String asstActNumber3;

    private String asstActName3;

    private String asstActType4;

    private String asstActNumber4;

    private String asstActName4;

//    @JsonIgnore
//    private String asstActType5;
//
//    @JsonIgnore
//    private String asstActNumber5;
//
//    @JsonIgnore
//    private String asstActName5;
//
//    @JsonIgnore
//    private String asstActType6;
//
//    @JsonIgnore
//    private String asstActNumber6;
//
//    @JsonIgnore
//    private String asstActName6;
//
//    @JsonIgnore
//    private String asstActType7;
//
//    @JsonIgnore
//    private String asstActNumber7;
//
//    @JsonIgnore
//    private String asstActName7;
//
//    @JsonIgnore
//    private String asstActType8;
//
//    @JsonIgnore
//    private String asstActNumber8;
//
//    @JsonIgnore
//    private String asstActName8;
//
//    @JsonIgnore
//    private String itemflag;
//
//    @JsonIgnore
//    private String oppAccountSeq;
//
//    @JsonIgnore
//    private String primaryItem;
//
//    @JsonIgnore
//    private String supplyItem;
//
//    @JsonIgnore
//    private Double cashflowAmountOriginal;
//
//    @JsonIgnore
//    private Double cashflowAmountLocal;
//
//    @JsonIgnore
//    private Double cashflowAmountRpt;
//
//    @JsonIgnore
//    private String cashAsstActType1;
//
//    @JsonIgnore
//    private String cashAsstActNumber1;
//
//    @JsonIgnore
//    private String cashAsstActName1;
//
//    @JsonIgnore
//    private String cashAsstActType2;
//
//    @JsonIgnore
//    private String cashAsstActNumber2;
//
//    @JsonIgnore
//    private String cashAsstActName2;
//
//    @JsonIgnore
//    private String cashAsstActType3;
//
//    @JsonIgnore
//    private String cashAsstActNumber3;
//
//    @JsonIgnore
//    private String cashAsstActName3;
//
//    @JsonIgnore
//    private String cashAsstActType4;
//
//    @JsonIgnore
//    private String cashAsstActNumber4;
//
//    @JsonIgnore
//    private String cashAsstActName4;
//
//    @JsonIgnore
//    private String cashAsstActType5;
//
//    @JsonIgnore
//    private String cashAsstActNumber5;
//
//    @JsonIgnore
//    private String cashAsstActName5;
//
//    @JsonIgnore
//    private String cashAsstActType6;
//
//    @JsonIgnore
//    private String cashAsstActNumber6;
//
//    @JsonIgnore
//    private String cashAsstActName6;
//
//    @JsonIgnore
//    private String cashAsstActType7;
//
//    @JsonIgnore
//    private String cashAsstActNumber7;
//
//    @JsonIgnore
//    private String cashAsstActName7;
//
//    @JsonIgnore
//    private String cashAsstActType8;
//
//    @JsonIgnore
//    private String cashAsstActNumber8;
//
//    @JsonIgnore
//    private String cashAsstActName8;

//    @JsonIgnore
//    private Long sessionId;
}
