package com.hand.hls.eas.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class HlsCusAccountAndContractData{

    private String contractNo;

    private String acctNum;

    private String date;

    private String accountNumber;

}
