package com.hand.hls.eas.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Setter
@Getter
public class HlsCusBankAccountPostData{

     private String number;

     private String name;

     private String bankAccountNumber;

     private String company;

     private String bank;

     private String InnerAcct;

     private String isByCurrency;

     private String currency;

     private String account;

     private String property;

     private String openDate;

     private String ctrlStrategy;

    private String classificatio;

    private String reference;

    private String description;

    private String simpleCode;

    private String isDefaultReck;

    private String isReckoning;

    private String isDCPay;

    private String isForEDrafOnly;

    private String isVirtualAcct;

    private String isSetBankInterface;

    private String isOnlyRead;

    private String bankInterfaceType;

    private String acctName;

    private String country;

    private String openArea;

    private String maxPayAmount;

    private String isMotherAccount;

    private String notOutPay;

    private String accountType;

    private String subaccount;


     }
