package com.hand.hls.prj.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Data;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@Data
@ExtensionAttribute(disable = true)
@Table(name = "HLS_BP_MASTER_EMPLOYEE")
public class BpMasterEmployee extends BaseDTO {

    public static final String FIELD_BP_EMPLOYEE_ID = "bpEmployeeId";
    public static final String FIELD_BP_ID = "bpId";
    public static final String FIELD_EMPLOYEE_ID = "employeeId";
    public static final String FIELD_UNIT_ID = "unitId";
    public static final String FIELD_PRIMARY_FLAG = "primaryFlag";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_NOTE = "note";


    @Id
    @GeneratedValue
    private Long bpEmployeeId;

    private Long bpId;

    private Long employeeId;

    private Long unitId;

    @Length(max = 1)
    private String primaryFlag;

    @Length(max = 1)
    private String enabledFlag;

    @Length(max = 4000)
    private String note;

    @Transient
    private String employeeIdN;

    @Transient
    private String unitIdN;

    @Transient
    private String mobile;
}
