package com.hand.hls.prj.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "prj_chance")
public class HlsCusPrjChance extends BaseDTO {
     @Id
     @GeneratedValue
     private Long chanceId; //项目ID

     @NotNull
     private Long companyId; //公司ID

     @Length(max = 100)
     private String documentType; //单据类型

     @Length(max = 100)
     private String documentCategory; //单据类别

     @Length(max = 100)
     private String businessType; //业务类型

     @NotEmpty
     @Length(max = 100)
     private String projectNumber; //项目编号

     @Length(max = 2000)
     private String projectName; //项目名称

     @Length(max = 100)
     private String projectStatus; //项目状态

     @Length(max = 100)
     private String leaseChannel; //商业模式

     @Length(max = 100)
     private String division; //产品线

     private Long employeeId; //业务员（用户id）

     private Long unitId; //部门id

     private Double financeAmount; //融资额

     private Date leaseStartDate;

     @Length(max = 255)
     private String financingPurpose;

     @Length(max = 255)
     private String currency;

     @Length(max = 4000)
     private String comprehensiveOpinion;

     @Length(max = 255)
     private String leaseItemType; //租赁物类型

     @Length(max = 1000)
     private String authorityRuleString;

     private Double debtAmount; //或有负债金额

     private Long tenantId; //承租人ID

     private Double creditAmount; //拟授信额度/授信额度/项目额度

     private Long projectAssistant; //协办项目经理(员工ID)

     private Long projectAssistantAssignsId;

     private Double assetLiabilityRatio;//资产负债率

     private Double totalAssets;//总资产

     private String customerIncomeStructure;//客户收入结构

     private String finStatementDate;//最新财报日期

     private Long refProjectId;

     @Length(max = 1000)
     private String usedCashFlow; //授信资金用途及流向

     @Length(max = 1000)
     private String cashFlowAnalyse; //还款来源及未来现金流分析

     @Length(max = 1000)
     private String prjAdvantage; //项目优势、风险及发展前景

     @Length(max = 1000)
     private String otherDescription;

     @Length(max = 255)
     private String location;

     @Transient
     private String projectStatusDesc;//立项状态描述

     @Transient
     private String businessTypeDesc;//业务类型描述

     @Transient
     private String divisionDesc;//产品线描述

     @Transient
     private  String documentTypeDesc;//单据类型描述

     @Transient
     private String leaseChannelDesc;//商业模式描述

     @Transient
     private String bpName;//承租人名称

     @Transient
     private Long userId;//用户ID

    @Transient
    private String params;//查询参数

     @Transient
     private String projectAssistantName;//协办项目经理

    @Transient
    private String projectManager;//主办项目经理



     public void setChanceId(Long chanceId){
         this.chanceId = chanceId;
     }

     public Long getChanceId(){
         return chanceId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setDocumentType(String documentType){
         this.documentType = documentType;
     }

     public String getDocumentType(){
         return documentType;
     }

     public void setDocumentCategory(String documentCategory){
         this.documentCategory = documentCategory;
     }

     public String getDocumentCategory(){
         return documentCategory;
     }

     public void setBusinessType(String businessType){
         this.businessType = businessType;
     }

     public String getBusinessType(){
         return businessType;
     }

     public void setProjectNumber(String projectNumber){
         this.projectNumber = projectNumber;
     }

     public String getProjectNumber(){
         return projectNumber;
     }

     public void setProjectName(String projectName){
         this.projectName = projectName;
     }

     public String getProjectName(){
         return projectName;
     }

     public void setProjectStatus(String projectStatus){
         this.projectStatus = projectStatus;
     }

     public String getProjectStatus(){
         return projectStatus;
     }

     public void setLeaseChannel(String leaseChannel){
         this.leaseChannel = leaseChannel;
     }

     public String getLeaseChannel(){
         return leaseChannel;
     }

     public void setDivision(String division){
         this.division = division;
     }

     public String getDivision(){
         return division;
     }

     public void setEmployeeId(Long employeeId){
         this.employeeId = employeeId;
     }

     public Long getEmployeeId(){
         return employeeId;
     }

     public void setUnitId(Long unitId){
         this.unitId = unitId;
     }

     public Long getUnitId(){
         return unitId;
     }

     public void setFinanceAmount(Double financeAmount){
         this.financeAmount = financeAmount;
     }

     public Double getFinanceAmount(){
         return financeAmount;
     }

     public void setLeaseStartDate(Date leaseStartDate){
         this.leaseStartDate = leaseStartDate;
     }

     public Date getLeaseStartDate(){
         return leaseStartDate;
     }

     public void setFinancingPurpose(String financingPurpose){
         this.financingPurpose = financingPurpose;
     }

     public String getFinancingPurpose(){
         return financingPurpose;
     }

     public void setCurrency(String currency){
         this.currency = currency;
     }

     public String getCurrency(){
         return currency;
     }

     public void setComprehensiveOpinion(String comprehensiveOpinion){
         this.comprehensiveOpinion = comprehensiveOpinion;
     }

     public String getComprehensiveOpinion(){
         return comprehensiveOpinion;
     }

     public void setLeaseItemType(String leaseItemType){
         this.leaseItemType = leaseItemType;
     }

     public String getLeaseItemType(){
         return leaseItemType;
     }

     public void setAuthorityRuleString(String authorityRuleString){
         this.authorityRuleString = authorityRuleString;
     }

     public String getAuthorityRuleString(){
         return authorityRuleString;
     }

     public void setDebtAmount(Double debtAmount){
         this.debtAmount = debtAmount;
     }

     public Double getDebtAmount(){
         return debtAmount;
     }

     public void setTenantId(Long tenantId){
         this.tenantId = tenantId;
     }

     public Long getTenantId(){
         return tenantId;
     }

     public void setCreditAmount(Double creditAmount){
         this.creditAmount = creditAmount;
     }

     public Double getCreditAmount(){
         return creditAmount;
     }

     public void setProjectAssistant(Long projectAssistant){
         this.projectAssistant = projectAssistant;
     }

     public Long getProjectAssistant(){
         return projectAssistant;
     }

     public void setProjectAssistantAssignsId(Long projectAssistantAssignsId){
         this.projectAssistantAssignsId = projectAssistantAssignsId;
     }

     public Long getProjectAssistantAssignsId(){
         return projectAssistantAssignsId;
     }

     public void setUsedCashFlow(String usedCashFlow){
         this.usedCashFlow = usedCashFlow;
     }

     public String getUsedCashFlow(){
         return usedCashFlow;
     }

     public void setCashFlowAnalyse(String cashFlowAnalyse){
         this.cashFlowAnalyse = cashFlowAnalyse;
     }

     public String getCashFlowAnalyse(){
         return cashFlowAnalyse;
     }

     public void setPrjAdvantage(String prjAdvantage){
         this.prjAdvantage = prjAdvantage;
     }

     public String getPrjAdvantage(){
         return prjAdvantage;
     }

     public void setOtherDescription(String otherDescription){
         this.otherDescription = otherDescription;
     }

     public String getOtherDescription(){
         return otherDescription;
     }

     public void setLocation(String location){
         this.location = location;
     }

     public String getLocation(){
         return location;
     }

    public String getProjectStatusDesc() {
        return projectStatusDesc;
    }

    public void setProjectStatusDesc(String projectStatusDesc) {
        this.projectStatusDesc = projectStatusDesc;
    }

    public String getBusinessTypeDesc() {
        return businessTypeDesc;
    }

    public void setBusinessTypeDesc(String businessTypeDesc) {
        this.businessTypeDesc = businessTypeDesc;
    }

    public String getDivisionDesc() {
        return divisionDesc;
    }

    public void setDivisionDesc(String divisionDesc) {
        this.divisionDesc = divisionDesc;
    }

    public String getDocumentTypeDesc() {
        return documentTypeDesc;
    }

    public void setDocumentTypeDesc(String documentTypeDesc) {
        this.documentTypeDesc = documentTypeDesc;
    }

    public String getLeaseChannelDesc() {
        return leaseChannelDesc;
    }

    public void setLeaseChannelDesc(String leaseChannelDesc) {
        this.leaseChannelDesc = leaseChannelDesc;
    }

    public String getBpName() {
        return bpName;
    }

    public void setBpName(String bpName) {
        this.bpName = bpName;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public String getProjectAssistantName() {
        return projectAssistantName;
    }

    public void setProjectAssistantName(String projectAssistantName) {
        this.projectAssistantName = projectAssistantName;
    }

    public String getProjectManager() {
        return projectManager;
    }

    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager;
    }

    public Double getAssetLiabilityRatio() {
        return assetLiabilityRatio;
    }

    public void setAssetLiabilityRatio(Double assetLiabilityRatio) {
        this.assetLiabilityRatio = assetLiabilityRatio;
    }

    public Double getTotalAssets() {
        return totalAssets;
    }

    public void setTotalAssets(Double totalAssets) {
        this.totalAssets = totalAssets;
    }

    public String getCustomerIncomeStructure() {
        return customerIncomeStructure;
    }

    public void setCustomerIncomeStructure(String customerIncomeStructure) {
        this.customerIncomeStructure = customerIncomeStructure;
    }

    public String getFinStatementDate() {
        return finStatementDate;
    }

    public void setFinStatementDate(String finStatementDate) {
        this.finStatementDate = finStatementDate;
    }

    public Long getRefProjectId() {
        return refProjectId;
    }

    public void setRefProjectId(Long refProjectId) {
        this.refProjectId = refProjectId;
    }
}
