package com.hand.hls.prj.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Data;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "PRJ_PROJECT_CONDITION")
@Data
public class HlsCusPrjProjectCondition extends BaseDTO {

     public static final String FIELD_CONDITION_ID = "conditionId";
     public static final String FIELD_PROJECT_ID = "projectId";
     public static final String FIELD_CONTENT = "content";
     public static final String FIELD_STAGE = "stage";


     @Id
     @GeneratedValue
     private Long conditionId;

     private Long projectId;

     @Length(max = 1024)
     private String content;

     @Length(max = 64)
     private String stage;



     }
