package com.hand.hls.prj.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@ExtensionAttribute(disable = true)
@Table(name = "PRJ_PROJECT_WFL_QUESTION")
public class HlsCusProjectWflQuestion extends BaseDTO {

    public static final String FIELD_QUESTION_ID = "questionId";
    public static final String FIELD_QUESTION_SEQ = "questionSeq";
    public static final String FIELD_QUESTION_COMMENTS = "questionComments";
    public static final String FIELD_QUESTION_CREATED_BY = "questionCreatedBy";
    public static final String FIELD_QUESTION_ANSWER = "questionAnswer";
    public static final String FIELD_QUESTION_ANSWERED_BY = "questionAnsweredBy";


    @Id
    @GeneratedValue
    private Long questionId;

    private Long questionSeq;

    @Length(max = 2000)
    private String questionComments;

    private Long questionCreatedBy;

    @Length(max = 2000)
    private String questionAnswer;

    @Length(max = 2000)
    private String questionAnsweredBy;

    private Long projectId;

    @Transient
    private String questionCreatedByN;

    @Transient
    private String questionAnsweredByN;

    @Transient
    private String questionFileExistFlag;

    @Transient
    private String answerFileExistFlag;
    @Transient
    private String questionFileName;
    @Transient
    private String answerFileName;
    @Transient
    private String questionFileDate;
    @Transient
    private String answerFileDate;

    private String questionType;


    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setQuestionSeq(Long questionSeq) {
        this.questionSeq = questionSeq;
    }

    public Long getQuestionSeq() {
        return questionSeq;
    }

    public void setQuestionComments(String questionComments) {
        this.questionComments = questionComments;
    }

    public String getQuestionComments() {
        return questionComments;
    }

    public void setQuestionCreatedBy(Long questionCreatedBy) {
        this.questionCreatedBy = questionCreatedBy;
    }

    public Long getQuestionCreatedBy() {
        return questionCreatedBy;
    }

    public void setQuestionAnswer(String questionAnswer) {
        this.questionAnswer = questionAnswer;
    }

    public String getQuestionAnswer() {
        return questionAnswer;
    }

    public void setQuestionAnsweredBy(String questionAnsweredBy) {
        this.questionAnsweredBy = questionAnsweredBy;
    }

    public String getQuestionAnsweredBy() {
        return questionAnsweredBy;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public String getQuestionCreatedByN() {
        return questionCreatedByN;
    }

    public void setQuestionCreatedByN(String questionCreatedByN) {
        this.questionCreatedByN = questionCreatedByN;
    }

    public String getQuestionAnsweredByN() {
        return questionAnsweredByN;
    }

    public void setQuestionAnsweredByN(String questionAnsweredByN) {
        this.questionAnsweredByN = questionAnsweredByN;
    }

    public String getQuestionFileExistFlag() {
        return questionFileExistFlag;
    }

    public void setQuestionFileExistFlag(String questionFileExistFlag) {
        this.questionFileExistFlag = questionFileExistFlag;
    }

    public String getAnswerFileExistFlag() {
        return answerFileExistFlag;
    }

    public void setAnswerFileExistFlag(String answerFileExistFlag) {
        this.answerFileExistFlag = answerFileExistFlag;
    }

    public String getQuestionFileName() {
        return questionFileName;
    }

    public void setQuestionFileName(String questionFileName) {
        this.questionFileName = questionFileName;
    }

    public String getAnswerFileName() {
        return answerFileName;
    }

    public void setAnswerFileName(String answerFileName) {
        this.answerFileName = answerFileName;
    }

    public String getQuestionFileDate() {
        return questionFileDate;
    }

    public void setQuestionFileDate(String questionFileDate) {
        this.questionFileDate = questionFileDate;
    }

    public String getAnswerFileDate() {
        return answerFileDate;
    }

    public void setAnswerFileDate(String answerFileDate) {
        this.answerFileDate = answerFileDate;
    }

    public String getQuestionType() {
        return questionType;
    }

    public void setQuestionType(String questionType) {
        this.questionType = questionType;
    }
}
