package com.hand.hls.prj.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Data;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "prj_project_mail_info")
@Data
public class HlsCusPrjProjectMailInfo extends BaseDTO {

     public static final String FIELD_MAIL_ID = "mailId";
     public static final String FIELD_PROJECT_ID = "projectId";
     public static final String FIELD_ADDRESSEE = "addressee";
     public static final String FIELD_PHONE = "phone";
     public static final String FIELD_TO_ADDRESS = "toAddress";
     public static final String FIELD_EXPRESS_NAME = "expressName";
     public static final String FIELD_EXPRESS_NUMBER = "expressNumber";
     public static final String FIELD_DESCRIPTION = "description";


     @Id
     @GeneratedValue
     private Long mailId;

     @NotNull
     private Long projectId; //虚拟合同ID

     @Length(max = 200)
     private String addressee; //收件人

     @Length(max = 200)
     private String phone; //电话

     @Length(max = 2000)
     private String toAddress; //寄送地址

     @Length(max = 200)
     private String expressName; //快递名称

     @Length(max = 200)
     private String expressNumber; //寄送快递单号

     @Length(max = 2000)
     private String description; //描述/备注

}
