package com.hand.hls.prj.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "prj_quotation_cashflow_h")
public class HlsCusPrjQuotationCashflowH extends BaseDTO {
    @Id
    @GeneratedValue
    private Long quotationCashflowId; //现金流ID

    @NotNull
    private Long quotationId; //项目报价ID

    private Long cfItem; //现金流项目

    private Long cfType; //现金流类型

    @Length(max = 100)
    private String cfDirection; //现金流方向（INFLOW/OUTFLOW）

    @Length(max = 100)
    private String cfStatus; //现金流状态（BLOCK/冻结 、RELEASE/下达、CANCEL/取消） （syscode：HLS.CASHFLOW_STATUS）

    private Long times; //期数

    private Date dueDate; //支付日/到期日

    private Date calcDate;//计算日期

    private Date finIncomeDate; //收入确认日

    private Double dueAmount; //应收金额 租金

    private Double netDueAmount; //不含税应收金额

    private Double vatDueAmount; //增值税额

    private Double principal; //应收本金

    private Double netPrincipal; //不含税应收本金

    private Double vatPrincipal; //本金增值税额

    private Double interest; //应收利息

    private Double netInterest; //不含税应收利息

    private Double vatInterest; //利息增值税额

    private Double outstandingRental; //当期剩余租金

    private Double outstandingPrincipal; //当期剩余本金

    private Double outstandingInterest; //当期剩余利息

    private Double interestAccrualBalance; //当期计息余额

    private Double accumulatedUnpaidInterest; //累计未偿还利息

    private Double writeOffAmount; //核销金额

    private Double writeOffDays; //罚息天数

    private String writeOffStatus;//核销状态

    private Double changeFineAmount;//调整后罚金

    private String reductionType;//减免类型

    private String description;//说明

    private Double billingVatRate;//开票利率


    private Double cashflowIrr; //净现金流
    private Double cashflowIrrAfterTax; //净现金流（不含税）
    private Double cashflowIrrWithoutFee; //净现金流（不含费用）
    private Double vatTotal; //支付增值税
    private String cashflowName;//款项名称
    private String calcWay;//计算方式(分段报价计算方式)
    private Date planDueDate;


    private Long subsectionId; //分段报价主键

    public Long getQuotationCashflowId() {
        return quotationCashflowId;
    }

    public void setQuotationCashflowId(Long quotationCashflowId) {
        this.quotationCashflowId = quotationCashflowId;
    }

    public Long getQuotationId() {
        return quotationId;
    }

    public void setQuotationId(Long quotationId) {
        this.quotationId = quotationId;
    }

    public Long getCfItem() {
        return cfItem;
    }

    public void setCfItem(Long cfItem) {
        this.cfItem = cfItem;
    }

    public Long getCfType() {
        return cfType;
    }

    public void setCfType(Long cfType) {
        this.cfType = cfType;
    }

    public String getCfDirection() {
        return cfDirection;
    }

    public void setCfDirection(String cfDirection) {
        this.cfDirection = cfDirection;
    }

    public String getCfStatus() {
        return cfStatus;
    }

    public void setCfStatus(String cfStatus) {
        this.cfStatus = cfStatus;
    }

    public Long getTimes() {
        return times;
    }

    public void setTimes(Long times) {
        this.times = times;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public Date getCalcDate() {
        return calcDate;
    }

    public void setCalcDate(Date calcDate) {
        this.calcDate = calcDate;
    }

    public Date getFinIncomeDate() {
        return finIncomeDate;
    }

    public void setFinIncomeDate(Date finIncomeDate) {
        this.finIncomeDate = finIncomeDate;
    }

    public Double getDueAmount() {
        return dueAmount;
    }

    public void setDueAmount(Double dueAmount) {
        this.dueAmount = dueAmount;
    }

    public Double getNetDueAmount() {
        return netDueAmount;
    }

    public void setNetDueAmount(Double netDueAmount) {
        this.netDueAmount = netDueAmount;
    }

    public Double getVatDueAmount() {
        return vatDueAmount;
    }

    public void setVatDueAmount(Double vatDueAmount) {
        this.vatDueAmount = vatDueAmount;
    }

    public Double getPrincipal() {
        return principal;
    }

    public void setPrincipal(Double principal) {
        this.principal = principal;
    }

    public Double getNetPrincipal() {
        return netPrincipal;
    }

    public void setNetPrincipal(Double netPrincipal) {
        this.netPrincipal = netPrincipal;
    }

    public Double getVatPrincipal() {
        return vatPrincipal;
    }

    public void setVatPrincipal(Double vatPrincipal) {
        this.vatPrincipal = vatPrincipal;
    }

    public Double getInterest() {
        return interest;
    }

    public void setInterest(Double interest) {
        this.interest = interest;
    }

    public Double getNetInterest() {
        return netInterest;
    }

    public void setNetInterest(Double netInterest) {
        this.netInterest = netInterest;
    }

    public Double getVatInterest() {
        return vatInterest;
    }

    public void setVatInterest(Double vatInterest) {
        this.vatInterest = vatInterest;
    }

    public Double getOutstandingRental() {
        return outstandingRental;
    }

    public void setOutstandingRental(Double outstandingRental) {
        this.outstandingRental = outstandingRental;
    }

    public Double getOutstandingPrincipal() {
        return outstandingPrincipal;
    }

    public void setOutstandingPrincipal(Double outstandingPrincipal) {
        this.outstandingPrincipal = outstandingPrincipal;
    }

    public Double getOutstandingInterest() {
        return outstandingInterest;
    }

    public void setOutstandingInterest(Double outstandingInterest) {
        this.outstandingInterest = outstandingInterest;
    }

    public Double getInterestAccrualBalance() {
        return interestAccrualBalance;
    }

    public void setInterestAccrualBalance(Double interestAccrualBalance) {
        this.interestAccrualBalance = interestAccrualBalance;
    }

    public Double getAccumulatedUnpaidInterest() {
        return accumulatedUnpaidInterest;
    }

    public void setAccumulatedUnpaidInterest(Double accumulatedUnpaidInterest) {
        this.accumulatedUnpaidInterest = accumulatedUnpaidInterest;
    }

    public Double getWriteOffAmount() {
        return writeOffAmount;
    }

    public void setWriteOffAmount(Double writeOffAmount) {
        this.writeOffAmount = writeOffAmount;
    }

    public Double getWriteOffDays() {
        return writeOffDays;
    }

    public void setWriteOffDays(Double writeOffDays) {
        this.writeOffDays = writeOffDays;
    }

    public String getWriteOffStatus() {
        return writeOffStatus;
    }

    public void setWriteOffStatus(String writeOffStatus) {
        this.writeOffStatus = writeOffStatus;
    }

    public Double getChangeFineAmount() {
        return changeFineAmount;
    }

    public void setChangeFineAmount(Double changeFineAmount) {
        this.changeFineAmount = changeFineAmount;
    }

    public String getReductionType() {
        return reductionType;
    }

    public void setReductionType(String reductionType) {
        this.reductionType = reductionType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getBillingVatRate() {
        return billingVatRate;
    }

    public void setBillingVatRate(Double billingVatRate) {
        this.billingVatRate = billingVatRate;
    }

    public Double getCashflowIrr() {
        return cashflowIrr;
    }

    public void setCashflowIrr(Double cashflowIrr) {
        this.cashflowIrr = cashflowIrr;
    }

    public Double getCashflowIrrAfterTax() {
        return cashflowIrrAfterTax;
    }

    public void setCashflowIrrAfterTax(Double cashflowIrrAfterTax) {
        this.cashflowIrrAfterTax = cashflowIrrAfterTax;
    }

    public Double getCashflowIrrWithoutFee() {
        return cashflowIrrWithoutFee;
    }

    public void setCashflowIrrWithoutFee(Double cashflowIrrWithoutFee) {
        this.cashflowIrrWithoutFee = cashflowIrrWithoutFee;
    }

    public Double getVatTotal() {
        return vatTotal;
    }

    public void setVatTotal(Double vatTotal) {
        this.vatTotal = vatTotal;
    }

    public String getCashflowName() {
        return cashflowName;
    }

    public void setCashflowName(String cashflowName) {
        this.cashflowName = cashflowName;
    }


    public Long getSubsectionId() {
        return subsectionId;
    }

    public void setSubsectionId(Long subsectionId) {
        this.subsectionId = subsectionId;
    }
    public String getCalcWay() {
        return calcWay;
    }

    public void setCalcWay(String calcWay) {
        this.calcWay = calcWay;
    }

    public Date getPlanDueDate() {
        return planDueDate;
    }

    public void setPlanDueDate(Date planDueDate) {
        this.planDueDate = planDueDate;
    }
}
