package com.hand.hls.prj.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "prj_project_attachment")
public class HlsCusPrjProjectAttachment extends BaseDTO {

    public static final String FIELD_PROJECT_ATTACHMENT_ID = "projectAttachmentId";
    public static final String FIELD_CHANGE_ID = "chanceId";
    public static final String FIELD_PROJECT_ID = "projectId";
    public static final String FIELD_PROJECT_ATTACHMENT_CATEGORY = "projectAttachmentCategory";
    public static final String FIELD_DOCUMENT_NAME = "documentName";
    public static final String FIELD_DESCRIPTION = "description";


    @Id
    @GeneratedValue
    private Long projectAttachmentId; //项目附件ID

    @NotNull
    private Long projectId; //项目ID

    @NotEmpty
    @Length(max = 200)
    private String projectAttachmentCategory; //项目附件类别

    @Length(max = 2000)
    private String documentName; //文档名称

    @Length(max = 2000)
    private String description; //说明备注

    private Long sourceId;

    private String wflUpload;

    private String isFinalPrint;//是否最终用印

    private String copies;//份数

    private String stampName;//印章名称

    private String companySeal;//申请公章

    private String repSeal;//申请法人章

    private String printComment;//用印意见

    /**
     * 附件编码
     */
    private String attachmentCode;

    /**
     * 序号
     */
    private Long orderNumber;

    private Long serialNumberT;

    private Date timeT;

    private String adressT;

    private String businessParty;

    private String litigantT;

    private String dueContent;

    private Long photoT;

    private String leaseItem;

    private String capitalItem;

    private String limitsT;

    private String checkContent;

    private String subjectSubject;

    private String spotChecking;

    @Transient
    private String spotCheckingN;

    private String checkResult;

    @Transient
    private String photocopyingN;

    private String photocopying;

    private String tenantSignFlag;

    @Transient
    private Long fundingPlanId;
    @Transient
    private Long tenantId;
    @Transient
    private String fileNumber;
    @Transient
    private String fileNum;
    @Transient
    private Date creationDate;
    @Transient
    private String attachmentId;
    @Transient
    private Long attachmentIdList;

    @Transient
    private String editableFlag;

    public String getEditableFlag() {
        return editableFlag;
    }

    public void setEditableFlag(String editableFlag) {
        this.editableFlag = editableFlag;
    }

    private Long listDocumentId;
    public Long getListDocumentId() {
        return listDocumentId;
    }
    public void setListDocumentId(long listDocumentId) {
        this.listDocumentId = listDocumentId;
    }


    public Long getAttachmentIdList() {
        return attachmentIdList;
    }

    public void setAttachmentIdList(long attachmentIdList) {
        this.attachmentIdList = attachmentIdList;
    }



    public String getFileNumber() {
        return fileNumber;
    }

    public void setFileNumber(String fileNumber) {
        this.fileNumber = fileNumber;
    }

    public String getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getWflUpload() {
        return wflUpload;
    }

    public void setWflUpload(String wflUpload) {
        this.wflUpload = wflUpload;
    }

    public String getIsFinalPrint() {
        return isFinalPrint;
    }

    public void setIsFinalPrint(String isFinalPrint) {
        this.isFinalPrint = isFinalPrint;
    }

    public String getCopies() {
        return copies;
    }

    public void setCopies(String copies) {
        this.copies = copies;
    }

    public String getStampName() {
        return stampName;
    }

    public void setStampName(String stampName) {
        this.stampName = stampName;
    }

    public String getCompanySeal() {
        return companySeal;
    }

    public void setCompanySeal(String companySeal) {
        this.companySeal = companySeal;
    }

    public String getRepSeal() {
        return repSeal;
    }

    public void setRepSeal(String repSeal) {
        this.repSeal = repSeal;
    }

    public String getPrintComment() {
        return printComment;
    }

    public void setPrintComment(String printComment) {
        this.printComment = printComment;
    }

    public void setProjectAttachmentId(Long projectAttachmentId) {
        this.projectAttachmentId = projectAttachmentId;
    }

    public Long getProjectAttachmentId() {
        return projectAttachmentId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectAttachmentCategory(String projectAttachmentCategory) {
        this.projectAttachmentCategory = projectAttachmentCategory;
    }

    public String getProjectAttachmentCategory() {
        return projectAttachmentCategory;
    }

    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    public String getDocumentName() {
        return documentName;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public Long getSourceId() {
        return sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    @Transient
    private String fileName;
    @Transient
    private Long fileSize;

    @Transient
    private String filePath;
    @Transient
    private Date uploadDate;
    //上传人
    @Transient
    private String uploadPerson;
    @Transient
    private String sourceType;
    //是否是最新的
    @Transient
    private String updateStatus;

    @Transient
    private String fileNames;
    @Transient
    private String fileId;
    @Transient
    private String sourceKey;
    @Transient
    private String fileType;
    @Transient
    private String fileTypeCode;
    @Transient
    private String bpName;
    @Transient
    private String bpCategory;
    @Transient
    private String statusDesc;
    @Transient
    private String documentNumber;
    @Transient
    private String[] fileTypeArr;
    /**
     * 上传人id
     */
    @Transient
    private Long uploadPersonId;

    private String contractNumber;

    @Transient
    private Date signedDate;

    @Transient
    private String fileSuffix;

    @Transient
    private String[] fileIds;

    public String getFileNum() {
        return fileNum;
    }

    public void setFileNum(String fileNum) {
        this.fileNum = fileNum;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    public String getQueryFlag() {
        return queryFlag;
    }

    public void setQueryFlag(String queryFlag) {
        this.queryFlag = queryFlag;
    }

    public String getContractNumber() {
        return contractNumber;
    }

    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    public Date getSignedDate() {
        return signedDate;
    }

    public void setSignedDate(Date signedDate) {
        this.signedDate = signedDate;
    }

    @Transient
    private String queryFlag;

    public String getBpName() {
        return bpName;
    }

    public void setBpName(String bpName) {
        this.bpName = bpName;
    }

    public String getDocumentNumber() {
        return documentNumber;
    }

    public void setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber;
    }

    public String getFileNames() {
        return fileNames;
    }

    public void setFileNames(String fileNames) {
        this.fileNames = fileNames;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getSourceKey() {
        return sourceKey;
    }

    public void setSourceKey(String sourceKey) {
        this.sourceKey = sourceKey;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getUpdateStatus() {
        return updateStatus;
    }

    public void setUpdateStatus(String updateStatus) {
        this.updateStatus = updateStatus;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getUploadPerson() {
        return uploadPerson;
    }

    public void setUploadPerson(String uploadPerson) {
        this.uploadPerson = uploadPerson;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String[] getFileTypeArr() {
        return fileTypeArr;
    }

    public void setFileTypeArr(String[] fileTypeArr) {
        this.fileTypeArr = fileTypeArr;
    }

    public String getAttachmentCode() {
        return attachmentCode;
    }

    public void setAttachmentCode(String attachmentCode) {
        this.attachmentCode = attachmentCode;
    }

    public Long getUploadPersonId() {
        return uploadPersonId;
    }

    public void setUploadPersonId(Long uploadPersonId) {
        this.uploadPersonId = uploadPersonId;
    }

    public Long getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(Long orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getFileSuffix() {
        return fileSuffix;
    }

    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix;
    }

    public String[] getFileIds() {
        return fileIds;
    }

    public void setFileIds(String[] fileIds) {
        this.fileIds = fileIds;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Long getSerialNumberT() {
        return serialNumberT;
    }

    public void setSerialNumberT(Long serialNumberT) {
        this.serialNumberT = serialNumberT;
    }

    public Date getTimeT() {
        return timeT;
    }

    public void setTimeT(Date timeT) {
        this.timeT = timeT;
    }

    public String getAdressT() {
        return adressT;
    }

    public void setAdressT(String adressT) {
        this.adressT = adressT;
    }

    public String getBusinessParty() {
        return businessParty;
    }

    public void setBusinessParty(String businessParty) {
        this.businessParty = businessParty;
    }

    public String getLitigantT() {
        return litigantT;
    }

    public void setLitigantT(String litigantT) {
        this.litigantT = litigantT;
    }

    public String getDueContent() {
        return dueContent;
    }

    public void setDueContent(String dueContent) {
        this.dueContent = dueContent;
    }

    public Long getPhotoT() {
        return photoT;
    }

    public void setPhotoT(Long photoT) {
        this.photoT = photoT;
    }

    public String getLeaseItem() {
        return leaseItem;
    }

    public void setLeaseItem(String leaseItem) {
        this.leaseItem = leaseItem;
    }

    public String getCapitalItem() {
        return capitalItem;
    }

    public void setCapitalItem(String capitalItem) {
        this.capitalItem = capitalItem;
    }

    public String getLimitsT() {
        return limitsT;
    }

    public void setLimitsT(String limitsT) {
        this.limitsT = limitsT;
    }

    public String getCheckContent() {
        return checkContent;
    }

    public void setCheckContent(String checkContent) {
        this.checkContent = checkContent;
    }

    public String getSubjectSubject() {
        return subjectSubject;
    }

    public void setSubjectSubject(String subjectSubject) {
        this.subjectSubject = subjectSubject;
    }

    public String getSpotChecking() {
        return spotChecking;
    }

    public void setSpotChecking(String spotChecking) {
        this.spotChecking = spotChecking;
    }

    public String getSpotCheckingN() {
        return spotCheckingN;
    }

    public void setSpotCheckingN(String spotCheckingN) {
        this.spotCheckingN = spotCheckingN;
    }

    public String getCheckResult() {
        return checkResult;
    }

    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult;
    }

    public String getPhotocopyingN() {
        return photocopyingN;
    }

    public void setPhotocopyingN(String photocopyingN) {
        this.photocopyingN = photocopyingN;
    }

    public String getPhotocopying() {
        return photocopying;
    }

    public void setPhotocopying(String photocopying) {
        this.photocopying = photocopying;
    }


    private String prjProjectType;

    public String getPrjProjectType() {
        return prjProjectType;
    }

    public void setPrjProjectType(String prjProjectType) {
        this.prjProjectType = prjProjectType;
    }

    public Long getFundingPlanId() {
        return fundingPlanId;
    }

    public void setFundingPlanId(Long fundingPlanId) {
        this.fundingPlanId = fundingPlanId;
    }

    public String getTenantSignFlag() {
        return tenantSignFlag;
    }

    public void setTenantSignFlag(String tenantSignFlag) {
        this.tenantSignFlag = tenantSignFlag;
    }

    public void setAttachmentIdList(Long attachmentIdList) {
        this.attachmentIdList = attachmentIdList;
    }

    public void setListDocumentId(Long listDocumentId) {
        this.listDocumentId = listDocumentId;
    }

    public String getFileTypeCode() {
        return fileTypeCode;
    }

    public void setFileTypeCode(String fileTypeCode) {
        this.fileTypeCode = fileTypeCode;
    }

    public String getBpCategory() {
        return bpCategory;
    }

    public void setBpCategory(String bpCategory) {
        this.bpCategory = bpCategory;
    }

    public String getStatusDesc() {
        return statusDesc;
    }

    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }
}
