package com.hand.hls.prj.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "PRJ_PROJECT_SURVIVE_REQUIRE")
public class HlsCusPrjSurviveRequire extends BaseDTO {

     public static final String FIELD_PRJ_SURVIVE_ID = "prjSurviveId";
     public static final String FIELD_PROJECT_ID = "projectId";
     public static final String FIELD_MANAGE_REQUIREMENTS = "manageRequirements";


     @Id
     @GeneratedValue
     private Long prjSurviveId;

     private Long projectId;

     @Length(max = 2000)
     private String manageRequirements;


     private Long refPrjSurviveId;

     @Transient
     private Long hisProjectId;

     @Transient
     private String hisManageRequirements;

    public String getHisManageRequirements() {
        return hisManageRequirements;
    }

    public void setHisManageRequirements(String hisManageRequirements) {
        this.hisManageRequirements = hisManageRequirements;
    }

    public Long getHisProjectId() {
        return hisProjectId;
    }

    public void setHisProjectId(Long hisProjectId) {
        this.hisProjectId = hisProjectId;
    }

    public Long getPrjSurviveId() {
        return prjSurviveId;
    }

    public void setPrjSurviveId(Long prjSurviveId) {
        this.prjSurviveId = prjSurviveId;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public void setManageRequirements(String manageRequirements){
         this.manageRequirements = manageRequirements;
     }

     public String getManageRequirements(){
         return manageRequirements;
     }

    public Long getRefPrjSurviveId() {
        return refPrjSurviveId;
    }

    public void setRefPrjSurviveId(Long refPrjSurviveId) {
        this.refPrjSurviveId = refPrjSurviveId;
    }
}
