package com.hand.hls.prj.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Column;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "prj_project")
@Setter
@Getter
public class HlsCusPrjProject extends PrjProject {
    @Transient
    private List<HlsCusPrjProjectLeaseItem> hlsCusPrjProjectLeaseItemList;

    @Transient
    private List<HlsCusPrjProjectBp> hlsCusPrjProjectBpList;

    private static final long serialVersionUID = 5233874842143415958L;
    @Transient
    private Long contractCount;

    private Long chanceId;//立项ID

    private Double debtAmount; //或有负债金额

    private Long tenantId; //承租人ID
    private Long sellerId; //出卖人ID
    private String suspendFlag;
    private Long finStatementHdId;
    private String usedNumberFlag;
    private String conApplicationStatus;
    private String conApplicationChangeStatus;
    private String guaranteeAnalyse;
    private String loanCondition;
    private String loanMethod;
    private String repaymentMethod;
    @Transient
    private String conApplicationStatusN;
    @Transient
    private String conApplicationChangeStatusN;
    @Transient
    private String templateCode;
    @Transient
    private String residualPriceType;
    @Transient
    private String residualPriceTypeN;
    @Transient
    private String annualPayTimesN;
    @Transient
    private String annualPayTimess;
    private Long bankAccountId;
    private String purchaseFrame;
    private String purchaseFrameName;
    private Double purchaseFrameAmount; //或有负债金额

    private String virtualAccount;
    private Long manufacturerId;
    private Long bpIdVender;
    private String signStatus;
    private Long factoryId;
    private String bpClass;

    private String leaseOrganization;

    private String signedFlag;
    private String preStatus;
    private String orderStatus;
    private String driverAndApplicant;
    private String investmentStatus;


    @Transient
    private String businessTypeValue;

    @Transient
    private String whetherLabelingN;
    @Transient
    private String purchaseFrameN;

    @Transient
    private String bankAccountIdN;
    @Transient
    private String tenantIdN;
    @Transient
    private String overdueStatusN;
    @Transient
    private String overdueStatus;
    @Transient
    private String overdueMaxDays;
    @Transient
    private Long overdueTimes;
    @Transient
    private Double overdueAmount;
    @Transient
    private Double overduePrincipalAmount;
    @Transient
    private Double overdueInterestAmount;
    @Transient
    private Double penaltyAmount;
    @Transient
    private Double actualPaymentAmount;
    @Transient
    private Long days;

    @Transient
    private Long projectIdHistory;//变更历史

    @Transient
    private String projectReqStatus; //变更申请审批状态

    private Double creditAmount; //拟授信额度/授信额度/项目额度

    @Length(max = 1000)
    private String usedCashFlow; //授信资金用途及流向

    @Length(max = 1000)
    private String cashFlowAnalyse; //还款来源及未来现金流分析

    @Length(max = 1000)
    private String prjAdvantage; //项目优势、风险及发展前景

    @Length(max = 1000)
    private String otherDescription; //其他情况说明

    private String location;//所在区域

    private String sumEvaluation;//总体评价

    private String subjectMatterIntrodution;//标的物介绍

    private String dataClass;//正常项目/虚拟合同

    private Long refProjectId;//虚拟合同指向项目ID

    private String contractStatus;//虚拟合同状态
    @Transient
    private String contractStatusN;//虚拟合同状态

    private Double contractAmount;//虚拟合同金额

    private String contractName;//虚拟合同名称

    private String contractNumber;//虚拟合同编号

    private Date cancelDate;//撤销日期

    private String cancelReasion;//撤销原因

    private Long cancelPerson;//合同撤销申请人

    private Double penaltyRate;//罚息率

    private String approvalNumber;//批复编号

    private Double approvalAmount;//批复金额

    private String creditPlan;//授信方案

    private String creditCondition;//授信条件

    private String paymentCondition;//放款条件

    private String manageCondition;//管理条件

    private String dataType;//虚拟合同变更类型（NORMAL/HISTORY/CHANGE_REQ）

    private String meetingStatus;//会议确认状态(APPROVED/null)

    private String identificationMethod;//租赁物价值认定方式

    private String whetherInsurance;//是否办理保险

    private String whetherLabeling;//是否贴标

    private String whetherMortgageRegistration;//是否办理动产抵押登记

    private String isSpv;

    private String isLowRisk;

    private String powerfulPerson;

    private String fiveCategories;
    private String bankAccountNum;//银行卡号（进件收款信息）
    private String bankAccountName;//账户名（进件收款信息）
    private String bankFullName;//开户银行（进件收款信息）
    private String bankBranchName;//开户支行（进件收款信息）
    private Long investmentInstanceId;//投放审查流程id
    private String confirmStatus;//发起进件正审前，记录接口返回的审批状态

    @Transient
    private String fiveCategoriesN;


    public Long getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }

    @Transient
    private Long attachmentId;


    @Length(max = 255)
    private String floatingRangeMethod;//调息方式

    @Length(max = 255)
    private String prepaymentMethod;//提前还款方式

    @Length(max = 255)
    private String isInsure;//是否投保

    @Length(max = 255)
    private String inspectFrenquency; //贷后检查频率

    private Double assetLiabilityRatio;//资产负债率

    private Double totalAssets;//总资产

    private String customerIncomeStructure;//客户收入结构

    private String finStatementDate;//最新财报日期

    private String fiveClassificationResult;//五级分类结果

    private Long creditLineId;//授信额度id


    private String reviewStatus;


    private Date priceReviewDate;

    private Long priceReviewPerson;
    private String inceptType;
    @Transient
    private String inceptTypeN;
    @Transient
    private String isLowRiskN;
    @Transient
    private String reviewStatusN;

    @Transient
    private Double leftAmount;//剩余批复金额
    @Transient
    private Double usedAmount;//已用金额

    @Transient
    private Long virtualConCounts;//项目下虚拟合同数

    @Transient
    private String projectManager;//主办项目经理

    @Transient
    private String projectAssistantor;//协办项目经理

    @Transient
    private String projectAssistantName;//协办项目经理

    @Transient
    private String contractStatusDesc;//虚拟合同状态

    @Transient
    private String changeDescription;//
    @Transient
    private Long changeReqUserId;//
    @Transient
    private String changeReqUserName;
    @Transient
    private Date changeReqDate;//
    @Transient
    private Date approvedTime;

    private Long changeReqId;
    private String secondHandFlag;
    @Transient
    private String secondHandFlagN;

    private String paymentBpType;
    @Transient
    private String paymentBpTypeN;
    private Long paymentBpId;
    @Transient
    private String paymentBpIdN;
    private String insuranceFlag;
    @Transient
    private String insuranceFlagN;
    private String baseRateType;
    @Transient
    private String baseRateTypeN;
    private String pledgeFlag;
    @Transient
    private String pledgeFlagN;
    //租金计划是否通知客户
    @Column(name = "RENT_PLAN_NOTICE_FLAG")
    private String rentPlanNoticeFlag;

    @Transient
    private String rentPlanNoticeFlagN;

    @Transient
    private Long projectIdNew;
    @Transient
    private Long projectIdOld;
    @Transient
    private String bpName;
    @Transient
    private Long contractId;
    @Transient
    private String mortgageRegistrationN;

    @Transient
    private String mortgageRegistration;

    @Transient
    private String meetingResult;
    @Transient
    private Long seqNum;
    @Transient
    private String applyPayDate;
    @Transient
    private Double amountPaid;
    @Transient
    private Double amountRest;
    @Transient
    private String year;
    @Transient
    private String motherSource;
    @Transient
    private String otherSource;
    @Transient
    private String legalForm;
    private String leaseTerm;
    @Transient
    private String dueDate;
    @Transient
    private Double parInterestRate;
    @Transient
    private Double leaseChargeRatio;
    @Transient
    private Double leaseCharge;
    @Transient
    private Double depositRatio;
    @Transient
    private Double downPaymentRatio;
    @Transient
    private Double residual;
    @Transient
    private Double deposit;
    @Transient
    private String guaranteeType;
    @Transient
    private String abs;
    private String cancelReason;
    @Transient
    private String currencyDesc;
    @Transient
    private Date inceptDate;
    @Transient
    private Long creditLineIdOld;
    @Transient
    private Double vatRate;
    @Transient
    private String isLowRiskDesc;
    @Transient
    private String whetherMortRegDesc;
    @Transient
    private String identificationMethodDesc;
    @Transient
    private String whetherInsuranceDesc;
    @Transient
    private String whetherLabelingDesc;
    @Transient
    private String floatingRangeMethodDesc;
    @Transient
    private String leaseItemPropertyDesc;
    @Transient
    private String powerfulPersonN;
    @Transient
    private String projectNumberN;

    private Date firstRentalPaymentDate;
    @Transient
    private Long changeCount;

    //二期功能：是否更换合同编号
    @Transient
    private String changeProjectNumberFlag;

    @Transient
    private String creditWayCredit;
    @Transient
    private String creditWayGuarantee;
    @Transient
    private String creditWayMortgage;
    @Transient
    private String creditWayPledge;
    @Transient
    private String projectAssistantPart;
    @Transient
    private String proposerEmployeePart;

    @Transient
    private String changeReqProject;
    private String factorNature;
    @Transient
    private String factorNatureN;

    @Transient
    private Long checkId;
    @Transient
    private Double xirr;
    @Transient
    private Double intRate;
    @Transient
    private Double outstandingPrincipal;
    @Transient
    private String contractNum;
    private String riskStaffAdvice;
    @Transient
    private String riskStaffAdviceN;
    private String legalStaffAdvice;
    @Transient
    private String legalStaffAdviceN;

    private Date leaseLatestDeliveryDate;
    private Double terminationCompensationRatio;
    private Double earlyTerminationRatio;
    private Double earlyAlsoRentRatio;
    private String leasePriceUse;
    private Double stampDuty;
    private Double addedValueTax;
    private String falsifyCalculationMethod;
    private Double falsifyInterestRate;
    private Double poundageSignPay;
    private Double riskFeeSignPay;
    private String meetingType;
    @Transient
    private String unitManager;
    @Transient
    private String unitAssistant;
    @Transient
    private Long headId;
    @Transient
    private String meetingTypeN;

    private String meetingFlag;
    @Transient
    private String meetingFlagN;

    private String tenantSecId;

    private String tenantSecIdN;

    @Transient
    private Long tenantSecCount;

    @Transient
    private Long tenantSecMax;

    @Transient
    private Long warrantorCount;

    @Transient
    private Long warrantorMax;

    @Transient
    private Long warrantorCountNp;

    @Transient
    private Long warrantorMaxNp;

    private String priceNote;

    public Long getHeadId() {
        return headId;
    }

    public void setHeadId(Long headId) {
        this.headId = headId;
    }

    private Long marketingReportId;

    private Long hostProjectManager;

    private Long projectAssistant2;

    private Double proposerEmployeeRatio;

    private Double projectAssistantRatio;

    private Double projectAssistant2Ratio;

    private Long riskHost;
    private Double riskHostRatio;
    private Long riskAssistantFirst;
    private Long riskAssistantSecond;
    private Double riskAssistantFirstRatio;
    private Double riskAssistantSecondRatio;
    @Transient
    private String projectAssistant2Name;
    @Transient
    private String projectAssistant2N;
    @Transient
    private String riskHostN;
    @Transient
    private String riskAssistantFirstN;
    @Transient
    private String riskAssistantSecondN;

    private Long legalHost;
    private Double legalHostRatio;
    private Long legalAssistantFirst;
    private Long legalAssistantSecond;
    private Double legalAssistantFirstRatio;
    private Double legalAssistantSecondRatio;
    @Transient
    private String legalHostN;
    @Transient
    private String legalAssistantFirstN;
    @Transient
    private String legalAssistantSecondN;

    @Transient
    private String hostProjectManagerN;

    @Transient
    private String hostUnitName;

    private Long assistProjectManager;

    @Transient
    private String assistProjectManagerN;

    @Transient
    private String assistUnitName;

    @Transient
    private Long refCreditConditionId;

    @Transient
    private Long refPrjSurviveId;

    private String guarantorId;

    private String creditConditionContent;

    private String quotationElementContent;

    private String surviveRequireContent;

    private String guarantorNpId;

    private String riskMitigationMeasures;

    private String otherThing;

    private String competitiveAdvantage;

    private String businessRisk;

    private String comprehensiveOpinions;

    private String industryVoting;

    private String credit;

    private String ensure;

    private String mortgage;

    private String pledge;

    private String keySupportArea;

    private String greenLeasing;

    private String epidemicPrevention;

    private String nada;

    private Long approvalId;

    private String approvalStatus;

    private Long processInstanceId;

    private String voteStatus;

    private String voteComment;

    private String voteResult;

    private String endTaskNodeId;

    private Long hostUnitId;

    private Long assistUnitId;
    private String conEndTask;
    @Transient
    private String conEndTaskN;

    @Transient
    private String voteStatusN;

    @Transient
    private String voteResultN;

    @Transient
    private String queryInfo;
    @Transient
    private String falsifyCalculationMethodN;

    private Long companySpv;
    @Transient
    private Long riskWarningId;
    @Transient
    private String email;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getRiskWarningId() {
        return riskWarningId;
    }

    public void setRiskWarningId(Long riskWarningId) {
        this.riskWarningId = riskWarningId;
    }

    @Transient
    private String companySpvN;

    private String taxStructure;
    @Transient
    private Double leaseItemAmountPrj;
    @Transient
    private Double leftAmountPrj;
    public String getQueryInfo() {
        return queryInfo;
    }

    public void setQueryInfo(String queryInfo) {
        this.queryInfo = queryInfo;
    }

    public Double getVatRate() {
        return vatRate;
    }

    public void setVatRate(Double vatRate) {
        this.vatRate = vatRate;
    }

    public String getLeaseItemProperty() {
        return leaseItemProperty;
    }

    public void setLeaseItemProperty(String leaseItemProperty) {
        this.leaseItemProperty = leaseItemProperty;
    }

    private String leaseItemProperty;

    public String getInceptWflStatus() {
        return inceptWflStatus;
    }

    public void setInceptWflStatus(String inceptWflStatus) {
        this.inceptWflStatus = inceptWflStatus;
    }

    @Transient
    private String inceptWflStatus;

    private Long guarantorSum; //保证流水号

    public Long getDays() {
        return days;
    }

    public void setDays(Long days) {
        this.days = days;
    }

    public Long getGuarantorSum() {
        return guarantorSum;
    }

    public void setGuarantorSum(Long guarantorSum) {
        this.guarantorSum = guarantorSum;
    }

    public Long getPledgorSum() {
        return pledgorSum;
    }

    public void setPledgorSum(Long pledgorSum) {
        this.pledgorSum = pledgorSum;
    }

    public Long getMortgagorSum() {
        return mortgagorSum;
    }

    public void setMortgagorSum(Long mortgagorSum) {
        this.mortgagorSum = mortgagorSum;
    }

    private Long pledgorSum; //质押流水号

    private Long mortgagorSum; //抵押流水号

    public Date getInceptDate() {
        return inceptDate;
    }

    public void setInceptDate(Date inceptDate) {
        this.inceptDate = inceptDate;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Transient
    private String companyName;

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    @Transient
    private String unitName;

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Boolean getSuccess() {
        return success;
    }

    public void setSuccess(Boolean success) {
        this.success = success;
    }

    @Transient

    private String message;
    @Transient
    private Boolean success;

    @Override
    public Long getQuotationId() {
        return quotationId;
    }

    @Override
    public void setQuotationId(Long quotationId) {
        this.quotationId = quotationId;
    }

    @Transient
    private Long quotationId;


    private Date signDate;

    public Date getSignDate() {
        return signDate;
    }

    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    public String getSignDescription() {
        return signDescription;
    }

    public void setSignDescription(String signDescription) {
        this.signDescription = signDescription;
    }

    private String signDescription;

    public String getCurrencyDesc() {
        return currencyDesc;
    }

    public void setCurrencyDesc(String currencyDesc) {
        this.currencyDesc = currencyDesc;
    }

    public String getCreateContractStatusDesc() {
        return createContractStatusDesc;
    }

    public void setCreateContractStatusDesc(String createContractStatusDesc) {
        this.createContractStatusDesc = createContractStatusDesc;
    }

    @Transient
    private String createContractStatusDesc;

    public String getCancelReason() {
        return cancelReason;
    }

    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    public String getCancelStatus() {
        return cancelStatus;
    }

    public void setCancelStatus(String cancelStatus) {
        this.cancelStatus = cancelStatus;
    }

    private String cancelStatus;

    public String getCreateContractStatus() {
        return createContractStatus;
    }

    public void setCreateContractStatus(String createContractStatus) {
        this.createContractStatus = createContractStatus;
    }

    private String createContractStatus;

    public String getLeasingNumber() {
        return leasingNumber;
    }

    public void setLeasingNumber(String leasingNumber) {
        this.leasingNumber = leasingNumber;
    }

    private String leasingNumber;//流水号
    private String creditFlag;
    @Transient
    private String creditFlagN;
    @Transient
    private String createdByN;
    @Transient
    private String hostUnitIdN;
    @Transient
    private String assistUnitIdN;
    @Transient
    private String projectManagerN;
    @Transient
    private String unitIdN;
    private String creditApply;
    private String creditNote;
    private String leaseMatterNote;
    private String guaranteeMethodNote;
    private String financeNote;
//    @Transient
    private Date approvedDate;
    private String otherYn;
    private String pledgeYn;
    private String mortgageYn;
    private String guaranteeYn;
    private String insurancePlanNote;
    private String insureFlag;
    @Transient
    private String insureFlagN;
    private String guaranteeMethod;
    @Transient
    private String guaranteeMethodN;
    private String payMethod;
    @Transient
    private String payMethodN;
    private Long insuranceAmount;
    private Long bondAmount;
    private Long insuredAmount;
    private String beneficiary;
    private String insurancePeriod;
    private String comRiskFlag;
    private String machineDamageFlag;
    private String enginMachFlag;
    private String enginAllFlag;
    private String compulsoryInsFlag;
    private String thirdInsFlag;
    private String othersFlag;
    private String cs_number;
    @Transient
    private Long allocationId;

    private String other;
    private Integer returnTimes;
    private Date returnDate;

    private Double penaltyRatio;
    private String singAddr;
    private Long employeeId;
    private Long unitId;
    private String leaseItemType;
    private Double financeAmount;

    @Transient
    private String employeeIdN;
    @Transient
    private String employeeName;
    @Transient
    private String manufacturerIdN;
    @Transient
    private String projectNumber;

    public Long getAllocationId() {
        return allocationId;
    }

    public void setAllocationId(Long allocationId) {
        this.allocationId = allocationId;
    }

    public String getCs_number() {
        return cs_number;
    }

    public void setCs_number(String cs_number) {
        this.cs_number = cs_number;
    }

    public String getOverdueStatus() {
        return overdueStatus;
    }

    public void setOverdueStatus(String overdueStatus) {
        this.overdueStatus = overdueStatus;
    }

    public String getOverdueStatusN() {
        return overdueStatusN;
    }

    public void setOverdueStatusN(String overdueStatusN) {
        this.overdueStatusN = overdueStatusN;
    }

    public String getOverdueMaxDays() {
        return overdueMaxDays;
    }

    public void setOverdueMaxDays(String overdueMaxDays) {
        this.overdueMaxDays = overdueMaxDays;
    }

    public Long getOverdueTimes() {
        return overdueTimes;
    }

    public void setOverdueTimes(Long overdueTimes) {
        this.overdueTimes = overdueTimes;
    }

    public Double getOverdueAmount() {
        return overdueAmount;
    }

    public void setOverdueAmount(Double overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    public Double getOverduePrincipalAmount() {
        return overduePrincipalAmount;
    }

    public void setOverduePrincipalAmount(Double overduePrincipalAmount) {
        this.overduePrincipalAmount = overduePrincipalAmount;
    }

    public Double getOverdueInterestAmount() {
        return overdueInterestAmount;
    }

    public void setOverdueInterestAmount(Double overdueInterestAmount) {
        this.overdueInterestAmount = overdueInterestAmount;
    }

    public Double getPenaltyAmount() {
        return penaltyAmount;
    }

    public void setPenaltyAmount(Double penaltyAmount) {
        this.penaltyAmount = penaltyAmount;
    }

    public Long getContractId() {
        return contractId;
    }

    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    @Override
    public String getBpName() {
        return bpName;
    }

    public void setBpName(String bpName) {
        this.bpName = bpName;
    }

    public Double getDebtAmount() {
        return debtAmount;
    }

    public void setDebtAmount(Double debtAmount) {
        this.debtAmount = debtAmount;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Double getCreditAmount() {
        return creditAmount;
    }

    public void setCreditAmount(Double creditAmount) {
        this.creditAmount = creditAmount;
    }

    public String getUsedCashFlow() {
        return usedCashFlow;
    }

    public void setUsedCashFlow(String usedCashFlow) {
        this.usedCashFlow = usedCashFlow;
    }

    public String getCashFlowAnalyse() {
        return cashFlowAnalyse;
    }

    public void setCashFlowAnalyse(String cashFlowAnalyse) {
        this.cashFlowAnalyse = cashFlowAnalyse;
    }

    public String getPrjAdvantage() {
        return prjAdvantage;
    }

    public void setPrjAdvantage(String prjAdvantage) {
        this.prjAdvantage = prjAdvantage;
    }

    public String getOtherDescription() {
        return otherDescription;
    }

    public void setOtherDescription(String otherDescription) {
        this.otherDescription = otherDescription;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Long getChanceId() {
        return chanceId;
    }

    public void setChanceId(Long chanceId) {
        this.chanceId = chanceId;
    }

    public String getSumEvaluation() {
        return sumEvaluation;
    }


    public void setSumEvaluation(String sumEvaluation) {
        this.sumEvaluation = sumEvaluation;
    }

    public String getProjectManager() {
        return projectManager;
    }

    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager;
    }

    public String getProjectAssistantor() {
        return projectAssistantor;
    }

    public void setProjectAssistantor(String projectAssistantor) {
        this.projectAssistantor = projectAssistantor;
    }

    public String getSubjectMatterIntrodution() {
        return subjectMatterIntrodution;
    }

    public void setSubjectMatterIntrodution(String subjectMatterIntrodution) {
        this.subjectMatterIntrodution = subjectMatterIntrodution;
    }

    public String getDataClass() {
        return dataClass;
    }

    public void setDataClass(String dataClass) {
        this.dataClass = dataClass;
    }

    public Long getRefProjectId() {
        return refProjectId;
    }

    public void setRefProjectId(Long refProjectId) {
        this.refProjectId = refProjectId;
    }

    public String getContractStatus() {
        return contractStatus;
    }

    public void setContractStatus(String contractStatus) {
        this.contractStatus = contractStatus;
    }

    public Double getContractAmount() {
        return contractAmount;
    }

    public void setContractAmount(Double contractAmount) {
        this.contractAmount = contractAmount;
    }

    public Double getPenaltyRate() {
        return penaltyRate;
    }

    public void setPenaltyRate(Double penaltyRate) {
        this.penaltyRate = penaltyRate;
    }

    public String getFloatingRangeMethod() {
        return floatingRangeMethod;
    }

    public void setFloatingRangeMethod(String floatingRangeMethod) {
        this.floatingRangeMethod = floatingRangeMethod;
    }

    public String getPrepaymentMethod() {
        return prepaymentMethod;
    }

    public void setPrepaymentMethod(String prepaymentMethod) {
        this.prepaymentMethod = prepaymentMethod;
    }

    public String getIsInsure() {
        return isInsure;
    }

    public void setIsInsure(String isInsure) {
        this.isInsure = isInsure;
    }

    public String getInspectFrenquency() {
        return inspectFrenquency;
    }

    public void setInspectFrenquency(String inspectFrenquency) {
        this.inspectFrenquency = inspectFrenquency;
    }

    public String getContractName() {
        return contractName;
    }

    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    public String getContractNumber() {
        return contractNumber;
    }

    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    public String getContractStatusDesc() {
        return contractStatusDesc;
    }

    public void setContractStatusDesc(String contractStatusDesc) {
        this.contractStatusDesc = contractStatusDesc;
    }

    public Date getCancelDate() {
        return cancelDate;
    }

    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    public String getCancelReasion() {
        return cancelReasion;
    }

    public void setCancelReasion(String cancelReasion) {
        this.cancelReasion = cancelReasion;
    }

    public String getChangeDescription() {
        return changeDescription;
    }

    public void setChangeDescription(String changeDescription) {
        this.changeDescription = changeDescription;
    }

    public Long getChangeReqUserId() {
        return changeReqUserId;
    }

    public void setChangeReqUserId(Long changeReqUserId) {
        this.changeReqUserId = changeReqUserId;
    }

    public Date getChangeReqDate() {
        return changeReqDate;
    }

    public void setChangeReqDate(Date changeReqDate) {
        this.changeReqDate = changeReqDate;
    }

    public Long getChangeReqId() {
        return changeReqId;
    }

    public void setChangeReqId(Long changeReqId) {
        this.changeReqId = changeReqId;
    }

    public Long getProjectIdNew() {
        return projectIdNew;
    }

    public void setProjectIdNew(Long projectIdNew) {
        this.projectIdNew = projectIdNew;
    }

    public Long getProjectIdOld() {
        return projectIdOld;
    }

    public void setProjectIdOld(Long projectIdOld) {
        this.projectIdOld = projectIdOld;
    }

    public Long getCancelPerson() {
        return cancelPerson;
    }

    public void setCancelPerson(Long cancelPerson) {
        this.cancelPerson = cancelPerson;
    }

    public String getApprovalNumber() {
        return approvalNumber;
    }

    public void setApprovalNumber(String approvalNumber) {
        this.approvalNumber = approvalNumber;
    }

    public Double getApprovalAmount() {
        return approvalAmount;
    }

    public void setApprovalAmount(Double approvalAmount) {
        this.approvalAmount = approvalAmount;
    }

    public String getCreditPlan() {
        return creditPlan;
    }

    public void setCreditPlan(String creditPlan) {
        this.creditPlan = creditPlan;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getMeetingResult() {
        return meetingResult;
    }

    public void setMeetingResult(String meetingResult) {
        this.meetingResult = meetingResult;
    }

    public String getMeetingStatus() {
        return meetingStatus;
    }

    public void setMeetingStatus(String meetingStatus) {
        this.meetingStatus = meetingStatus;
    }

    public Double getAssetLiabilityRatio() {
        return assetLiabilityRatio;
    }

    public void setAssetLiabilityRatio(Double assetLiabilityRatio) {
        this.assetLiabilityRatio = assetLiabilityRatio;
    }

    public Double getTotalAssets() {
        return totalAssets;
    }

    public void setTotalAssets(Double totalAssets) {
        this.totalAssets = totalAssets;
    }

    public String getCustomerIncomeStructure() {
        return customerIncomeStructure;
    }

    public void setCustomerIncomeStructure(String customerIncomeStructure) {
        this.customerIncomeStructure = customerIncomeStructure;
    }

    public String getCreditCondition() {
        return creditCondition;
    }

    public void setCreditCondition(String creditCondition) {
        this.creditCondition = creditCondition;
    }

    public String getPaymentCondition() {
        return paymentCondition;
    }

    public void setPaymentCondition(String paymentCondition) {
        this.paymentCondition = paymentCondition;
    }

    public String getManageCondition() {
        return manageCondition;
    }

    public void setManageCondition(String manageCondition) {
        this.manageCondition = manageCondition;
    }

    public String getFinStatementDate() {
        return finStatementDate;
    }

    public void setFinStatementDate(String finStatementDate) {
        this.finStatementDate = finStatementDate;
    }

    public Double getLeftAmount() {
        return leftAmount;
    }

    public void setLeftAmount(Double leftAmount) {
        this.leftAmount = leftAmount;
    }

    public Long getVirtualConCounts() {
        return virtualConCounts;
    }

    public void setVirtualConCounts(Long virtualConCounts) {
        this.virtualConCounts = virtualConCounts;
    }

    public String getFiveClassificationResult() {
        return fiveClassificationResult;
    }

    public void setFiveClassificationResult(String fiveClassificationResult) {
        this.fiveClassificationResult = fiveClassificationResult;
    }

    public String getTenantIdN() {
        return tenantIdN;
    }

    public void setTenantIdN(String tenantIdN) {
        this.tenantIdN = tenantIdN;
    }

    public Long getSeqNum() {
        return seqNum;
    }

    public void setSeqNum(Long seqNum) {
        this.seqNum = seqNum;
    }

    public String getApplyPayDate() {
        return applyPayDate;
    }

    public void setApplyPayDate(String applyPayDate) {
        this.applyPayDate = applyPayDate;
    }

    public Double getAmountPaid() {
        return amountPaid;
    }

    public void setAmountPaid(Double amountPaid) {
        this.amountPaid = amountPaid;
    }

    public Double getAmountRest() {
        return amountRest;
    }

    public void setAmountRest(Double amountRest) {
        this.amountRest = amountRest;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getMotherSource() {
        return motherSource;
    }

    public void setMotherSource(String motherSource) {
        this.motherSource = motherSource;
    }

    public String getOtherSource() {
        return otherSource;
    }

    public void setOtherSource(String otherSource) {
        this.otherSource = otherSource;
    }

    public String getLegalForm() {
        return legalForm;
    }

    public void setLegalForm(String legalForm) {
        this.legalForm = legalForm;
    }

    public String getLeaseTerm() {
        return leaseTerm;
    }

    public void setLeaseTerm(String leaseTerm) {
        this.leaseTerm = leaseTerm;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public Double getParInterestRate() {
        return parInterestRate;
    }

    public void setParInterestRate(Double parInterestRate) {
        this.parInterestRate = parInterestRate;
    }

    public Double getLeaseChargeRatio() {
        return leaseChargeRatio;
    }

    public void setLeaseChargeRatio(Double leaseChargeRatio) {
        this.leaseChargeRatio = leaseChargeRatio;
    }

    public Double getLeaseCharge() {
        return leaseCharge;
    }

    public void setLeaseCharge(Double leaseCharge) {
        this.leaseCharge = leaseCharge;
    }

    public Double getDepositRatio() {
        return depositRatio;
    }

    public void setDepositRatio(Double depositRatio) {
        this.depositRatio = depositRatio;
    }

    public Double getDeposit() {
        return deposit;
    }

    public void setDeposit(Double deposit) {
        this.deposit = deposit;
    }

    public String getGuaranteeType() {
        return guaranteeType;
    }

    public void setGuaranteeType(String guaranteeType) {
        this.guaranteeType = guaranteeType;
    }

    public String getAbs() {
        return abs;
    }

    public void setAbs(String abs) {
        this.abs = abs;
    }

    @Transient
    private String documentTypeArray;
    @Transient
    private String absArray;
    @Transient
    private String absString;
    @Transient
    private Long yearFrom;
    @Transient
    private Long yearTo;//年份到
    @Transient
    private String dateFrom;//投放时间从
    @Transient
    private String dateTo;
    @Transient
    private String dateValidFrom;//到期日从
    @Transient
    private String dateValidTo;
    @Transient
    private String amountBetween;
    @Transient
    private Double amountFrom;
    @Transient
    private Double amountTo;
    @Transient
    private Double trxAmountFrom;
    @Transient
    private Double trxAmountTo;
    @Transient
    private Long projectRefCount;
    @Transient
    private String projectAssistantPartN;
    @Transient
    private Double leaseItemAmountFrom;
    @Transient
    private Double leaseItemAmountTo;
    @Transient
    private String businessTypeN;

    private String marketingChannel;

    private String xyBranchBank;
    private String contentBusinessType;
    @Transient
    private String contentBusinessTypeN;
    @Transient
    private Long projectAttachmentId;

    private String industryCategory;

    //接受前端租赁物id参数
    @Transient
    private String itemIds;

    public String getDocumentTypeArray() {
        return documentTypeArray;
    }

    public void setDocumentTypeArray(String documentTypeArray) {
        this.documentTypeArray = documentTypeArray;
    }

    public String getAbsArray() {
        return absArray;
    }

    public void setAbsArray(String absArray) {
        this.absArray = absArray;
    }

    public String getAbsString() {
        return absString;
    }

    public void setAbsString(String absString) {
        this.absString = absString;
    }

    public Long getYearFrom() {
        return yearFrom;
    }

    public void setYearFrom(Long yearFrom) {
        this.yearFrom = yearFrom;
    }

    public Long getYearTo() {
        return yearTo;
    }

    public void setYearTo(Long yearTo) {
        this.yearTo = yearTo;
    }

    public String getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(String dateFrom) {
        this.dateFrom = dateFrom;
    }

    public String getDateTo() {
        return dateTo;
    }

    public void setDateTo(String dateTo) {
        this.dateTo = dateTo;
    }

    public String getDateValidFrom() {
        return dateValidFrom;
    }

    public void setDateValidFrom(String dateValidFrom) {
        this.dateValidFrom = dateValidFrom;
    }

    public String getDateValidTo() {
        return dateValidTo;
    }

    public void setDateValidTo(String dateValidTo) {
        this.dateValidTo = dateValidTo;
    }

    public String getAmountBetween() {
        return amountBetween;
    }

    public void setAmountBetween(String amountBetween) {
        this.amountBetween = amountBetween;
    }

    public Double getAmountFrom() {
        return amountFrom;
    }

    public void setAmountFrom(Double amountFrom) {
        this.amountFrom = amountFrom;
    }

    public Double getAmountTo() {
        return amountTo;
    }

    public void setAmountTo(Double amountTo) {
        this.amountTo = amountTo;
    }

    public Double getTrxAmountFrom() {
        return trxAmountFrom;
    }

    public void setTrxAmountFrom(Double trxAmountFrom) {
        this.trxAmountFrom = trxAmountFrom;
    }

    public Double getTrxAmountTo() {
        return trxAmountTo;
    }

    public void setTrxAmountTo(Double trxAmountTo) {
        this.trxAmountTo = trxAmountTo;
    }

    public Long getCreditLineId() {
        return creditLineId;
    }

    public void setCreditLineId(Long creditLineId) {
        this.creditLineId = creditLineId;
    }

    public String getProjectAssistantName() {
        return projectAssistantName;
    }

    public void setProjectAssistantName(String projectAssistantName) {
        this.projectAssistantName = projectAssistantName;
    }

    public String getIdentificationMethod() {
        return identificationMethod;
    }

    public void setIdentificationMethod(String identificationMethod) {
        this.identificationMethod = identificationMethod;
    }

    public String getWhetherInsurance() {
        return whetherInsurance;
    }

    public void setWhetherInsurance(String whetherInsurance) {
        this.whetherInsurance = whetherInsurance;
    }

    public String getWhetherLabeling() {
        return whetherLabeling;
    }

    public void setWhetherLabeling(String whetherLabeling) {
        this.whetherLabeling = whetherLabeling;
    }

    public String getWhetherMortgageRegistration() {
        return whetherMortgageRegistration;
    }

    public void setWhetherMortgageRegistration(String whetherMortgageRegistration) {
        this.whetherMortgageRegistration = whetherMortgageRegistration;
    }

    private Double leaseItemAmount;

    @Override
    public Double getLeaseItemAmount() {
        return leaseItemAmount;
    }

    @Override
    public void setLeaseItemAmount(Double leaseItemAmount) {
        this.leaseItemAmount = leaseItemAmount;
    }

    public String getProjectReqStatus() {
        return projectReqStatus;
    }

    public void setProjectReqStatus(String projectReqStatus) {
        this.projectReqStatus = projectReqStatus;
    }

    public Long getCreditLineIdOld() {
        return creditLineIdOld;
    }

    public void setCreditLineIdOld(Long creditLineIdOld) {
        this.creditLineIdOld = creditLineIdOld;
    }

    public Long getProjectIdHistory() {
        return projectIdHistory;
    }

    public void setProjectIdHistory(Long projectIdHistory) {
        this.projectIdHistory = projectIdHistory;
    }

    public String getChangeReqUserName() {
        return changeReqUserName;
    }

    public void setChangeReqUserName(String changeReqUserName) {
        this.changeReqUserName = changeReqUserName;
    }

    public String getIsSpv() {
        return isSpv;
    }

    public void setIsSpv(String isSpv) {
        this.isSpv = isSpv;
    }

    public String getIsLowRisk() {
        return isLowRisk;
    }

    public void setIsLowRisk(String isLowRisk) {
        this.isLowRisk = isLowRisk;
    }

    public String getIsLowRiskDesc() {
        return isLowRiskDesc;
    }

    public void setIsLowRiskDesc(String isLowRiskDesc) {
        this.isLowRiskDesc = isLowRiskDesc;
    }

    public String getWhetherMortRegDesc() {
        return whetherMortRegDesc;
    }

    public void setWhetherMortRegDesc(String whetherMortRegDesc) {
        this.whetherMortRegDesc = whetherMortRegDesc;
    }

    public String getIdentificationMethodDesc() {
        return identificationMethodDesc;
    }

    public void setIdentificationMethodDesc(String identificationMethodDesc) {
        this.identificationMethodDesc = identificationMethodDesc;
    }

    public String getWhetherInsuranceDesc() {
        return whetherInsuranceDesc;
    }

    public void setWhetherInsuranceDesc(String whetherInsuranceDesc) {
        this.whetherInsuranceDesc = whetherInsuranceDesc;
    }

    public String getWhetherLabelingDesc() {
        return whetherLabelingDesc;
    }

    public void setWhetherLabelingDesc(String whetherLabelingDesc) {
        this.whetherLabelingDesc = whetherLabelingDesc;
    }

    public String getFloatingRangeMethodDesc() {
        return floatingRangeMethodDesc;
    }

    public void setFloatingRangeMethodDesc(String floatingRangeMethodDesc) {
        this.floatingRangeMethodDesc = floatingRangeMethodDesc;
    }

    public String getLeaseItemPropertyDesc() {
        return leaseItemPropertyDesc;
    }

    public void setLeaseItemPropertyDesc(String leaseItemPropertyDesc) {
        this.leaseItemPropertyDesc = leaseItemPropertyDesc;
    }

    public Date getFirstRentalPaymentDate() {
        return firstRentalPaymentDate;
    }

    public void setFirstRentalPaymentDate(Date firstRentalPaymentDate) {
        this.firstRentalPaymentDate = firstRentalPaymentDate;
    }

    public Long getChangeCount() {
        return changeCount;
    }

    public void setChangeCount(Long changeCount) {
        this.changeCount = changeCount;
    }

    public Long getProjectRefCount() {
        return projectRefCount;
    }

    public void setProjectRefCount(Long projectRefCount) {
        this.projectRefCount = projectRefCount;
    }

    private Double firstDownPayment;

    private Double residualValue;


    private Date leaseTermLimitDate;

    private Double downPayment;

    private Double projectPrincipal;

    public Double getDownPayment() {
        return downPayment;
    }

    public void setDownPayment(Double downPayment) {
        this.downPayment = downPayment;
    }

    public Double getProjectPrincipal() {
        return projectPrincipal;
    }

    public void setProjectPrincipal(Double projectPrincipal) {
        this.projectPrincipal = projectPrincipal;
    }

    public Double getFirstDownPayment() {
        return firstDownPayment;
    }

    public void setFirstDownPayment(Double firstDownPayment) {
        this.firstDownPayment = firstDownPayment;
    }

    public Double getResidualValue() {
        return residualValue;
    }

    public void setResidualValue(Double residualValue) {
        this.residualValue = residualValue;
    }

    public Date getLeaseTermLimitDate() {
        return leaseTermLimitDate;
    }

    public void setLeaseTermLimitDate(Date leaseTermLimitDate) {
        this.leaseTermLimitDate = leaseTermLimitDate;
    }

    public String getProjectNumberN() {
        return projectNumberN;
    }

    public void setProjectNumberN(String projectNumberN) {
        this.projectNumberN = projectNumberN;
    }

    public Long getFinStatementHdId() {
        return finStatementHdId;
    }

    public void setFinStatementHdId(Long finStatementHdId) {
        this.finStatementHdId = finStatementHdId;
    }

    public String getMortgageRegistrationN() {
        return mortgageRegistrationN;
    }

    public void setMortgageRegistrationN(String mortgageRegistrationN) {
        this.mortgageRegistrationN = mortgageRegistrationN;
    }

    public String getMortgageRegistration() {
        return mortgageRegistration;
    }

    public void setMortgageRegistration(String mortgageRegistration) {
        this.mortgageRegistration = mortgageRegistration;
    }

    public String getCreditWayCredit() {
        return creditWayCredit;
    }

    public void setCreditWayCredit(String creditWayCredit) {
        this.creditWayCredit = creditWayCredit;
    }

    public String getCreditWayGuarantee() {
        return creditWayGuarantee;
    }

    public void setCreditWayGuarantee(String creditWayGuarantee) {
        this.creditWayGuarantee = creditWayGuarantee;
    }

    public String getCreditWayMortgage() {
        return creditWayMortgage;
    }

    public void setCreditWayMortgage(String creditWayMortgage) {
        this.creditWayMortgage = creditWayMortgage;
    }

    public String getCreditWayPledge() {
        return creditWayPledge;
    }

    public void setCreditWayPledge(String creditWayPledge) {
        this.creditWayPledge = creditWayPledge;
    }

    public Date getLeaseLatestDeliveryDate() {
        return leaseLatestDeliveryDate;
    }

    public void setLeaseLatestDeliveryDate(Date leaseLatestDeliveryDate) {
        this.leaseLatestDeliveryDate = leaseLatestDeliveryDate;
    }

    public Double getTerminationCompensationRatio() {
        return terminationCompensationRatio;
    }

    public void setTerminationCompensationRatio(Double terminationCompensationRatio) {
        this.terminationCompensationRatio = terminationCompensationRatio;
    }

    public Double getEarlyTerminationRatio() {
        return earlyTerminationRatio;
    }

    public void setEarlyTerminationRatio(Double earlyTerminationRatio) {
        this.earlyTerminationRatio = earlyTerminationRatio;
    }

    public Double getEarlyAlsoRentRatio() {
        return earlyAlsoRentRatio;
    }

    public void setEarlyAlsoRentRatio(Double earlyAlsoRentRatio) {
        this.earlyAlsoRentRatio = earlyAlsoRentRatio;
    }

    public String getLeasePriceUse() {
        return leasePriceUse;
    }

    public void setLeasePriceUse(String leasePriceUse) {
        this.leasePriceUse = leasePriceUse;
    }

    public Double getStampDuty() {
        return stampDuty;
    }

    public void setStampDuty(Double stampDuty) {
        this.stampDuty = stampDuty;
    }

    public Double getAddedValueTax() {
        return addedValueTax;
    }

    public void setAddedValueTax(Double addedValueTax) {
        this.addedValueTax = addedValueTax;
    }

    public String getFalsifyCalculationMethod() {
        return falsifyCalculationMethod;
    }

    public void setFalsifyCalculationMethod(String falsifyCalculationMethod) {
        this.falsifyCalculationMethod = falsifyCalculationMethod;
    }

    public Double getFalsifyInterestRate() {
        return falsifyInterestRate;
    }

    public void setFalsifyInterestRate(Double falsifyInterestRate) {
        this.falsifyInterestRate = falsifyInterestRate;
    }

    public Double getPoundageSignPay() {
        return poundageSignPay;
    }

    public void setPoundageSignPay(Double poundageSignPay) {
        this.poundageSignPay = poundageSignPay;
    }

    public Double getRiskFeeSignPay() {
        return riskFeeSignPay;
    }

    public void setRiskFeeSignPay(Double riskFeeSignPay) {
        this.riskFeeSignPay = riskFeeSignPay;
    }

    public String getTenantSecId() {
        return tenantSecId;
    }

    public void setTenantSecId(String tenantSecId) {
        this.tenantSecId = tenantSecId;
    }

    public String getTenantSecIdN() {
        return tenantSecIdN;
    }

    public void setTenantSecIdN(String tenantSecIdN) {
        this.tenantSecIdN = tenantSecIdN;
    }

    public String getProjectAssistantPart() {
        return projectAssistantPart;
    }

    public void setProjectAssistantPart(String projectAssistantPart) {
        this.projectAssistantPart = projectAssistantPart;
    }

    public String getProposerEmployeePart() {
        return proposerEmployeePart;
    }

    public void setProposerEmployeePart(String proposerEmployeePart) {
        this.proposerEmployeePart = proposerEmployeePart;
    }

    public String getUnitManager() {
        return unitManager;
    }

    public void setUnitManager(String unitManager) {
        this.unitManager = unitManager;
    }

    public String getUnitAssistant() {
        return unitAssistant;
    }

    public void setUnitAssistant(String unitAssistant) {
        this.unitAssistant = unitAssistant;
    }

    public Long getMarketingReportId() {
        return marketingReportId;
    }

    public void setMarketingReportId(Long marketingReportId) {
        this.marketingReportId = marketingReportId;
    }

    public Long getHostProjectManager() {
        return hostProjectManager;
    }

    public void setHostProjectManager(Long hostProjectManager) {
        this.hostProjectManager = hostProjectManager;
    }

    public String getHostProjectManagerN() {
        return hostProjectManagerN;
    }

    public void setHostProjectManagerN(String hostProjectManagerN) {
        this.hostProjectManagerN = hostProjectManagerN;
    }

    public String getHostUnitName() {
        return hostUnitName;
    }

    public void setHostUnitName(String hostUnitName) {
        this.hostUnitName = hostUnitName;
    }

    public Long getAssistProjectManager() {
        return assistProjectManager;
    }

    public void setAssistProjectManager(Long assistProjectManager) {
        this.assistProjectManager = assistProjectManager;
    }

    public String getAssistProjectManagerN() {
        return assistProjectManagerN;
    }

    public void setAssistProjectManagerN(String assistProjectManagerN) {
        this.assistProjectManagerN = assistProjectManagerN;
    }

    public String getAssistUnitName() {
        return assistUnitName;
    }

    public void setAssistUnitName(String assistUnitName) {
        this.assistUnitName = assistUnitName;
    }

    public Long getTenantSecCount() {
        return tenantSecCount;
    }

    public void setTenantSecCount(Long tenantSecCount) {
        this.tenantSecCount = tenantSecCount;
    }

    public Long getTenantSecMax() {
        return tenantSecMax;
    }

    public void setTenantSecMax(Long tenantSecMax) {
        this.tenantSecMax = tenantSecMax;
    }

    public Long getWarrantorCount() {
        return warrantorCount;
    }

    public void setWarrantorCount(Long warrantorCount) {
        this.warrantorCount = warrantorCount;
    }

    public Long getWarrantorMax() {
        return warrantorMax;
    }

    public void setWarrantorMax(Long warrantorMax) {
        this.warrantorMax = warrantorMax;
    }

    public String getGuarantorId() {
        return guarantorId;
    }

    public void setGuarantorId(String guarantorId) {
        this.guarantorId = guarantorId;
    }

    @Transient
    private String paymentNumber;

    public String getPaymentNumber() {
        return paymentNumber;
    }

    public void setPaymentNumber(String paymentNumber) {
        this.paymentNumber = paymentNumber;
    }

    @Transient
    private Date leaseAccountDate;

    public Date getLeaseAccountDate() {
        return leaseAccountDate;
    }

    public void setLeaseAccountDate(Date leaseAccountDate) {
        this.leaseAccountDate = leaseAccountDate;
    }

    @Transient
    private Date inceptionOfLease;

    public Date getInceptionOfLease() {
        return inceptionOfLease;
    }

    public void setInceptionOfLease(Date inceptionOfLease) {
        this.inceptionOfLease = inceptionOfLease;
    }

    @Transient
    private Double financeAmountFrom;

    @Transient
    private Double financeAmountTo;

    public Double getFinanceAmountFrom() {
        return financeAmountFrom;
    }

    public void setFinanceAmountFrom(Double financeAmountFrom) {
        this.financeAmountFrom = financeAmountFrom;
    }

    public Double getFinanceAmountTo() {
        return financeAmountTo;
    }

    public void setFinanceAmountTo(Double financeAmountTo) {
        this.financeAmountTo = financeAmountTo;
    }

    public String getRiskMitigationMeasures() {
        return riskMitigationMeasures;
    }

    public void setRiskMitigationMeasures(String riskMitigationMeasures) {
        this.riskMitigationMeasures = riskMitigationMeasures;
    }

    public String getOtherThing() {
        return otherThing;
    }

    public void setOtherThing(String otherThing) {
        this.otherThing = otherThing;
    }

    public String getCompetitiveAdvantage() {
        return competitiveAdvantage;
    }

    public void setCompetitiveAdvantage(String competitiveAdvantage) {
        this.competitiveAdvantage = competitiveAdvantage;
    }

    public String getBusinessRisk() {
        return businessRisk;
    }

    public void setBusinessRisk(String businessRisk) {
        this.businessRisk = businessRisk;
    }

    public String getComprehensiveOpinions() {
        return comprehensiveOpinions;
    }

    public void setComprehensiveOpinions(String comprehensiveOpinions) {
        this.comprehensiveOpinions = comprehensiveOpinions;
    }

    public Long getWarrantorCountNp() {
        return warrantorCountNp;
    }

    public void setWarrantorCountNp(Long warrantorCountNp) {
        this.warrantorCountNp = warrantorCountNp;
    }

    public Long getWarrantorMaxNp() {
        return warrantorMaxNp;
    }

    public void setWarrantorMaxNp(Long warrantorMaxNp) {
        this.warrantorMaxNp = warrantorMaxNp;
    }

    public String getGuarantorNpId() {
        return guarantorNpId;
    }

    public void setGuarantorNpId(String guarantorNpId) {
        this.guarantorNpId = guarantorNpId;
    }

    @Transient
    private Date leaseAccountDateDelay;

    public Date getLeaseAccountDateDelay() {
        return leaseAccountDateDelay;
    }

    public void setLeaseAccountDateDelay(Date leaseAccountDateDelay) {
        this.leaseAccountDateDelay = leaseAccountDateDelay;
    }

    public void setIndustryVoting(String industryVoting) {
        this.industryVoting = industryVoting;
    }

    public String getIndustryVoting() {
        return industryVoting;
    }

    @Transient
    private String leaseAccountDateFrom;

    @Transient
    private String leaseAccountDateTo;

    @Transient
    private String approvalStatusN;
    @Transient
    private String marketingReportNumber;

    @Transient
    private String meetingName;
    @Transient
    private String meetingLocation;
    @Transient
    private String meetingDate;
    @Transient
    private String meetingPerson;

    @Transient
    private Long creditPlanId;

    public String getMeetingName() {
        return meetingName;
    }

    public void setMeetingName(String meetingName) {
        this.meetingName = meetingName;
    }

    public String getCredit() {
        return credit;
    }

    public void setCredit(String credit) {
        this.credit = credit;
    }

    public String getEnsure() {
        return ensure;
    }

    public void setEnsure(String ensure) {
        this.ensure = ensure;
    }

    public String getMortgage() {
        return mortgage;
    }

    public void setMortgage(String mortgage) {
        this.mortgage = mortgage;
    }

    public String getPledge() {
        return pledge;
    }

    public void setPledge(String pledge) {
        this.pledge = pledge;
    }

    public String getKeySupportArea() {
        return keySupportArea;
    }

    public void setKeySupportArea(String keySupportArea) {
        this.keySupportArea = keySupportArea;
    }

    public String getGreenLeasing() {
        return greenLeasing;
    }

    public void setGreenLeasing(String greenLeasing) {
        this.greenLeasing = greenLeasing;
    }

    public String getEpidemicPrevention() {
        return epidemicPrevention;
    }

    public void setEpidemicPrevention(String epidemicPrevention) {
        this.epidemicPrevention = epidemicPrevention;
    }

    public String getNada() {
        return nada;
    }

    public void setNada(String nada) {
        this.nada = nada;
    }

    public String getProjectAssistantPartN() {
        return projectAssistantPartN;
    }

    public void setProjectAssistantPartN(String projectAssistantPartN) {
        this.projectAssistantPartN = projectAssistantPartN;
    }

    public Double getLeaseItemAmountFrom() {
        return leaseItemAmountFrom;
    }

    public void setLeaseItemAmountFrom(Double leaseItemAmountFrom) {
        this.leaseItemAmountFrom = leaseItemAmountFrom;
    }

    public Double getLeaseItemAmountTo() {
        return leaseItemAmountTo;
    }

    public void setLeaseItemAmountTo(Double leaseItemAmountTo) {
        this.leaseItemAmountTo = leaseItemAmountTo;
    }

    public String getLeaseAccountDateFrom() {
        return leaseAccountDateFrom;
    }

    public void setLeaseAccountDateFrom(String leaseAccountDateFrom) {
        this.leaseAccountDateFrom = leaseAccountDateFrom;
    }

    public String getLeaseAccountDateTo() {
        return leaseAccountDateTo;
    }

    public void setLeaseAccountDateTo(String leaseAccountDateTo) {
        this.leaseAccountDateTo = leaseAccountDateTo;
    }

    public Long getAssistUnitId() {
        return assistUnitId;
    }

    public void setAssistUnitId(Long assistUnitId) {
        this.assistUnitId = assistUnitId;
    }

    public void setApprovalId(Long approvalId) {
        this.approvalId = approvalId;
    }

    public Long getApprovalId() {
        return approvalId;
    }

    public String getApprovalStatus() {
        return approvalStatus;
    }

    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    public String getBusinessTypeN() {
        return businessTypeN;
    }

    public void setBusinessTypeN(String businessTypeN) {
        this.businessTypeN = businessTypeN;
    }

    public String getApprovalStatusN() {
        return approvalStatusN;
    }

    public String getMarketingReportNumber() {
        return marketingReportNumber;
    }

    public void setMarketingReportNumber(String marketingReportNumber) {
        this.marketingReportNumber = marketingReportNumber;
    }

    public void setApprovalStatusN(String approvalStatusN) {
        this.approvalStatusN = approvalStatusN;
    }

    public String getMeetingType() {
        return meetingType;
    }

    public void setMeetingType(String meetingType) {
        this.meetingType = meetingType;
    }

    public String getMeetingTypeN() {
        return meetingTypeN;
    }

    public void setMeetingTypeN(String meetingTypeN) {
        this.meetingTypeN = meetingTypeN;
    }

    public Long getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(Long processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    public String getVoteStatus() {
        return voteStatus;
    }

    public void setVoteStatus(String voteStatus) {
        this.voteStatus = voteStatus;
    }

    public String getVoteComment() {
        return voteComment;
    }

    public void setVoteComment(String voteComment) {
        this.voteComment = voteComment;
    }

    public String getVoteResult() {
        return voteResult;
    }

    public void setVoteResult(String voteResult) {
        this.voteResult = voteResult;
    }

    public String getVoteStatusN() {
        return voteStatusN;
    }

    public void setVoteStatusN(String voteStatusN) {
        this.voteStatusN = voteStatusN;
    }

    public String getVoteResultN() {
        return voteResultN;
    }

    public void setVoteResultN(String voteResultN) {
        this.voteResultN = voteResultN;
    }

    private String meetingNotice;

    private String projectNoticeNumber;

    @Transient
    private String projectBpName;

    @Transient
    private Long quatationNums;

    @Transient
    private String rowSeq;

    @Transient
    private String condition;

    @Transient
    private String manageRequirements;

    @Transient
    private String riskClass;

    @Transient
    private String riskClassN;

    private String creditPeriod;

    private Date creditPeriodFrom;

    private Date creditPeriodTo;

    private String meetingProcessInstanceId;


    @Transient
    private String taskDefKey;

    @Transient
    private String warrantorName;
    @Transient
    private Date creditEffectiveDate;
    @Transient
    private Date creditExpiryDate;

    private Long examineHost;

    @Transient
    private String tenantAllName;

    @Transient
    private String projectStatusN;
    private String leaseInsureCategory;
    @Transient
    private String loanInitialLeaseN;

    private String loanInitialLease;

    private String docxFlag;
    //CREATE_CONTRACT_STATUS

    @Transient
    private String sourcePkValue1;
    @Transient
    private String sourcePkValue2;
    @Transient
    private String sourcePkValue3;

    public String getLeaseInsureCategory() {
        return leaseInsureCategory;
    }

    public void setLeaseInsureCategory(String leaseInsureCategory) {
        this.leaseInsureCategory = leaseInsureCategory;
    }

    public String getLoanInitialLeaseN() {
        return loanInitialLeaseN;
    }

    public void setLoanInitialLeaseN(String loanInitialLeaseN) {
        this.loanInitialLeaseN = loanInitialLeaseN;
    }

    public String getMeetingNotice() {
        return meetingNotice;
    }

    public void setMeetingNotice(String meetingNotice) {
        this.meetingNotice = meetingNotice;
    }

    public String getProjectNoticeNumber() {
        return projectNoticeNumber;
    }

    public void setProjectNoticeNumber(String projectNoticeNumber) {
        this.projectNoticeNumber = projectNoticeNumber;
    }

    public String getProjectBpName() {
        return projectBpName;
    }

    public void setProjectBpName(String projectBpName) {
        this.projectBpName = projectBpName;
    }

    public Long getQuatationNums() {
        return quatationNums;
    }

    public void setQuatationNums(Long quatationNums) {
        this.quatationNums = quatationNums;
    }

    public String getRowSeq() {
        return rowSeq;
    }

    public void setRowSeq(String rowSeq) {
        this.rowSeq = rowSeq;
    }

    public String getCondition() {
        return condition;
    }

    public void setCondition(String condition) {
        this.condition = condition;
    }

    public String getManageRequirements() {
        return manageRequirements;
    }

    public void setManageRequirements(String manageRequirements) {
        this.manageRequirements = manageRequirements;
    }

    public String getRiskClass() {
        return riskClass;
    }

    public void setRiskClass(String riskClass) {
        this.riskClass = riskClass;
    }

    public String getRiskClassN() {
        return riskClassN;
    }

    public void setRiskClassN(String riskClassN) {
        this.riskClassN = riskClassN;
    }

    public String getCreditPeriod() {
        return creditPeriod;
    }

    public void setCreditPeriod(String creditPeriod) {
        this.creditPeriod = creditPeriod;
    }

    public Date getCreditPeriodFrom() {
        return creditPeriodFrom;
    }

    public void setCreditPeriodFrom(Date creditPeriodFrom) {
        this.creditPeriodFrom = creditPeriodFrom;
    }

    public Date getCreditPeriodTo() {
        return creditPeriodTo;
    }

    public void setCreditPeriodTo(Date creditPeriodTo) {
        this.creditPeriodTo = creditPeriodTo;
    }

    public String getTaskDefKey() {
        return taskDefKey;
    }

    public void setTaskDefKey(String taskDefKey) {
        this.taskDefKey = taskDefKey;
    }

    public String getWarrantorName() {
        return warrantorName;
    }

    public void setWarrantorName(String warrantorName) {
        this.warrantorName = warrantorName;
    }

    public String getTenantAllName() {
        return tenantAllName;
    }

    public void setTenantAllName(String tenantAllName) {
        this.tenantAllName = tenantAllName;
    }

    public String getProjectStatusN() {
        return projectStatusN;
    }

    public void setProjectStatusN(String projectStatusN) {
        this.projectStatusN = projectStatusN;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public String getEndTaskNodeId() {
        return endTaskNodeId;
    }

    public void setEndTaskNodeId(String endTaskNodeId) {
        this.endTaskNodeId = endTaskNodeId;
    }

    public String getMarketingChannel() {
        return marketingChannel;
    }

    public void setMarketingChannel(String marketingChannel) {
        this.marketingChannel = marketingChannel;
    }

    public String getXyBranchBank() {
        return xyBranchBank;
    }

    public void setXyBranchBank(String xyBranchBank) {
        this.xyBranchBank = xyBranchBank;
    }

    public String getFalsifyCalculationMethodN() {
        return falsifyCalculationMethodN;
    }

    public void setFalsifyCalculationMethodN(String falsifyCalculationMethodN) {
        this.falsifyCalculationMethodN = falsifyCalculationMethodN;
    }

    public String getPriceNote() {
        return priceNote;
    }

    public void setPriceNote(String priceNote) {
        this.priceNote = priceNote;
    }

    public Long getCompanySpv() {
        return companySpv;
    }

    public void setCompanySpv(Long companySpv) {
        this.companySpv = companySpv;
    }

    public String getCompanySpvN() {
        return companySpvN;
    }

    public void setCompanySpvN(String companySpvN) {
        this.companySpvN = companySpvN;
    }

    private String  contractSigningTimes;

    public String getPowerfulPerson() {
        return powerfulPerson;
    }

    public void setPowerfulPerson(String powerfulPerson) {
        this.powerfulPerson = powerfulPerson;
    }
    @Transient
    private String vetoAdvice;

    @Transient
    private String approveResult;

    @Transient
    private Long prjSurviveId;

    @Transient
    private Long creditConditionId;

    private Long allocationIdRisk;

    @Transient
    private String allocationIdRiskN;

    private String reviewComments;

    @Transient
    private Double useAmount;

    @Transient
    private String changeType;

    @Transient
    private String approveNumber;

    @Transient
    private String changeInfoDesc;

    @Transient
    private String changeEffctDesc;

    private String noticeApproveVeto;

    private String meetingNoticeResult;

    @Transient
    private Long prjNoticeId;

    @Transient
    private String prjNoticeIdN;

    @Transient
    private Long prjSuppleId;

    @Transient
    private String  prjSuppleNumber;

    @Transient
    private String suppleStatus;

    @Transient
    private String suppleStatusN;

    @Transient
    private Date suppleSubmitDate;

    @Transient
    private Date approveDate ;

    @Transient
    private Date approvedTimeFrom ;
    @Transient
    private Date approvedTimeTo ;

    private String  rentCardinality;

    private String  terminationCardinality;

    @Transient
    private String  rentCardinalityN;

    @Transient
    private String  terminationCardinalityN;

    @Transient
    private Double stampAmount;

    @Transient
    private String  employeeEnableFlag;


    @Transient
    private String  supplementaryPass;

    @Transient
    private String  creditUpNow;

    private String instanceEndFlag;

    @Transient
    private String finLoanInitialLease;

    @Transient
    private String finLoanInitialLeaseN;

    @Transient
    private Long prjVetoId;

    @Transient
    private String  exemptionCause;

    @Transient
    private String  ifPracticable;

    @Transient
    private String  ifImmunity;

    @Transient
    private Date contractCreationDate;
    private Date contractEndDate;

    @Transient
    private Date creationDateFrom;
    @Transient
    private Date creationDateTo;

    @Transient
    private String financialLeaseStatus;

    @Transient
    private Date firstReleaseDate;
    @Transient
    private String companyIdN;
    @Transient
    private Long companyId;
    @Transient
    private Date firstPayDate;
    @Transient
    private String bondedLeaseFlag;

    private Long terminateNoticeTimes;

    private String terminateApprovalStatus;

    @Transient
    private String terminateApprovalStatusN;
    @Transient
    private String currencyN;

    //立项新增字段同步
    private String industry;
    private String industryType;
    private String city;

    @Transient
    private String cityN;
    @Transient
    private String votingResult;
    @Transient
    private Long numberPassers;
    @Transient
    private Long numberFailures;
    @Transient
    private Long numberConditiona;


    private String spotCheckDesc;


    private String riskInvestDesc;
    private Date meetingTime;

    @Transient
    private String industryTypeN;

    private Long riskAllocationId;
    private Long legalAllocationId;

    private String postItfcFlag;
    private String itfcDocument;
    private String postItfcCode;
    private String postItfcMsg;
    private Date postApprovedDate;
    private Date creationDate;

    @Transient
    private String creditLineNumber;
    @Transient
    private String creditBpName;
    @Transient
    private Double creditAmt;

    @Transient
    private String quotaType;

    @Transient
    private Long definitionId;

    public String getBondedLeaseFlag() {
        return bondedLeaseFlag;
    }

    public void setBondedLeaseFlag(String bondedLeaseFlag) {
        this.bondedLeaseFlag = bondedLeaseFlag;
    }

    public Date getFirstPayDate() {
        return firstPayDate;
    }

    public void setFirstPayDate(Date firstPayDate) {
        this.firstPayDate = firstPayDate;
    }

    public String getInstanceEndFlag() {
        return instanceEndFlag;
    }

    public void setInstanceEndFlag(String instanceEndFlag) {
        this.instanceEndFlag = instanceEndFlag;
    }

    private String rentNumberSeq;

    public String getIndustryCategory() {
        return industryCategory;
    }

    public void setIndustryCategory(String industryCategory) {
        this.industryCategory = industryCategory;
    }

    private String applyBusinessType;

    @Transient
    private String applyBusinessTypeN;

    public String getRentNumberSeq() {
        return rentNumberSeq;
    }

    public void setRentNumberSeq(String rentNumberSeq) {
        this.rentNumberSeq = rentNumberSeq;
    }

    public String getApplyBusinessType() {
        return applyBusinessType;
    }

    public void setApplyBusinessType(String applyBusinessType) {
        this.applyBusinessType = applyBusinessType;
    }

    public String getApplyBusinessTypeN() {
        return applyBusinessTypeN;
    }

    public void setApplyBusinessTypeN(String applyBusinessTypeN) {
        this.applyBusinessTypeN = applyBusinessTypeN;
    }

    public Date getContractEndDate() {
        return contractEndDate;
    }

    public void setContractEndDate(Date contractEndDate) {
        this.contractEndDate = contractEndDate;
    }

    public String getCreditFlagN() {
        return creditFlagN;
    }

    public void setCreditFlagN(String creditFlagN) {
        this.creditFlagN = creditFlagN;
    }

    private Long creditTenantId;//额度占用选择的承租人
    @Transient
    private Long creditTenantIdN;
    private Long creditChanceBpId;
    private String description;
    @Transient
    private Double tenantCreditAmount;
    @Transient
    private Double tenantCreditAmountUsed;
    @Transient
    private Double tenantCreditAmountAvailable;

    @Transient
    private Double creditAmtAvailable;
    @Transient
    private String changeReqNumber;
    @Transient
    private Long sourceProjectId;
    @Transient
    private Double nonCyclicalAmount;
    @Transient
    private Double cyclicalAmount;

    private String penetrateId;
    private String alipayStatus;


    private Long riskSubmitValueTime; //风控审核提交有效期

    private Long loanSubmitValueTime; //放款申请提交有效期

    private Long loanSubmitValueSecondTime; //再次放款申请提交有效期

    private Long compenDay; //代偿天数

    private Long buyBackDay; //回购天数

    private String factoringType;
    @Transient
    private String factoringTypeN;
    private String factoringCategory;
    @Transient
    private String factoringCategoryN;
    private String factoringRecourse;
    @Transient
    private String factoringRecourseN;
    private String factoringOpen;
    @Transient
    private String factoringOpenN;
    private String prjInfoDesc;
    private String creditorAnalyse;
    private String debtorAnalyse;
    private String otherDesc;
    private String creditMeasures;

    private Long virConProcessInstatnceId; //保理合同工作流实例ID
    private Long financeChargeId; //财务部负责人ID
    @Transient
    private String paymentApprovedStatus;

    private String contractContentNumber; //合同用印份数

    private String contractSignAddress; //合同签订地点

    private Date contractSignTimes; //合同签订日期

    private String contractSpecialCondit; //合同特别约定条款

    private String contractOutLawName;  //外聘律师事务所机构名称

    private String contractOutLawReviewer; //外聘律师事务所审查人

    private Date contractOutLawDate; //外聘律师事务所审查日期

    private String contractOutLawComment; //外聘律师事务所审查意见

}
