package com.hand.hls.prj.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "prj_project_bp")
@Getter
@Setter
public class HlsCusPrjProjectBp extends BaseDTO {

    public static final String FIELD_PRJ_BP_ID = "prjBpId";
    public static final String FIELD_CHANCE_ID = "chanceId";
    public static final String FIELD_PROJECT_ID = "projectId";
    public static final String FIELD_BP_CATEGROY = "bpCategroy";
    public static final String FIELD_BP_TYPE = "bpType";
    public static final String FIELD_BP_ID = "bpId";

    @Id
    @GeneratedValue
    private Long prjBpId; //租赁商业伙伴ID



    public String getBankAccountNum() {
        return bankAccountNum;
    }

    public void setBankAccountNum(String bankAccountNum) {
        this.bankAccountNum = bankAccountNum;
    }

    public String getBankAccountName() {
        return bankAccountName;
    }

    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    public String getBankFullName() {
        return bankFullName;
    }

    public void setBankFullName(String bankFullName) {
        this.bankFullName = bankFullName;
    }

    @NotNull
    private Long chanceId; //立项ID

    @NotNull
    private Long projectId; //租赁ID

    @Length(max = 255)
    private String bpCategroy; //商业伙伴类别

    @Length(max = 255)
    private String bpType; //商业伙伴类型

    private Long bpId;
    private String remarks;
    @Length(max = 255)
    private String guaranteeType;//担保方式

    private Double guaranteeAmount;//担保金额

    private Double valueAmount;//价值金额/可提供抵押金额

    private Double pledgeRate;//抵押率/质押率

    private String bpRoleType;//项目商业伙伴类型[客户信息/抵押信息/质押信息/保证信息]

    private String isCreditFlag;
    private String refV02;
    private String refV03;
    @Transient
    private String refV02N;
    @Transient
    private String tenantName;
    @Transient
    private String allocatFlag;

    public String getRefV02() {
        return refV02;
    }

    public void setRefV02(String refV02) {
        this.refV02 = refV02;
    }

    public String getRefV03() {
        return refV03;
    }

    public void setRefV03(String refV03) {
        this.refV03 = refV03;
    }

    @Length(max = 255)
    private String description;//备注

    @Transient
    private String bankAccountIdN;
    @Transient
    private String contactInfoIdN;
    @Transient
    private String addressIdN;
    @Transient
    private String bpCodeN;
    @Transient
    private String bpTypeN;

    @Transient
    private String bpName;//商业伙伴名称
    @Transient
    private String saveFlag;//暂存标志
    @Transient
    private String bpCode;//商业伙伴编号
    @Transient
    private String bpTypeDesc;//商业伙伴类型
    @Transient
    private String exBpRoleType;//排除质押，抵押，保证等信息
    @Transient
    private String bpClass;
    @Transient
    private String phone;
    @Transient
    private String taxpayerType;
    @Transient
    private String invoiceTitle;
    @Transient
    private String invoiceBpAddressPhoneNum;
    @Transient
    private String invoiceBpBankAccount;
    @Transient
    private String prjRole;
    @Transient
    private String loanCardNum;
    @Transient
    private String idType;
    @Transient
    private String communalCurrencyDesc;
    @Transient
    private String guaranteeTypeDesc;
    @Transient
    private String npGuaranteeTypeDesc;
    @Transient
    private String securedPartyDesc;
    @Transient
    private String communalOtherCurrencyDesc;
    @Transient
    private String collateralTypeDesc;
    @Transient
    private String taxpayerTypeDesc;

    @Transient
    private String bpIdN;
    @Transient
    private String communalOtherCurrencyN;
    @Transient
    private String collateralTypeN;
    @Transient
    private String communalCurrencyN;
    @Transient
    private String guaranteeTypeN;
    @Transient
    private String npGuaranteeTypeN;
    @Transient
    private String securedPartyN;
    @Transient
    private Long companyId;
    /**
     * 20230407新增：信用评级
     */
    @Transient
    private Long creditGrade;
    @Transient
    private String creditGradeN;

//    private String lease_item_id;
    private String leaseItemId;

    @Transient
    private Long marketingReportId;

    @Transient
    private Long checkId;
    private String groupCompanies;

    private Double creditAmount;
    public Double getCreditAmount() {
        return creditAmount;
    }

    public void setCreditAmount(Double creditAmount) {
        this.creditAmount = creditAmount;
    }

    public String getGroupCompanies() {
        return groupCompanies;
    }

    public void setGroupCompanies(String groupCompanies) {
        this.groupCompanies = groupCompanies;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public static String getFieldPrjBpId() {
        return FIELD_PRJ_BP_ID;
    }

    public static String getFieldChanceId() {
        return FIELD_CHANCE_ID;
    }

    public static String getFieldProjectId() {
        return FIELD_PROJECT_ID;
    }

    public static String getFieldBpCategroy() {
        return FIELD_BP_CATEGROY;
    }

    public static String getFieldBpType() {
        return FIELD_BP_TYPE;
    }

    public static String getFieldBpId() {
        return FIELD_BP_ID;
    }

    public String getBpClass() {
        return bpClass;
    }

    public void setBpClass(String bpClass) {
        this.bpClass = bpClass;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getTaxpayerType() {
        return taxpayerType;
    }

    public void setTaxpayerType(String taxpayerType) {
        this.taxpayerType = taxpayerType;
    }

    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle;
    }

    public String getInvoiceBpAddressPhoneNum() {
        return invoiceBpAddressPhoneNum;
    }

    public void setInvoiceBpAddressPhoneNum(String invoiceBpAddressPhoneNum) {
        this.invoiceBpAddressPhoneNum = invoiceBpAddressPhoneNum;
    }

    public String getInvoiceBpBankAccount() {
        return invoiceBpBankAccount;
    }

    public void setInvoiceBpBankAccount(String invoiceBpBankAccount) {
        this.invoiceBpBankAccount = invoiceBpBankAccount;
    }

    public String getPrjRole() {
        return prjRole;
    }

    public void setPrjRole(String prjRole) {
        this.prjRole = prjRole;
    }

    public String getLoanCardNum() {
        return loanCardNum;
    }

    public void setLoanCardNum(String loanCardNum) {
        this.loanCardNum = loanCardNum;
    }

    public String getIdType() {
        return idType;
    }

    public void setIdType(String idType) {
        this.idType = idType;
    }

    public String getIdCardNo() {
        return idCardNo;
    }

    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    @Transient

    private String idCardNo;
    /**
     * 2018-11-29 添加字段
     * 保证币种/抵押币种/质押币种
     */
    private String communalCurrency;
    /**
     * 抵押的评估币种/质押的质押物币种
     */
    private String communalOtherCurrency;
    /**
     * 抵押物评估值/质押物价值
     */
    private String communalValue;
    /**
     * 抵押评估日期
     * MORTGAGE_EVALUATION_DATE
     */
    private Date mortgageEvaluationDate;
    /**
     * 抵押评估机构名称
     * MORTGAGE_EVALUATION_NAME
     */
    private String mortgageEvaluationName;
    /**
     * 抵押评估机构组织机构代码
     * MORTGAGE_EVALUATION_CODE
     */
    private String mortgageEvaluationCode;
    /**
     * 抵押物种类/质押物类型
     * COLLATERAL_TYPE
     */
    private String collateralType;
    /**
     * 登记机关
     * REGISTRATION_AUTHORITY
     */
    private String registrationAuthority;
    /**
     * 登记日期
     * REGISTRATION_DATE
     */
    private Date registrationDate;
    /**
     * 抵押物说明
     * MORTGAGE_DESC
     */
    private String mortgageDesc;
    /**
     * 信贷系统担保物的编码/信贷系统质押物编号【
     * COLLATERAL_CODE
     */
    private String collateralCode;

    /**
     * 地址【外键】
     */
    private Long addressId;
    /**
     * 联系人【外键】
     */
    private Long contactInfoId;
    /**
     * 银行账户Id
     */
    private Long bankAccountId;

    /**
     * 自然人担保形式
     */
    private String npGuaranteeType;

    /**
     * 合同编码
     */
    private String contractNumber;

    /**
     * 合同流水号
     */
    private String serialNumber;

    /**
     * 被担保方
     */
    private String securedParty;

    /**
     * 到期日
     */

    private Date expiryDate;
    private String contactInfo;
    private String addressInfo;
    private String bankAccountNum;
    private String bankAccountName;
    private String bankFullName;
    @Transient
    private Long bpSeq;
    @Transient
    private String bpEngName;
    @Transient
    private String extraNam;
    @Transient
    private String bpClassN;
    @Transient
    private String registeredCapital;
    @Transient
    private String paidInCapital;
    @Transient
    private String registerCapitalCur;
    @Transient
    private Date foundedDate;
    @Transient
    private String registrationNumType;
    @Transient
    private String registerCertNum;
    @Transient
    private Date operatingPeriodEnd;
    @Transient
    private String groupCustomers;
    @Transient
    private String legalPerson;
    @Transient
    private String actualController;
    //@Transient
    private String economicInduClassify;
    @Transient
    private String exclusiveTrade;
    @Transient
    private String customerNature;
    @Transient
    private String enterpriseNature;
    @Transient
    private String enterpriseScale;
    @Transient
    private String economicZone;
    @Transient
    private String listedCompany;
    @Transient
    private String organizationType;
    @Transient
    private String organizationTypeDetails;
    @Transient
    private String creditCustomer;
    @Transient
    private Long customerNumber;
    @Transient
    private String bpFinancialType;
    @Transient
    private String swift;
    @Transient
    private String localFinance;
    @Transient
    private String exitFinancing;

    @Transient
    private String nationality;

    @Transient
    private String country;

    @Transient
    private String countryN;

    @Transient
    private String province;

    @Transient
    private String provinceN;

    @Transient
    private String city;

    @Transient
    private String cityN;

    @Transient
    private String economicInduClassifyN;

    @Transient
    private String strategicBpType;

    @Transient
    private String strategicBpTypeN;

    @Transient
    private String identificationResultO;

    @Transient
    private String identificationResultON;
    private Double pledgeProportion;

    @Transient
    private String paidUpCapital;

    @Transient
    private String tenantFlag;

    @Transient
    private String industry;
    @Transient
    private String industryN;

    public String getTenantFlag() {
        return tenantFlag;
    }

    public void setTenantFlag(String tenantFlag) {
        this.tenantFlag = tenantFlag;
    }

    public Double getPledgeProportion() {
        return pledgeProportion;
    }

    public void setPledgeProportion(Double pledgeProportion) {
        this.pledgeProportion = pledgeProportion;
    }

    public String getBpRoleType() {
        return bpRoleType;
    }

    public void setBpRoleType(String bpRoleType) {
        this.bpRoleType = bpRoleType;
    }

    /**
     * 被担保方
     */
    public void setPrjBpId(Long prjBpId) {
        this.prjBpId = prjBpId;
    }

    public Long getPrjBpId() {
        return prjBpId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setBpCategroy(String bpCategroy) {
        this.bpCategroy = bpCategroy;
    }

    public String getBpCategroy() {
        return bpCategroy;
    }

    public void setBpType(String bpType) {
        this.bpType = bpType;
    }

    public String getBpType() {
        return bpType;
    }

    public void setBpId(Long bpId) {
        this.bpId = bpId;
    }

    public Long getBpId() {
        return bpId;
    }

    public String getBpName() {
        return bpName;
    }

    public void setBpName(String bpName) {
        this.bpName = bpName;
    }

    public String getBpCode() {
        return bpCode;
    }

    public void setBpCode(String bpCode) {
        this.bpCode = bpCode;
    }

    public String getBpTypeDesc() {
        return bpTypeDesc;
    }

    public void setBpTypeDesc(String bpTypeDesc) {
        this.bpTypeDesc = bpTypeDesc;
    }

    public Long getChanceId() {
        return chanceId;
    }

    public void setChanceId(Long chanceId) {
        this.chanceId = chanceId;
    }

    public String getGuaranteeType() {
        return guaranteeType;
    }

    public void setGuaranteeType(String guaranteeType) {
        this.guaranteeType = guaranteeType;
    }

    public Double getGuaranteeAmount() {
        return guaranteeAmount;
    }

    public void setGuaranteeAmount(Double guaranteeAmount) {
        this.guaranteeAmount = guaranteeAmount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCommunalCurrency() {
        return communalCurrency;
    }

    public void setCommunalCurrency(String communalCurrency) {
        this.communalCurrency = communalCurrency;
    }

    public String getCommunalOtherCurrency() {
        return communalOtherCurrency;
    }

    public void setCommunalOtherCurrency(String communalOtherCurrency) {
        this.communalOtherCurrency = communalOtherCurrency;
    }

    public String getCommunalValue() {
        return communalValue;
    }

    public void setCommunalValue(String communalValue) {
        this.communalValue = communalValue;
    }

    public Date getMortgageEvaluationDate() {
        return mortgageEvaluationDate;
    }

    public void setMortgageEvaluationDate(Date mortgageEvaluationDate) {
        this.mortgageEvaluationDate = mortgageEvaluationDate;
    }

    public String getMortgageEvaluationName() {
        return mortgageEvaluationName;
    }

    public void setMortgageEvaluationName(String mortgageEvaluationName) {
        this.mortgageEvaluationName = mortgageEvaluationName;
    }

    public String getMortgageEvaluationCode() {
        return mortgageEvaluationCode;
    }

    public void setMortgageEvaluationCode(String mortgageEvaluationCode) {
        this.mortgageEvaluationCode = mortgageEvaluationCode;
    }

    public String getCollateralType() {
        return collateralType;
    }

    public void setCollateralType(String collateralType) {
        this.collateralType = collateralType;
    }

    public String getRegistrationAuthority() {
        return registrationAuthority;
    }

    public void setRegistrationAuthority(String registrationAuthority) {
        this.registrationAuthority = registrationAuthority;
    }

    public Date getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    public String getMortgageDesc() {
        return mortgageDesc;
    }

    public void setMortgageDesc(String mortgageDesc) {
        this.mortgageDesc = mortgageDesc;
    }

    public String getCollateralCode() {
        return collateralCode;
    }

    public void setCollateralCode(String collateralCode) {
        this.collateralCode = collateralCode;
    }

    public Long getAddressId() {
        return addressId;
    }

    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    public Long getContactInfoId() {
        return contactInfoId;
    }

    public void setContactInfoId(Long contactInfoId) {
        this.contactInfoId = contactInfoId;
    }

    public Long getBankAccountId() {
        return bankAccountId;
    }

    public void setBankAccountId(Long bankAccountId) {
        this.bankAccountId = bankAccountId;
    }

    public String getNpGuaranteeType() {
        return npGuaranteeType;
    }

    public void setNpGuaranteeType(String npGuaranteeType) {
        this.npGuaranteeType = npGuaranteeType;
    }

    public String getContractNumber() {
        return contractNumber;
    }

    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public String getSecuredParty() {
        return securedParty;
    }

    public void setSecuredParty(String securedParty) {
        this.securedParty = securedParty;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public String getContactInfo() {
        return contactInfo;
    }

    public void setContactInfo(String contactInfo) {
        this.contactInfo = contactInfo;
    }

    public String getAddressInfo() {
        return addressInfo;
    }

    public void setAddressInfo(String addressInfo) {
        this.addressInfo = addressInfo;
    }

    public Double getValueAmount() {
        return valueAmount;
    }

    public void setValueAmount(Double valueAmount) {
        this.valueAmount = valueAmount;
    }

    public Double getPledgeRate() {
        return pledgeRate;
    }

    public void setPledgeRate(Double pledgeRate) {
        this.pledgeRate = pledgeRate;
    }

    public String getExBpRoleType() {
        return exBpRoleType;
    }

    public void setExBpRoleType(String exBpRoleType) {
        this.exBpRoleType = exBpRoleType;
    }

    public String getSaveFlag() {
        return saveFlag;
    }

    public void setSaveFlag(String saveFlag) {
        this.saveFlag = saveFlag;
    }

    public String getIsCreditFlag() {
        return isCreditFlag;
    }

    public void setIsCreditFlag(String isCreditFlag) {
        this.isCreditFlag = isCreditFlag;
    }

    public String getCommunalCurrencyDesc() {
        return communalCurrencyDesc;
    }

    public void setCommunalCurrencyDesc(String communalCurrencyDesc) {
        this.communalCurrencyDesc = communalCurrencyDesc;
    }

    public String getGuaranteeTypeDesc() {
        return guaranteeTypeDesc;
    }

    public void setGuaranteeTypeDesc(String guaranteeTypeDesc) {
        this.guaranteeTypeDesc = guaranteeTypeDesc;
    }

    public String getNpGuaranteeTypeDesc() {
        return npGuaranteeTypeDesc;
    }

    public void setNpGuaranteeTypeDesc(String npGuaranteeTypeDesc) {
        this.npGuaranteeTypeDesc = npGuaranteeTypeDesc;
    }

    public String getSecuredPartyDesc() {
        return securedPartyDesc;
    }

    public void setSecuredPartyDesc(String securedPartyDesc) {
        this.securedPartyDesc = securedPartyDesc;
    }

    public String getCommunalOtherCurrencyDesc() {
        return communalOtherCurrencyDesc;
    }

    public void setCommunalOtherCurrencyDesc(String communalOtherCurrencyDesc) {
        this.communalOtherCurrencyDesc = communalOtherCurrencyDesc;
    }

    public String getCollateralTypeDesc() {
        return collateralTypeDesc;
    }

    public void setCollateralTypeDesc(String collateralTypeDesc) {
        this.collateralTypeDesc = collateralTypeDesc;
    }

    public String getTaxpayerTypeDesc() {
        return taxpayerTypeDesc;
    }

    public void setTaxpayerTypeDesc(String taxpayerTypeDesc) {
        this.taxpayerTypeDesc = taxpayerTypeDesc;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getBankAccountIdN() {
        return bankAccountIdN;
    }

    public String getBpIdN() {
        return bpIdN;
    }

    public void setBpIdN(String bpIdN) {
        this.bpIdN = bpIdN;
    }

    public String getCommunalOtherCurrencyN() {
        return communalOtherCurrencyN;
    }

    public void setCommunalOtherCurrencyN(String communalOtherCurrencyN) {
        this.communalOtherCurrencyN = communalOtherCurrencyN;
    }

    public String getCollateralTypeN() {
        return collateralTypeN;
    }

    public void setCollateralTypeN(String collateralTypeN) {
        this.collateralTypeN = collateralTypeN;
    }

    public String getCommunalCurrencyN() {
        return communalCurrencyN;
    }

    public void setCommunalCurrencyN(String communalCurrencyN) {
        this.communalCurrencyN = communalCurrencyN;
    }

    public String getGuaranteeTypeN() {
        return guaranteeTypeN;
    }

    public void setGuaranteeTypeN(String guaranteeTypeN) {
        this.guaranteeTypeN = guaranteeTypeN;
    }

    public String getNpGuaranteeTypeN() {
        return npGuaranteeTypeN;
    }

    public void setNpGuaranteeTypeN(String npGuaranteeTypeN) {
        this.npGuaranteeTypeN = npGuaranteeTypeN;
    }

    public String getSecuredPartyN() {
        return securedPartyN;
    }

    public void setSecuredPartyN(String securedPartyN) {
        this.securedPartyN = securedPartyN;
    }

    public void setBankAccountIdN(String bankAccountIdN) {
        this.bankAccountIdN = bankAccountIdN;
    }

    public String getContactInfoIdN() {
        return contactInfoIdN;
    }

    public void setContactInfoIdN(String contactInfoIdN) {
        this.contactInfoIdN = contactInfoIdN;
    }

    public String getAddressIdN() {
        return addressIdN;
    }

    public void setAddressIdN(String addressIdN) {
        this.addressIdN = addressIdN;
    }

    public String getBpCodeN() {
        return bpCodeN;
    }

    public void setBpCodeN(String bpCodeN) {
        this.bpCodeN = bpCodeN;
    }

    public String getBpTypeN() {
        return bpTypeN;
    }

    public void setBpTypeN(String bpTypeN) {
        this.bpTypeN = bpTypeN;
    }

    public Long getBpSeq() {
        return bpSeq;
    }

    public void setBpSeq(Long bpSeq) {
        this.bpSeq = bpSeq;
    }

    public String getBpEngName() {
        return bpEngName;
    }

    public void setBpEngName(String bpEngName) {
        this.bpEngName = bpEngName;
    }

    public String getExtraNam() {
        return extraNam;
    }

    public void setExtraNam(String extraNam) {
        this.extraNam = extraNam;
    }

    public String getBpClassN() {
        return bpClassN;
    }

    public void setBpClassN(String bpClassN) {
        this.bpClassN = bpClassN;
    }

    public String getRegisteredCapital() {
        return registeredCapital;
    }

    public void setRegisteredCapital(String registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    public String getPaidInCapital() {
        return paidInCapital;
    }

    public void setPaidInCapital(String paidInCapital) {
        this.paidInCapital = paidInCapital;
    }

    public String getRegisterCapitalCur() {
        return registerCapitalCur;
    }

    public void setRegisterCapitalCur(String registerCapitalCur) {
        this.registerCapitalCur = registerCapitalCur;
    }

    public Date getFoundedDate() {
        return foundedDate;
    }

    public void setFoundedDate(Date foundedDate) {
        this.foundedDate = foundedDate;
    }

    public String getRegistrationNumType() {
        return registrationNumType;
    }

    public void setRegistrationNumType(String registrationNumType) {
        this.registrationNumType = registrationNumType;
    }

    public String getRegisterCertNum() {
        return registerCertNum;
    }

    public void setRegisterCertNum(String registerCertNum) {
        this.registerCertNum = registerCertNum;
    }

    public Date getOperatingPeriodEnd() {
        return operatingPeriodEnd;
    }

    public void setOperatingPeriodEnd(Date operatingPeriodEnd) {
        this.operatingPeriodEnd = operatingPeriodEnd;
    }

    public String getGroupCustomers() {
        return groupCustomers;
    }

    public void setGroupCustomers(String groupCustomers) {
        this.groupCustomers = groupCustomers;
    }

    public String getLegalPerson() {
        return legalPerson;
    }

    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    public String getActualController() {
        return actualController;
    }

    public void setActualController(String actualController) {
        this.actualController = actualController;
    }

    public String getEconomicInduClassify() {
        return economicInduClassify;
    }

    public void setEconomicInduClassify(String economicInduClassify) {
        this.economicInduClassify = economicInduClassify;
    }

    public String getExclusiveTrade() {
        return exclusiveTrade;
    }

    public void setExclusiveTrade(String exclusiveTrade) {
        this.exclusiveTrade = exclusiveTrade;
    }

    public String getCustomerNature() {
        return customerNature;
    }

    public void setCustomerNature(String customerNature) {
        this.customerNature = customerNature;
    }

    public String getEnterpriseNature() {
        return enterpriseNature;
    }

    public void setEnterpriseNature(String enterpriseNature) {
        this.enterpriseNature = enterpriseNature;
    }

    public String getEnterpriseScale() {
        return enterpriseScale;
    }

    public void setEnterpriseScale(String enterpriseScale) {
        this.enterpriseScale = enterpriseScale;
    }

    public String getEconomicZone() {
        return economicZone;
    }

    public void setEconomicZone(String economicZone) {
        this.economicZone = economicZone;
    }

    public String getListedCompany() {
        return listedCompany;
    }

    public void setListedCompany(String listedCompany) {
        this.listedCompany = listedCompany;
    }

    public String getOrganizationType() {
        return organizationType;
    }

    public void setOrganizationType(String organizationType) {
        this.organizationType = organizationType;
    }

    public String getOrganizationTypeDetails() {
        return organizationTypeDetails;
    }

    public void setOrganizationTypeDetails(String organizationTypeDetails) {
        this.organizationTypeDetails = organizationTypeDetails;
    }

    public String getCreditCustomer() {
        return creditCustomer;
    }

    public void setCreditCustomer(String creditCustomer) {
        this.creditCustomer = creditCustomer;
    }

    public Long getCustomerNumber() {
        return customerNumber;
    }

    public void setCustomerNumber(Long customerNumber) {
        this.customerNumber = customerNumber;
    }

    public String getBpFinancialType() {
        return bpFinancialType;
    }

    public void setBpFinancialType(String bpFinancialType) {
        this.bpFinancialType = bpFinancialType;
    }

    public String getSwift() {
        return swift;
    }

    public void setSwift(String swift) {
        this.swift = swift;
    }

    public String getLocalFinance() {
        return localFinance;
    }

    public void setLocalFinance(String localFinance) {
        this.localFinance = localFinance;
    }

    public String getExitFinancing() {
        return exitFinancing;
    }

    public void setExitFinancing(String exitFinancing) {
        this.exitFinancing = exitFinancing;
    }

/*
    public String getLease_item_id() {
        return lease_item_id;
    }

    public void setLease_item_id(String lease_item_id) {
        this.lease_item_id = lease_item_id;
    }
*/

    public String getLeaseItemId() {
        return leaseItemId;
    }

    public void setLeaseItemId(String leaseItemId) {
        this.leaseItemId = leaseItemId;
    }

    public Long getMarketingReportId() {
        return marketingReportId;
    }

    public void setMarketingReportId(Long marketingReportId) {
        this.marketingReportId = marketingReportId;
    }

    public String getNationality() {
        return nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCountryN() {
        return countryN;
    }

    public void setCountryN(String countryN) {
        this.countryN = countryN;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getProvinceN() {
        return provinceN;
    }

    public void setProvinceN(String provinceN) {
        this.provinceN = provinceN;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCityN() {
        return cityN;
    }

    public void setCityN(String cityN) {
        this.cityN = cityN;
    }

    public String getEconomicInduClassifyN() {
        return economicInduClassifyN;
    }

    public void setEconomicInduClassifyN(String economicInduClassifyN) {
        this.economicInduClassifyN = economicInduClassifyN;
    }

    public String getStrategicBpType() {
        return strategicBpType;
    }

    public void setStrategicBpType(String strategicBpType) {
        this.strategicBpType = strategicBpType;
    }

    public String getStrategicBpTypeN() {
        return strategicBpTypeN;
    }

    public void setStrategicBpTypeN(String strategicBpTypeN) {
        this.strategicBpTypeN = strategicBpTypeN;
    }

    public String getIdentificationResultO() {
        return identificationResultO;
    }

    public void setIdentificationResultO(String identificationResultO) {
        this.identificationResultO = identificationResultO;
    }

    public String getIdentificationResultON() {
        return identificationResultON;
    }

    public void setIdentificationResultON(String identificationResultON) {
        this.identificationResultON = identificationResultON;
    }


    public String getPaidUpCapital() {
        return paidUpCapital;
    }

    public void setPaidUpCapital(String paidUpCapital) {
        this.paidUpCapital = paidUpCapital;
    }
}
