package com.hand.hls.prj.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "prj_lease_item_condition")
@Getter
@Setter
public class PrjProjectLeaseItemCondition extends BaseDTO {

    public static final String FIELD_PROJECT_LEASE_ITEM_ID = "projectLeaseItemId";//外键-租赁物主键
    public static final String FIELD_CONDITION_ID = "conditionId";//主键
    public static final String FIELD_IS_WATER_DAMAGED = "isWaterDamaged";//是否水泡
    public static final String FIELD_IS_CONVERSION = "isConversion";//是否营转非
    public static final String FIELD_IS_VEHICLE_DAMAGE = "isVehicleDamage";//是否有车损险
    public static final String FIELD_VEHICLE_END_DATE = "vehicleEndDate";//车损险到期日期
    public static final String FIELD_ACCIDENT_STATUS = "accidentStatus";//事故状况
    public static final String FIELD_IS_THIRD_PARTY = "isThirdParty";//是否有第三者责任险
    public static final String FIELD_THIRD_END_DATE = "thirdEndDate";//第三者责任险到期日期
    public static final String FIELD_IS_ANNUAL_INSPECTION = "isAnnualInspection";//是否年检
    public static final String FIELD_IS_SIGNIFICANTLY_MODIFIED = "isSignificantlyModified";//是否重大改装车
    public static final String FIELD_ENGINE_OVERHAUL = "engineOverhaul";//发动机大修
    public static final String FIELD_PREMIUM_ADD_ON = "premiumAddOn";//精品加装
    public static final String FIELD_MAINTENANCE_INFO = "maintenanceInfo";//维修保养情况
    public static final String FIELD_ORIGINAL_OWNER_CARD_TYPE = "originalOwnerCardType";//原车主证件类型
    public static final String FIELD_ORIGINAL_OWNER_NAME = "originalOwnerName";//原车主姓名
    public static final String FIELD_ORIGINAL_OWNER_CARD_NUM = "originalOwnerCardNum";//原车主证件号
    public static final String FIELD_ORIGINAL_OWNER_ADDRESS = "originalOwnerAddress";//原车主户籍所在地

    @Id
    @GeneratedValue
    private Long conditionId; //主键
    @NotNull
    private Long projectLeaseItemId;

    private String isWaterDamaged; //是否水泡

    private String isConversion; //是否营转非

    private String isVehicleDamage; //是否有车损险

    private Date vehicleEndDate; //车损险到期日期

    private String accidentStatus; //事故状况

    private String isThirdParty; //是否有第三者责任险

    private Date thirdEndDate; //第三者责任险到期日期
    private String isAnnualInspection; //是否年检
    private String isSignificantlyModified; //是否重大改装车
    private String engineOverhaul; //发动机大修
    private String premiumAddOn; //精品加装
    private String maintenanceInfo; //维修保养情况
    private String originalOwnerCardType; //原车主证件类型
    private String originalOwnerName; //原车主姓名
    private String originalOwnerCardNum; //原车主证件号
    private String originalOwnerAddress; //原车主户籍所在地

}
