package com.hand.hls.prj.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(
        disable = true
)
@Table(
        name = "prj_project"
)
@Getter
@Setter
public class PrjProject extends BaseDTO {
    @Id
    @GeneratedValue
    private Long projectId;
    @NotNull
    private Long companyId;
    private String documentType;
    private String documentCategory;
    private String businessType;
    @NotEmpty
    @Condition(
            operator = "LIKE"
    )
    private String projectNumber;
    @Condition(
            operator = "LIKE"
    )
    private String projectName;
    private String projectStatus;
    private String leaseChannel;
    private String division;
    private Long employeeId;
    private Long unitId;
    private Double financeAmount;
    private Date leaseStartDate;
    private String financingPurpose;
    private String currency;
    private String comprehensiveOpinion;
    private String authorityRuleString;
    private String leaseItemType;
    private String alipayStatus;
    @Transient
    private List divisionParam;
    @Transient
    private String alipayStatusN;//代扣签约状态
    @Transient
    private List prjTypeParam;
    @Transient
    private List prjStatusParam;
    @Transient
    private Long userId;
    @Transient
    private Long bpId;
    @Transient
    private String bpName;
    @Transient
    private String bpNumber;
    @Transient
    private String tenantName;
    @Transient
    private String documentTypeDesc;
    @Transient
    private String projectStatusDesc;
    @Transient
    private String creditLineAmtFormat;
    @Transient
    private String creditExposureAmtFormat;
    @Transient
    private Double creditLineAmt;
    @Transient
    private Double creditExposureAmt;
    @Transient
    private Integer creditExposureQty;
    @Transient
    private String collectFlag;
    @Transient
    private String projectMeetingId;
    @Transient
    private String companyFullName;
    @Transient
    private String tenantBpIdList;
    @Transient
    private Date validFrom;
    @Transient
    private Date validTo;
    @Transient
    private Long quotationId;
    @Transient
    private String sourceDocumentCategory;
    @Transient
    private Long sourceDocumentId;
    @Transient
    private String description;
    @Transient
    private String status;
    @Transient
    private String statusN;
    @Transient
    private String priceList;
    @Transient
    private Double leaseItemAmount;
    @Transient
    private Long leaseTimes;
    @Transient
    private Long annualPayTimes;
    @Transient
    private Double irr;
    @Children
    @Transient
    private List<HlsCusPrjProjectAttachment> prjProjectAttachments;
    @Children
    @Transient
    private List<HlsCusPrjProjectTenant> prjProjectTenants;
    @Children
    @Transient
    private List<HlsCusPrjProjectGuarantor> prjProjectGuarantors;
    @Children
    @Transient
    private List<HlsCusPrjProjectLeaseItem> prjProjectLeaseItems;
    @Children
    @Transient
    private List<HlsCusPrjProjectMortgage> prjProjectMortgages;
    @Children
    @Transient
    private List<HlsCusPrjProjectMeeting> prjProjectMeetings;
    @Children
    @Transient
    private List<HlsCusPrjProjectMeetingJudge> prjProjectMeetingJudges;
    @Transient
    private List<HlsCusPrjTenantHistEvolution> prjTenantHistEvolutions;
    @Transient
    private List<HlsCusPrjTenantStockStructure> prjTenantStockStructures;
    @Transient
    private List<HlsCusPrjTenantStockHolding> prjTenantStockHoldings;
    @Transient
    private List<HlsCusPrjTenantSupplier> prjTenantSuppliers;
    @Transient
    private List<HlsCusPrjTenantSalesCustomer> prjTenantSalesCustomers;
    @Transient
    private String businessTypeDesc;
    @Transient
    private String divisionDesc;
    @Transient
    private String leaseChannelDesc;
    @Transient
    private String hclDescription;
    @Transient
    private String params;

    private String contractNum;

    @Transient
    private Long changeReqId;

    private String farmerSignStatus;
    @Transient
    private String farmerSignStatusN;
    private String signStatus;
    private String partnersContractStatus;
    private String dealerSignType;
    private String venderSignType;
    private String manufacturerSignType;
    private String orgSignState;
    @Transient
    private String orgSignStateN;
    private Long manufacturerId;
    private String signType;
    private String confirmStatus;
    private String guaranteeSignedFlag;
    @Transient
    private String guaranteeSignedFlagN;
    private String contractTextStatus;
    @Transient
    private String contractTextStatusN;
    private String returnType;
    private String returnStage;
    private Date projectDate;
    private String rejectedDescription;
    private Date rejectedDate;
    private String deApplyResult;
    private String preStatus;
    private String orderStatus;
    private String driverAndApplicant;
    private String riskInfo;

    public PrjProject() {
    }

}
