package com.hand.hls.prj.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "prj_approval_condition")
public class ProjectApprovalCondition extends BaseDTO {

     public static final String FIELD_APPROVAL_RECORD_ID = "approvalRecordId";
     public static final String FIELD_APPROVAL_ID = "approvalId";
     public static final String FIELD_PROJECT_ID = "projectId";
     public static final String FIELD_CONDITION_TYPE = "conditionType";
     public static final String FIELD_APPROVAL_SEQ = "approvalSeq";
     public static final String FIELD_CONDITION_CONTENT = "conditionContent";


     @Id
     @GeneratedValue
     private Long approvalRecordId; //主键ID

     private Long approvalId; //项目批复ID（外键）

     private Long projectId;

     @Length(max = 255)
     private String conditionType; //条件类型

     @Length(max = 100)
     private String approvalSeq; //序号

     @Length(max = 500)
     private String conditionContent; //条件内容
    private String approvalType;
    @Transient
    private String conditionTypeN;
    @Transient
    private String approvalDataClass;

    public String getConditionTypeN() {
        return conditionTypeN;
    }

    public void setConditionTypeN(String conditionTypeN) {
        this.conditionTypeN = conditionTypeN;
    }

    public String getApprovalType() {
        return approvalType;
    }

    public void setApprovalType(String approvalType) {
        this.approvalType = approvalType;
    }

    public void setApprovalRecordId(Long approvalRecordId){
         this.approvalRecordId = approvalRecordId;
     }

     public Long getApprovalRecordId(){
         return approvalRecordId;
     }

     public void setApprovalId(Long approvalId){
         this.approvalId = approvalId;
     }

     public Long getApprovalId(){
         return approvalId;
     }

     public void setProjectId(Long projectId){
         this.projectId = projectId;
     }

     public Long getProjectId(){
         return projectId;
     }

     public void setConditionType(String conditionType){
         this.conditionType = conditionType;
     }

     public String getConditionType(){
         return conditionType;
     }

     public void setApprovalSeq(String approvalSeq){
         this.approvalSeq = approvalSeq;
     }

     public String getApprovalSeq(){
         return approvalSeq;
     }

     public void setConditionContent(String conditionContent){
         this.conditionContent = conditionContent;
     }

     public String getConditionContent(){
         return conditionContent;
     }

    public String getApprovalDataClass() {
        return approvalDataClass;
    }

    public void setApprovalDataClass(String approvalDataClass) {
        this.approvalDataClass = approvalDataClass;
    }
}
