package com.hand.hls.risk.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "plm_risk_attachment")
public class RiskAttachment extends BaseDTO {

     public static final String FIELD_RISK_ATTACHMENT_ID = "riskAttachmentId";
     public static final String FIELD_RISK_WARNING_ID = "riskWarningId";
     public static final String FIELD_DOCUMENT_NAME = "documentName";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_ATTACHMENT_CATEGORY = "attachmentCategory";
     public static final String FIELD_UPLOAD_DATE = "uploadDate";
     public static final String FIELD_UPLOAD_PERSON = "uploadPerson";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_SOURCE_ID = "sourceId";
     public static final String FIELD_SOURCE_TYPE = "sourceType";
     public static final String FIELD_DOCUMENT_ID = "documentId";


     @Id
     @GeneratedValue
     private Long riskAttachmentId;

     private Long riskWarningId;

     @Length(max = 65535)
     private String documentName;

     @Length(max = 65535)
     private String description;

     @Length(max = 255)
     private String attachmentCategory;

     private Date uploadDate;

     @Length(max = 255)
     private String uploadPerson;

     @Length(max = 255)
     private String status;

     private Long sourceId; //来源ID（合同文本模板ID）

     @Length(max = 255)
     private String sourceType; //营销报备附件类型

     private Long documentId; //营销报备document_id
     @Transient
     private String uploadPersonN;
     @Transient
     private String fileName;
     @Transient
     private String attachmentId;
     @Transient
     private Long checkId;

    public Long getCheckId() {
        return checkId;
    }

    public void setCheckId(Long checkId) {
        this.checkId = checkId;
    }

    public String getUploadPersonN() {
        return uploadPersonN;
    }

    public void setUploadPersonN(String uploadPersonN) {
        this.uploadPersonN = uploadPersonN;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

    public void setRiskAttachmentId(Long riskAttachmentId){
         this.riskAttachmentId = riskAttachmentId;
     }

     public Long getRiskAttachmentId(){
         return riskAttachmentId;
     }

     public void setRiskWarningId(Long riskWarningId){
         this.riskWarningId = riskWarningId;
     }

     public Long getRiskWarningId(){
         return riskWarningId;
     }

     public void setDocumentName(String documentName){
         this.documentName = documentName;
     }

     public String getDocumentName(){
         return documentName;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setAttachmentCategory(String attachmentCategory){
         this.attachmentCategory = attachmentCategory;
     }

     public String getAttachmentCategory(){
         return attachmentCategory;
     }

     public void setUploadDate(Date uploadDate){
         this.uploadDate = uploadDate;
     }

     public Date getUploadDate(){
         return uploadDate;
     }

     public void setUploadPerson(String uploadPerson){
         this.uploadPerson = uploadPerson;
     }

     public String getUploadPerson(){
         return uploadPerson;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setSourceId(Long sourceId){
         this.sourceId = sourceId;
     }

     public Long getSourceId(){
         return sourceId;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     public void setDocumentId(Long documentId){
         this.documentId = documentId;
     }

     public Long getDocumentId(){
         return documentId;
     }

     }
