package com.hand.hls.fin.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "LON_CON_REPAYMENT_BATCH")
@Getter
@Setter
public class HlsCusLonConRepaymentBatch extends BaseDTO {

     public static final String FIELD_BATCH_ID = "batchId";
     public static final String FIELD_BATCH_NUMBER = "batchNumber";
     public static final String FIELD_BATCH_STATUS = "batchStatus";
     private static final long serialVersionUID = -8358943920745935124L;


     @Id
     @GeneratedValue
     private Long batchId;

     @Length(max = 200)
     private String batchNumber;

     @Length(max = 100)
     private String batchStatus;

     private Long unitId;

     private Date repaymentDate;

     @Transient
     private String unitIdN;

     @Transient
     private String createPerson;

     @Transient
     private Date createTime;

     private Date creationDate;

     private Long processInstanceId;

     private Long creditBpId;

     @Transient
     private Date plannedDueDate;

     @Transient
     private Date plannedDueDateFrom;

     @Transient
     private Date plannedDueDateTo;

     @Transient
     private String batchStatusN;

     @Transient
     private String creditBpName;

     @Transient
     private String creditBpN;

     @Transient
     private String createdByN;
     private String historyFlag;

     private Long withBankAccountId;

     @Transient
     private String withBankAccountIdN;

     private String withBankAccountNum;

     private String withBankAccountName;

     private String withBankBranchName;

     private String powerfulChoose;

     @Transient
     private String powerfulChooseN;

     private String deptHeadChoose;

     @Transient
     private String deptHeadChooseN;

     private String description;

     @Transient
     private String bpName;

     private Long confirmSeq;

     private String confirmStatus;

     @Transient
     private String confirmStatusN;


     @Transient
     private String withdrawNumber;

     @Transient
     private String contractNumber;

     private String confirmPerson;

     @Transient
     private String confirmPersonN;

     @Transient
     private String currency ;

     @Transient
     private String currencyN;

     private String confirmUnit;

     @Transient
     private String confirmUnitN;

     @Transient
     private String batchNumberSeq;

     private Date confirmDate ;

     @Transient
     private String outPaymentIdN;

     @Transient
     private String inPaymentIdN;

     @Transient
     private String outBankAccountNum;
     @Transient
     private String inBankAccountNum;

     @Transient
     private Double paymentAmount ;

     @Transient
     private String fundDocumentType;

     @Transient
     private String documentId;

     @Transient
     private Double paymentAmountFrom;

     @Transient
     private Double paymentAmountTo;

     @Transient
     private Date paymentDateFrom;

     @Transient
     private Date paymentDateTo;

     @Transient
     private Date confirmDateFrom;

     @Transient
     private Date confirmDateTo;

     @Transient
     private String documentType;

     @Transient
     private String documentTypeN;

     @Transient
     private Long lonCompanyId;

     @Transient
     private String lonCompanyIdN;

     private String principalFlag;

     @Transient
     private Double repaymentAmountTotal;








}
