package com.hand.hls.fin.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "lon_contract_repayment")
@Getter
@Setter
public class HlsCusLonContractRepayment extends LonContractRepayment {

    public static final String FIELD_CONFIRM_FLAG = "confirmFlag";
    public static final String FIELD_PLANNED_CALC_DATE = "plannedCalcDate";
    public static final String FIELD_RECEIVED_BP_NAME = "receivedBpName";
    public static final String FIELD_RECEIVED_BANK_ACCOUNT_NAME = "receivedBankAccountName";
    public static final String FIELD_RECEIVED_BANK_ACCOUNT_NUM = "receivedBankAccountNum";

    private String confirmFlag;
    private Date writeOffDate;
    private Date plannedCalcDate;

    @Length(max = 400)
    private String receivedBpName;

    @Length(max = 400)
    private String receivedBankAccountName;

    @Length(max = 400)
    private String receivedBankAccountNum;

    private Double exchangeRate;

    private Double retainAmount;

    /**
     * 人民币还款金额
     */
    private Double cnyDueAmount;

    @Transient
    private String autoWrite;
    @Transient
    private Date plannedDueDateFrom;
    @Transient
    private Date plannedDueDateTo;
    @Transient
    private String documentType;
    @Transient
    private Date withdrawDate;
    @Transient
    private Date withdrawEndDate;
    @Transient
    private Date toRepayDays;
    @Transient
    private Date plannedCalcDateFrom;
    @Transient
    private Date plannedCalcDateTo;

    @JsonFormat(
            pattern = "yyyy-MM-dd"
    )
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date plannedDueDate;

    /**
     *
     */
    @Transient
    private Long plannedDueDay;
    @Transient
    private Date plannedDueDateStart;
    @Transient
    private Date plannedDueDateEnd;
    @Transient
    private String confirmFlagN;


    @Transient
    private Long rowTimes;


    @Transient

    private Date startDay;

    @Transient

    private Date endDay;

    @Transient
    private String interestFlag;

    @Transient
    @JsonFormat(
            pattern = "yyyy-MM-dd"
    )
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date queryDateFrom;

    @Transient
    @JsonFormat(
            pattern = "yyyy-MM-dd"
    )
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date queryDateTo;

    @Transient
    private Double newDueAmount;

    @Transient
    private Double principal;//原本金

    @Transient
    private Double newPrincipal;//现本金

    @Transient
    private String orgTypes;

    @Transient
    private String lonCompanyIdDesc;

    @Transient
    private String confirmFlagDesc;

    @Transient
    private String currencyName;

    @Transient
    private String withdrawDueAmount;

    @Transient
    private String orgTypeDesc;

    @Transient
    private String isWriteOffFlag;

    @Transient
    private String period;

    @Transient
    private Double remanningTimes;

    @Transient
    private Double reimbursementAmount;

    @Transient
    private Double sumReimbursementAmount;

    @Transient
    private Double cnyPlannedDueAmount;

    @Transient
    @JsonFormat(
            pattern = "yyyy-MM-dd"
    )
    private Date dueDate;

    @Transient
    private String majorContractNumber;

    @Transient
    private String repaymentIds;

    @Transient
    private Long companyId;

    @Transient
    private Long paymentReqId;

    @Transient
    private Long paymentReqLineId;

    @Transient
    private String paymentStatus;

    @Transient
    private Double approvedAmount;

    @Transient
    private Double sumAmount;

    @Transient
    private String withdrawNumber;

    @Transient
    private String currencys;

    @Transient
    private String writeOffFlags;
    /**
     * 系统计算标识 “Y”,默认为“N”
     */
    private String isSystemFlag;
    private String paymentMethod;

    @Transient
    private String paymentMethodN;

    @Transient
    private String amountLong;

    @Transient
    private String amountShort;

    @Transient
    private Double amtFrom;

    @Transient
    private Double amountTo;


    @Transient
    private String cfItemDesc;

    @Transient
    private String contractNumber;

    @Transient
    private String contractName;

    @Transient
    private Double financeAmount;
    @Transient
    private Double dueAmountNew;

    @Transient
    private String bpName;

    @Transient
    private String remainPaybackAmount;

    @Transient
    private String writeOffFlagDesc;

    @Transient
    private String cfTypeDesc;

    private Double proportion;

    @Transient
    private String cfItemN;

    @Transient
    private Long lonCompanyId;
    @Transient
    private String lonCompanyIdN;
    @Transient
    private Long creditBpId;
    @Transient
    private String creditBpName;

    @Transient
    private String currency;
    @Transient
    private String currencyN;
    private String amortizationMethod;
    @Transient
    private String amortizationMethodN;

    @Transient
    private String createdByN;

}
