package com.hand.hls.fin.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ExtensionAttribute(disable=true)
@Table(name = "CT_LON_CONTRACT_BANK_ACCOUNT")
public class HlsCusCtLonContractBankAccount extends BaseDTO {

     public static final String FIELD_CON_BANK_ACCOUNT_ID = "conBankAccountId";
     public static final String FIELD_BANK_ACCOUNT_ID = "bankAccountId";
     public static final String FIELD_BANK_ACCOUNT_TYPE = "bankAccountType";
     public static final String FIELD_DESCRIPTION = "description";

    @Transient
    private Long changeReqId;
    @Transient
    private Long oldcontractId;
    @Transient
    private Long oldwithdrawId;
    @Transient
    private String changeReqNumber; //变更编号

    @Transient
    private String reqStatus; //变更状态

    @Transient
    private Date reqDate; //变更日期

    @Transient
    private Date submitDate; //提交日期

    @Transient
    private Long submittedBy; //提交人

    @Transient
    private Long companyId ;

    @Transient
    private Long bankId ;

    private Long withdrawId;

    @Transient
    private String bankAccountIdN;

    public Long getConBankAccountId() {
        return conBankAccountId;
    }

    public void setConBankAccountId(Long conBankAccountId) {
        this.conBankAccountId = conBankAccountId;
    }

    public Long getBankAccountId() {
        return bankAccountId;
    }

    public void setBankAccountId(Long bankAccountId) {
        this.bankAccountId = bankAccountId;
    }

    public Long getContractId() {
        return contractId;
    }

    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    public String getBankAccountType() {
        return bankAccountType;
    }

    public void setBankAccountType(String bankAccountType) {
        this.bankAccountType = bankAccountType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getAccountSource() {
        return accountSource;
    }

    public void setAccountSource(String accountSource) {
        this.accountSource = accountSource;
    }

    public Long getLonBankAccountId() {
        return lonBankAccountId;
    }

    public void setLonBankAccountId(Long lonBankAccountId) {
        this.lonBankAccountId = lonBankAccountId;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankBranchName() {
        return bankBranchName;
    }

    public void setBankBranchName(String bankBranchName) {
        this.bankBranchName = bankBranchName;
    }

    public String getBankAccountName() {
        return bankAccountName;
    }

    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    public String getBankAccountNum() {
        return bankAccountNum;
    }

    public void setBankAccountNum(String bankAccountNum) {
        this.bankAccountNum = bankAccountNum;
    }

    @Id
     @GeneratedValue
     private Long conBankAccountId;

     private Long bankAccountId;

     private Long contractId;

     @Length(max = 100)
     private String bankAccountType;

     @Length(max = 100)
     private String description;

     private String enabledFlag;

     private String accountSource;

     private Long lonBankAccountId;

    /**
     * 银行名称
     */
     @Transient
     private String bankName;

    /**
     * 分行名称
     */
     //@Transient
     private String bankBranchName;

    /**
     * 银行账户名
     */
     //@Transient
     private String bankAccountName;

    /**
     * 银行账号
     */
     //@Transient
     private String bankAccountNum;

    public Long getChangeReqId() {
        return changeReqId;
    }

    public void setChangeReqId(Long changeReqId) {
        this.changeReqId = changeReqId;
    }

    public String getChangeReqNumber() {
        return changeReqNumber;
    }

    public void setChangeReqNumber(String changeReqNumber) {
        this.changeReqNumber = changeReqNumber;
    }

    public String getReqStatus() {
        return reqStatus;
    }

    public void setReqStatus(String reqStatus) {
        this.reqStatus = reqStatus;
    }

    public Date getReqDate() {
        return reqDate;
    }

    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    public Date getSubmitDate() {
        return submitDate;
    }

    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    public Long getSubmittedBy() {
        return submittedBy;
    }

    public void setSubmittedBy(Long submittedBy) {
        this.submittedBy = submittedBy;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getBankId() {
        return bankId;
    }

    public void setBankId(Long bankId) {
        this.bankId = bankId;
    }


    @Transient
    private String gldAccountCode;

    @Transient
    private String currency ;
    @Transient
    private String bankColor;

    @Transient
    private String financingLoanFlag;
    @Transient
    private String swiftCode;

    @Transient
    private Date openingDate;

    @Transient
    private Date closingDate;
    @Transient
    private String cnapsCode;

    @Transient
    private String accountNatureOne;

    @Transient
    private String accountNatureTwo;

    @Transient
    private String accountNatureThree;

    @Transient
    private String refV01;
    @Transient
    private String refV02;
    @Transient
    private String refV03;
    @Transient
    private String refV04;

    @Transient
    private String refV05;
    @Transient
    private String refV06;

    @Transient
    private String refV07;
    @Transient
    private String refV08;
    @Transient
    private String refV09;

    @Transient
    private String refV10;
    @Transient
    private String refV11;
    @Transient
    private String refV12;
    @Transient
    private String refV13;

    @Transient
    private String refV14;

    @Transient
    private String refV15;
    @Transient
    private String refN01;

    @Transient
    private String refN02;
    @Transient
    private String refN03;
    @Transient
    private String refN04;
    @Transient
    private String refN05;
    @Transient
    private String refN06;
    @Transient
    private String refN07;

    @Transient
    private String refN08;
    @Transient
    private String refN09;
    @Transient
    private String refN10;
    @Transient
    private String refD01;

    @Transient
    private String refD02;

    @Transient
    private String refD03;

    @Transient
    private String refD04;
    @Transient
    private String refD05;
    @Transient
    private String refD06;
    @Transient
    private String refD07;
    @Transient
    private String refD08;
    @Transient
    private String refD09;
    @Transient
    private String refD10;

    @Transient
    private String invoiceFlag;

    @Transient
    private String unitBankCode;

    @Transient
    private String address;

    @Transient
    private String managerId;

    @Transient
    private String managerName;

    @Transient
    private String contact;

    @Transient
    private String validFlag;

    @Transient
    private Date validStart;
    @Transient
    private Date validEnd;

    @Transient
    private Date openDate;

    @Transient
    private Date cancellDate;

    public String getGldAccountCode() {
        return gldAccountCode;
    }

    public void setGldAccountCode(String gldAccountCode) {
        this.gldAccountCode = gldAccountCode;
    }


    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getBankColor() {
        return bankColor;
    }

    public void setBankColor(String bankColor) {
        this.bankColor = bankColor;
    }

    public String getFinancingLoanFlag() {
        return financingLoanFlag;
    }

    public void setFinancingLoanFlag(String financingLoanFlag) {
        this.financingLoanFlag = financingLoanFlag;
    }

    public String getSwiftCode() {
        return swiftCode;
    }

    public void setSwiftCode(String swiftCode) {
        this.swiftCode = swiftCode;
    }

    public Date getOpeningDate() {
        return openingDate;
    }

    public void setOpeningDate(Date openingDate) {
        this.openingDate = openingDate;
    }

    public Date getClosingDate() {
        return closingDate;
    }

    public void setClosingDate(Date closingDate) {
        this.closingDate = closingDate;
    }

    public String getCnapsCode() {
        return cnapsCode;
    }

    public void setCnapsCode(String cnapsCode) {
        this.cnapsCode = cnapsCode;
    }

    public String getAccountNatureOne() {
        return accountNatureOne;
    }

    public void setAccountNatureOne(String accountNatureOne) {
        this.accountNatureOne = accountNatureOne;
    }

    public String getAccountNatureTwo() {
        return accountNatureTwo;
    }

    public void setAccountNatureTwo(String accountNatureTwo) {
        this.accountNatureTwo = accountNatureTwo;
    }

    public String getAccountNatureThree() {
        return accountNatureThree;
    }

    public void setAccountNatureThree(String accountNatureThree) {
        this.accountNatureThree = accountNatureThree;
    }

    public String getRefV01() {
        return refV01;
    }

    public void setRefV01(String refV01) {
        this.refV01 = refV01;
    }

    public String getRefV02() {
        return refV02;
    }

    public void setRefV02(String refV02) {
        this.refV02 = refV02;
    }

    public String getRefV03() {
        return refV03;
    }

    public void setRefV03(String refV03) {
        this.refV03 = refV03;
    }

    public String getRefV04() {
        return refV04;
    }

    public void setRefV04(String refV04) {
        this.refV04 = refV04;
    }

    public String getRefV05() {
        return refV05;
    }

    public void setRefV05(String refV05) {
        this.refV05 = refV05;
    }

    public String getRefV06() {
        return refV06;
    }

    public void setRefV06(String refV06) {
        this.refV06 = refV06;
    }

    public String getRefV07() {
        return refV07;
    }

    public void setRefV07(String refV07) {
        this.refV07 = refV07;
    }

    public String getRefV08() {
        return refV08;
    }

    public void setRefV08(String refV08) {
        this.refV08 = refV08;
    }

    public String getRefV09() {
        return refV09;
    }

    public void setRefV09(String refV09) {
        this.refV09 = refV09;
    }

    public String getRefV10() {
        return refV10;
    }

    public void setRefV10(String refV10) {
        this.refV10 = refV10;
    }

    public String getRefV11() {
        return refV11;
    }

    public void setRefV11(String refV11) {
        this.refV11 = refV11;
    }

    public String getRefV12() {
        return refV12;
    }

    public void setRefV12(String refV12) {
        this.refV12 = refV12;
    }

    public String getRefV13() {
        return refV13;
    }

    public void setRefV13(String refV13) {
        this.refV13 = refV13;
    }

    public String getRefV14() {
        return refV14;
    }

    public void setRefV14(String refV14) {
        this.refV14 = refV14;
    }

    public String getRefV15() {
        return refV15;
    }

    public void setRefV15(String refV15) {
        this.refV15 = refV15;
    }

    public String getRefN01() {
        return refN01;
    }

    public void setRefN01(String refN01) {
        this.refN01 = refN01;
    }

    public String getRefN02() {
        return refN02;
    }

    public void setRefN02(String refN02) {
        this.refN02 = refN02;
    }

    public String getRefN03() {
        return refN03;
    }

    public void setRefN03(String refN03) {
        this.refN03 = refN03;
    }

    public String getRefN04() {
        return refN04;
    }

    public void setRefN04(String refN04) {
        this.refN04 = refN04;
    }

    public String getRefN05() {
        return refN05;
    }

    public void setRefN05(String refN05) {
        this.refN05 = refN05;
    }

    public String getRefN06() {
        return refN06;
    }

    public void setRefN06(String refN06) {
        this.refN06 = refN06;
    }

    public String getRefN07() {
        return refN07;
    }

    public void setRefN07(String refN07) {
        this.refN07 = refN07;
    }

    public String getRefN08() {
        return refN08;
    }

    public void setRefN08(String refN08) {
        this.refN08 = refN08;
    }

    public String getRefN09() {
        return refN09;
    }

    public void setRefN09(String refN09) {
        this.refN09 = refN09;
    }

    public String getRefN10() {
        return refN10;
    }

    public void setRefN10(String refN10) {
        this.refN10 = refN10;
    }

    public String getRefD01() {
        return refD01;
    }

    public void setRefD01(String refD01) {
        this.refD01 = refD01;
    }

    public String getRefD02() {
        return refD02;
    }

    public void setRefD02(String refD02) {
        this.refD02 = refD02;
    }

    public String getRefD03() {
        return refD03;
    }

    public void setRefD03(String refD03) {
        this.refD03 = refD03;
    }

    public String getRefD04() {
        return refD04;
    }

    public void setRefD04(String refD04) {
        this.refD04 = refD04;
    }

    public String getRefD05() {
        return refD05;
    }

    public void setRefD05(String refD05) {
        this.refD05 = refD05;
    }

    public String getRefD06() {
        return refD06;
    }

    public void setRefD06(String refD06) {
        this.refD06 = refD06;
    }

    public String getRefD07() {
        return refD07;
    }

    public void setRefD07(String refD07) {
        this.refD07 = refD07;
    }

    public String getRefD08() {
        return refD08;
    }

    public void setRefD08(String refD08) {
        this.refD08 = refD08;
    }

    public String getRefD09() {
        return refD09;
    }

    public void setRefD09(String refD09) {
        this.refD09 = refD09;
    }

    public String getRefD10() {
        return refD10;
    }

    public void setRefD10(String refD10) {
        this.refD10 = refD10;
    }

    public String getInvoiceFlag() {
        return invoiceFlag;
    }

    public void setInvoiceFlag(String invoiceFlag) {
        this.invoiceFlag = invoiceFlag;
    }

    public String getUnitBankCode() {
        return unitBankCode;
    }

    public void setUnitBankCode(String unitBankCode) {
        this.unitBankCode = unitBankCode;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getManagerId() {
        return managerId;
    }

    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    public String getManagerName() {
        return managerName;
    }

    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getValidFlag() {
        return validFlag;
    }

    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag;
    }

    public Date getValidStart() {
        return validStart;
    }

    public void setValidStart(Date validStart) {
        this.validStart = validStart;
    }

    public Date getValidEnd() {
        return validEnd;
    }

    public void setValidEnd(Date validEnd) {
        this.validEnd = validEnd;
    }

    public Date getOpenDate() {
        return openDate;
    }

    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    public Date getCancellDate() {
        return cancellDate;
    }

    public void setCancellDate(Date cancellDate) {
        this.cancellDate = cancellDate;
    }

    @Transient
    private String bankAccountTypeN;

    @Transient
    private String accountSourceN;

    @Transient
    private String bankAccountNameN;
}
