package com.hand.hls.rw.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

@ExtensionAttribute(disable = true)
@Table(name = "plm_risk_warning_info")
public class HlsCusRiskWarningInfo extends BaseDTO {

    public static final String FIELD_RISK_WARNING_INFO_ID = "riskWarningInfoId";
    public static final String FIELD_RISK_WARNING_ID = "riskWarningId";
    public static final String FIELD_BREACH_CONTRACT_RISK_INFO = "breachContractRiskInfo";
    public static final String FIELD_FINANCIAL_RISK_INFO = "financialRiskInfo";
    public static final String FIELD_GUARANTEE_RISK_INFO = "guaranteeRiskInfo";
    public static final String FIELD_MANAGEMENT_RISK_INFO = "managementRiskInfo";
    public static final String FIELD_ASSOCIATED_RISK_INFO = "associatedRiskInfo";
    public static final String FIELD_OTHER_RISK_INFO = "otherRiskInfo";
    public static final String FIELD_INFO_COLLECTION_METHOD = "infoCollectionMethod";
    public static final String FIELD_RISK_LEVEL = "riskLevel";
    public static final String FIELD_CHANGE_IQ = "changeIq";
    public static final String FIELD_CHANGE_TIME = "changeTime";


    @Id
    @GeneratedValue
    private Long riskWarningInfoId; //id

    @NotNull
    private Long riskWarningId; //风险预警id

    @Length(max = 2000)
    private String breachContractRiskInfo; //违约风险信息

    @Length(max = 2000)
    private String financialRiskInfo; //财务风险信息

    @Length(max = 2000)
    private String guaranteeRiskInfo; //担保风险信息

    @Length(max = 2000)
    private String managementRiskInfo; //经营管理风险信息

    @Length(max = 2000)
    private String associatedRiskInfo; //关联风险信息

    @Length(max = 2000)
    private String litigationRiskInfo; //涉诉风险信息

    @Length(max = 2000)
    private String otherRiskInfo; //其他预警信息

    @Length(max = 100)
    private String infoCollectionMethod; //信息采集方式ONSITE:现场,OFFSITE:非现场

    @Length(max = 100)
    private String riskLevel; //预警级别


    //调整前预警级别
    private String riskLevelBefore;

    @Length(max = 100)
    private String changeIq; //变更中CHANGE,正常NORMAL,历史HISTORY

    private Long changeTime; //变更次数

    @Transient
    private String changeIqOld;//变更前状态
    @Transient
    private Double financeAmount;
    @Transient
    private String contractNumber;
    @Transient
    private String contractNum;
    @Transient
    private String contractName;

    private Long projectId; //虚拟合同ID

    private Long totalTimes; //总期数

    private Long receivedTimes; //已还期数

    private Long overdueAmount; //预期金额

    private Long overdueTimes; //逾期期次（现金流总逾期期数）

    private Long overdueDays; //累计逾期天数

    @Length(max = 50)
    private String fiveClassResult; //上次五级分类结果
    private Long bpId;

    public Long getBpId() {
        return bpId;
    }

    public void setBpId(Long bpId) {
        this.bpId = bpId;
    }

    public Double getFinanceAmount() {
        return financeAmount;
    }

    public void setFinanceAmount(Double financeAmount) {
        this.financeAmount = financeAmount;
    }

    public String getContractNum() {
        return contractNum;
    }

    public void setContractNum(String contractNum) {
        this.contractNum = contractNum;
    }

    public String getContractNumber() {
        return contractNumber;
    }

    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    public String getContractName() {
        return contractName;
    }

    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Long getTotalTimes() {
        return totalTimes;
    }

    public void setTotalTimes(Long totalTimes) {
        this.totalTimes = totalTimes;
    }

    public Long getReceivedTimes() {
        return receivedTimes;
    }

    public void setReceivedTimes(Long receivedTimes) {
        this.receivedTimes = receivedTimes;
    }

    public Long getOverdueAmount() {
        return overdueAmount;
    }

    public void setOverdueAmount(Long overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    public Long getOverdueTimes() {
        return overdueTimes;
    }

    public void setOverdueTimes(Long overdueTimes) {
        this.overdueTimes = overdueTimes;
    }

    public Long getOverdueDays() {
        return overdueDays;
    }

    public void setOverdueDays(Long overdueDays) {
        this.overdueDays = overdueDays;
    }

    public String getFiveClassResult() {
        return fiveClassResult;
    }

    public void setFiveClassResult(String fiveClassResult) {
        this.fiveClassResult = fiveClassResult;
    }

    public String getChangeIqOld() {
        return changeIqOld;
    }

    public void setChangeIqOld(String changeIqOld) {
        this.changeIqOld = changeIqOld;
    }

    public void setRiskWarningInfoId(Long riskWarningInfoId) {
        this.riskWarningInfoId = riskWarningInfoId;
    }

    public Long getRiskWarningInfoId() {
        return riskWarningInfoId;
    }

    public void setRiskWarningId(Long riskWarningId) {
        this.riskWarningId = riskWarningId;
    }

    public Long getRiskWarningId() {
        return riskWarningId;
    }

    public void setBreachContractRiskInfo(String breachContractRiskInfo) {
        this.breachContractRiskInfo = breachContractRiskInfo;
    }

    public String getBreachContractRiskInfo() {
        return breachContractRiskInfo;
    }

    public void setFinancialRiskInfo(String financialRiskInfo) {
        this.financialRiskInfo = financialRiskInfo;
    }

    public String getFinancialRiskInfo() {
        return financialRiskInfo;
    }

    public void setGuaranteeRiskInfo(String guaranteeRiskInfo) {
        this.guaranteeRiskInfo = guaranteeRiskInfo;
    }

    public String getGuaranteeRiskInfo() {
        return guaranteeRiskInfo;
    }

    public void setManagementRiskInfo(String managementRiskInfo) {
        this.managementRiskInfo = managementRiskInfo;
    }

    public String getManagementRiskInfo() {
        return managementRiskInfo;
    }

    public void setAssociatedRiskInfo(String associatedRiskInfo) {
        this.associatedRiskInfo = associatedRiskInfo;
    }

    public String getAssociatedRiskInfo() {
        return associatedRiskInfo;
    }

    public String getLitigationRiskInfo() {
        return litigationRiskInfo;
    }

    public void setLitigationRiskInfo(String litigationRiskInfo) {
        this.litigationRiskInfo = litigationRiskInfo;
    }

    public void setOtherRiskInfo(String otherRiskInfo) {
        this.otherRiskInfo = otherRiskInfo;
    }

    public String getOtherRiskInfo() {
        return otherRiskInfo;
    }

    public void setInfoCollectionMethod(String infoCollectionMethod) {
        this.infoCollectionMethod = infoCollectionMethod;
    }

    public String getInfoCollectionMethod() {
        return infoCollectionMethod;
    }

    public void setRiskLevel(String riskLevel) {
        this.riskLevel = riskLevel;
    }

    public String getRiskLevel() {
        return riskLevel;
    }

    public void setChangeIq(String changeIq) {
        this.changeIq = changeIq;
    }

    public String getChangeIq() {
        return changeIq;
    }

    public void setChangeTime(Long changeTime) {
        this.changeTime = changeTime;
    }

    public Long getChangeTime() {
        return changeTime;
    }

    public String getRiskLevelBefore() {
        return riskLevelBefore;
    }

    public void setRiskLevelBefore(String riskLevelBefore) {
        this.riskLevelBefore = riskLevelBefore;
    }
}
