package com.hand.hls.fp.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "jc_funding_plan_four")
public class JcFundingPlanFour extends BaseDTO {

     public static final String FIELD_FUNDING_FOUR_ID = "fundingFourId";
     public static final String FIELD_FUNDING_ID = "fundingId";
     public static final String FIELD_FUNDING_ONE_ID = "fundingOneId";
     public static final String FIELD_FUNDING_SECOND_ID = "fundingSecondId";
     public static final String FIELD_FUNDING_THREE_ID = "fundingThreeId";
     public static final String FIELD_FOUR_ITEM_CODE = "fourItemCode";
     public static final String FIELD_FOUR_ITEM_NAME = "fourItemName";
     public static final String FIELD_FOUR_ITEM_SEQ = "fourItemSeq";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";


     @Id
     @GeneratedValue
     private Long fundingFourId; //主键

     private Long fundingId; //资金计划ID

     private Long fundingOneId; //一级分类ID

     private Long fundingSecondId; //二级分类ID

     private Long fundingThreeId; //三级分类ID

     @Length(max = 50)
     private String fourItemCode; //四级分类代码

     @Length(max = 100)
     private String fourItemName; //四级分类项目名称

     @Length(max = 20)
     private Long fourItemSeq; //序号

     @Length(max = 1)
     private String enabledFlag; //是否启用


     public void setFundingFourId(Long fundingFourId){
         this.fundingFourId = fundingFourId;
     }

     public Long getFundingFourId(){
         return fundingFourId;
     }

     public void setFundingId(Long fundingId){
         this.fundingId = fundingId;
     }

     public Long getFundingId(){
         return fundingId;
     }

     public void setFundingOneId(Long fundingOneId){
         this.fundingOneId = fundingOneId;
     }

     public Long getFundingOneId(){
         return fundingOneId;
     }

     public void setFundingSecondId(Long fundingSecondId){
         this.fundingSecondId = fundingSecondId;
     }

     public Long getFundingSecondId(){
         return fundingSecondId;
     }

     public void setFundingThreeId(Long fundingThreeId){
         this.fundingThreeId = fundingThreeId;
     }

     public Long getFundingThreeId(){
         return fundingThreeId;
     }

     public void setFourItemCode(String fourItemCode){
         this.fourItemCode = fourItemCode;
     }

     public String getFourItemCode(){
         return fourItemCode;
     }

     public void setFourItemName(String fourItemName){
         this.fourItemName = fourItemName;
     }

     public String getFourItemName(){
         return fourItemName;
     }

     public void setFourItemSeq(Long fourItemSeq){
         this.fourItemSeq = fourItemSeq;
     }

     public Long getFourItemSeq(){
         return fourItemSeq;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     }
