package com.hand.hls.app.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "hls_app_interface_record")
public class HlsCusAppInterfaceRecord extends BaseDTO {

     public static final String FIELD_RECORD_ID = "recordId";
     public static final String FIELD_INTERFACE_NAME = "interfaceName";
     public static final String FIELD_INTERFACE_URL = "interfaceUrl";
     public static final String FIELD_INTERFACE_PARAM = "interfaceParam";
     public static final String FIELD_RETURN_DATA = "returnData";
     public static final String FIELD_RETURN_MESSAGE = "returnMessage";
     public static final String FIELD_INTERFACE_DATE = "interfaceDate";
     public static final String FIELD_REF_V01 = "refV01";
     public static final String FIELD_REF_V02 = "refV02";
     public static final String FIELD_REF_V03 = "refV03";
     public static final String FIELD_REF_V04 = "refV04";
     public static final String FIELD_REF_V05 = "refV05";
     public static final String FIELD_REF_V06 = "refV06";
     public static final String FIELD_REF_V07 = "refV07";
     public static final String FIELD_REF_V08 = "refV08";
     public static final String FIELD_REF_V09 = "refV09";
     public static final String FIELD_REF_V10 = "refV10";
     public static final String FIELD_REF_V11 = "refV11";
     public static final String FIELD_REF_V12 = "refV12";
     public static final String FIELD_REF_V13 = "refV13";
     public static final String FIELD_REF_V14 = "refV14";
     public static final String FIELD_REF_V15 = "refV15";
     public static final String FIELD_REF_N01 = "refN01";
     public static final String FIELD_REF_N02 = "refN02";
     public static final String FIELD_REF_N03 = "refN03";
     public static final String FIELD_REF_N04 = "refN04";
     public static final String FIELD_REF_N05 = "refN05";
     public static final String FIELD_REF_N06 = "refN06";
     public static final String FIELD_REF_N07 = "refN07";
     public static final String FIELD_REF_N08 = "refN08";
     public static final String FIELD_REF_N09 = "refN09";
     public static final String FIELD_REF_N10 = "refN10";
     public static final String FIELD_REF_D01 = "refD01";
     public static final String FIELD_REF_D02 = "refD02";
     public static final String FIELD_REF_D03 = "refD03";
     public static final String FIELD_REF_D04 = "refD04";
     public static final String FIELD_REF_D05 = "refD05";
     public static final String FIELD_REF_D06 = "refD06";
     public static final String FIELD_REF_D07 = "refD07";
     public static final String FIELD_REF_D08 = "refD08";
     public static final String FIELD_REF_D09 = "refD09";
     public static final String FIELD_REF_D10 = "refD10";


     @Id
     @GeneratedValue
     private Long recordId; //记录id

     @Length(max = 100)
     private String interfaceName; //接口名称

     @Length(max = 100)
     private String interfaceUrl; //接口url

     @Length(max = 2147483647)
     private String interfaceParam; //微信请求参数

     @Length(max = 2147483647)
     private String returnData; //系统返回数据

     @Length(max = 2147483647)
     private String returnMessage; //系统返回信息

     private Date interfaceDate; //接口调用时间

     @Length(max = 2147483647)
     private String refV01;

     @Length(max = 2147483647)
     private String refV02;

     @Length(max = 2147483647)
     private String refV03;

     @Length(max = 2147483647)
     private String refV04;

     @Length(max = 2147483647)
     private String refV05;

     @Length(max = 2147483647)
     private String refV06;

     @Length(max = 2147483647)
     private String refV07;

     @Length(max = 2147483647)
     private String refV08;

     @Length(max = 2147483647)
     private String refV09;

     @Length(max = 2147483647)
     private String refV10;

     @Length(max = 2147483647)
     private String refV11;

     @Length(max = 2147483647)
     private String refV12;

     @Length(max = 2147483647)
     private String refV13;

     @Length(max = 2147483647)
     private String refV14;

     @Length(max = 2147483647)
     private String refV15;

     private Double refN01;

     private Double refN02;

     private Double refN03;

     private Double refN04;

     private Double refN05;

     private Double refN06;

     private Double refN07;

     private Double refN08;

     private Double refN09;

     private Double refN10;

     private Date refD01;

     private Date refD02;

     private Date refD03;

     private Date refD04;

     private Date refD05;

     private Date refD06;

     private Date refD07;

     private Date refD08;

     private Date refD09;

     private Date refD10;


     public void setRecordId(Long recordId){
         this.recordId = recordId;
     }

     public Long getRecordId(){
         return recordId;
     }

     public void setInterfaceName(String interfaceName){
         this.interfaceName = interfaceName;
     }

     public String getInterfaceName(){
         return interfaceName;
     }

     public void setInterfaceUrl(String interfaceUrl){
         this.interfaceUrl = interfaceUrl;
     }

     public String getInterfaceUrl(){
         return interfaceUrl;
     }

     public void setInterfaceParam(String interfaceParam){
         this.interfaceParam = interfaceParam;
     }

     public String getInterfaceParam(){
         return interfaceParam;
     }

     public void setReturnData(String returnData){
         this.returnData = returnData;
     }

     public String getReturnData(){
         return returnData;
     }

     public void setReturnMessage(String returnMessage){
         this.returnMessage = returnMessage;
     }

     public String getReturnMessage(){
         return returnMessage;
     }

     public void setInterfaceDate(Date interfaceDate){
         this.interfaceDate = interfaceDate;
     }

     public Date getInterfaceDate(){
         return interfaceDate;
     }

     public void setRefV01(String refV01){
         this.refV01 = refV01;
     }

     public String getRefV01(){
         return refV01;
     }

     public void setRefV02(String refV02){
         this.refV02 = refV02;
     }

     public String getRefV02(){
         return refV02;
     }

     public void setRefV03(String refV03){
         this.refV03 = refV03;
     }

     public String getRefV03(){
         return refV03;
     }

     public void setRefV04(String refV04){
         this.refV04 = refV04;
     }

     public String getRefV04(){
         return refV04;
     }

     public void setRefV05(String refV05){
         this.refV05 = refV05;
     }

     public String getRefV05(){
         return refV05;
     }

     public void setRefV06(String refV06){
         this.refV06 = refV06;
     }

     public String getRefV06(){
         return refV06;
     }

     public void setRefV07(String refV07){
         this.refV07 = refV07;
     }

     public String getRefV07(){
         return refV07;
     }

     public void setRefV08(String refV08){
         this.refV08 = refV08;
     }

     public String getRefV08(){
         return refV08;
     }

     public void setRefV09(String refV09){
         this.refV09 = refV09;
     }

     public String getRefV09(){
         return refV09;
     }

     public void setRefV10(String refV10){
         this.refV10 = refV10;
     }

     public String getRefV10(){
         return refV10;
     }

     public void setRefV11(String refV11){
         this.refV11 = refV11;
     }

     public String getRefV11(){
         return refV11;
     }

     public void setRefV12(String refV12){
         this.refV12 = refV12;
     }

     public String getRefV12(){
         return refV12;
     }

     public void setRefV13(String refV13){
         this.refV13 = refV13;
     }

     public String getRefV13(){
         return refV13;
     }

     public void setRefV14(String refV14){
         this.refV14 = refV14;
     }

     public String getRefV14(){
         return refV14;
     }

     public void setRefV15(String refV15){
         this.refV15 = refV15;
     }

     public String getRefV15(){
         return refV15;
     }

     public void setRefN01(Double refN01){
         this.refN01 = refN01;
     }

     public Double getRefN01(){
         return refN01;
     }

     public void setRefN02(Double refN02){
         this.refN02 = refN02;
     }

     public Double getRefN02(){
         return refN02;
     }

     public void setRefN03(Double refN03){
         this.refN03 = refN03;
     }

     public Double getRefN03(){
         return refN03;
     }

     public void setRefN04(Double refN04){
         this.refN04 = refN04;
     }

     public Double getRefN04(){
         return refN04;
     }

     public void setRefN05(Double refN05){
         this.refN05 = refN05;
     }

     public Double getRefN05(){
         return refN05;
     }

     public void setRefN06(Double refN06){
         this.refN06 = refN06;
     }

     public Double getRefN06(){
         return refN06;
     }

     public void setRefN07(Double refN07){
         this.refN07 = refN07;
     }

     public Double getRefN07(){
         return refN07;
     }

     public void setRefN08(Double refN08){
         this.refN08 = refN08;
     }

     public Double getRefN08(){
         return refN08;
     }

     public void setRefN09(Double refN09){
         this.refN09 = refN09;
     }

     public Double getRefN09(){
         return refN09;
     }

     public void setRefN10(Double refN10){
         this.refN10 = refN10;
     }

     public Double getRefN10(){
         return refN10;
     }

     public void setRefD01(Date refD01){
         this.refD01 = refD01;
     }

     public Date getRefD01(){
         return refD01;
     }

     public void setRefD02(Date refD02){
         this.refD02 = refD02;
     }

     public Date getRefD02(){
         return refD02;
     }

     public void setRefD03(Date refD03){
         this.refD03 = refD03;
     }

     public Date getRefD03(){
         return refD03;
     }

     public void setRefD04(Date refD04){
         this.refD04 = refD04;
     }

     public Date getRefD04(){
         return refD04;
     }

     public void setRefD05(Date refD05){
         this.refD05 = refD05;
     }

     public Date getRefD05(){
         return refD05;
     }

     public void setRefD06(Date refD06){
         this.refD06 = refD06;
     }

     public Date getRefD06(){
         return refD06;
     }

     public void setRefD07(Date refD07){
         this.refD07 = refD07;
     }

     public Date getRefD07(){
         return refD07;
     }

     public void setRefD08(Date refD08){
         this.refD08 = refD08;
     }

     public Date getRefD08(){
         return refD08;
     }

     public void setRefD09(Date refD09){
         this.refD09 = refD09;
     }

     public Date getRefD09(){
         return refD09;
     }

     public void setRefD10(Date refD10){
         this.refD10 = refD10;
     }

     public Date getRefD10(){
         return refD10;
     }

     }
