package com.hand.hls.csh.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "con_debt_exemption_req")
public class ConDebtExemptionReq extends BaseDTO {

    @Id
    @GeneratedValue
    private Long changeReqId;
    private String changeReqNumber;
    private String documentType;
    private String documentCategory;
    private String businessType;
    private Long companyId;
    private Long reqUserId;
    private String reqStatus;
    private Date reqDate;
    private String description;
    private Long processInstanceId;

    private String instanceEndFlag;

    public String getInstanceEndFlag() {
        return instanceEndFlag;
    }

    public void setInstanceEndFlag(String instanceEndFlag) {
        this.instanceEndFlag = instanceEndFlag;
    }

    public Long getChangeReqId() {
        return changeReqId;
    }

    public void setChangeReqId(Long changeReqId) {
        this.changeReqId = changeReqId;
    }

    public String getChangeReqNumber() {
        return changeReqNumber;
    }

    public void setChangeReqNumber(String changeReqNumber) {
        this.changeReqNumber = changeReqNumber;
    }

    public String getDocumentType() {
        return documentType;
    }

    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    public String getDocumentCategory() {
        return documentCategory;
    }

    public void setDocumentCategory(String documentCategory) {
        this.documentCategory = documentCategory;
    }

    public String getBusinessType() {
        return businessType;
    }

    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getReqUserId() {
        return reqUserId;
    }

    public void setReqUserId(Long reqUserId) {
        this.reqUserId = reqUserId;
    }

    public String getReqStatus() {
        return reqStatus;
    }

    public void setReqStatus(String reqStatus) {
        this.reqStatus = reqStatus;
    }

    public Date getReqDate() {
        return reqDate;
    }

    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(Long processInstanceId) {
        this.processInstanceId = processInstanceId;
    }
}
