package com.hand.hls.csh.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.Table;
import javax.persistence.Transient;

@ExtensionAttribute(disable = true)
@Table(name = "con_debt_exemption_req_cf")
@Getter
@Setter
public class HlsCusConDebtExemptionReqCf extends DebtExemptionReqCf {
    @Transient
    private Double uncollectedAmount;
    @Transient
    private Double exemptionAmount;

}
