package com.hand.hls.csh.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import groovy.transform.Field;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "CSH_WRITE_OFF_TEMP")
@Getter
@Setter
public class WriteOffTemp extends BaseDTO {

     public static final String FIELD_TEMP_ID = "tempId";
     public static final String FIELD_UUID_STR = "uuidStr";
     public static final String FIELD_WRITE_OFF_TYPE = "writeOffType";
     public static final String FIELD_TRANSACTION_CATEGORY = "transactionCategory";
     public static final String FIELD_TRANSACTION_TYPE = "transactionType";
     public static final String FIELD_WRITE_OFF_DATE = "writeOffDate";
     public static final String FIELD_WRITE_OFF_DUE_AMOUNT = "writeOffDueAmount";
     public static final String FIELD_WRITE_OFF_PRINCIPAL = "writeOffPrincipal";
     public static final String FIELD_WRITE_OFF_INTEREST = "writeOffInterest";
     public static final String FIELD_CONTRACT_ID = "contractId";
     public static final String FIELD_CASHFLOW_ID = "cashflowId";
     public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_DEPOSIT_DEDUCTION = "depositDeduction";
    public static final String FIELD_TIMES = "times";
    public static final String FIELD_CF_TYPE = "cfType";
    public static final String FIELD_CF_ITEM = "cfItem";
    public static final String FIELD_CONTRACT_NUMBER = "contractNumber";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_PROPOSED_LAUNCH_DATE = "proposedLaunchDate";
    public static final String FIELD_PP_CONTRACT_NUMBER = "ppContractNumber";
    public static final String FIELD_PP_CONTRACT_NAME = "ppContractName";
    public static final String FIELD_SUM_TOUFANG_AMOUNT = "sumToufangAmount";
    public static final String FIELD_LOAN_TOTAL_AMOUNT = "loanTotalAmount";
    public static final String FIELD_PROJECT_ID = "projectId";
    public static final String FIELD_PROJECT_NAME = "projectName";
    public static final String FIELD_FINANCE_AMOUNT = "financeAmount";
    public static final String FIELD_UNIT_NAME = "unitName";
    public static final String FIELD_UNIT_ID = "unitId";
    public static final String FIELD_BP_ID = "bpId";
    public static final String FIELD_BP_NAME = "bpName";
    public static final String FIELD_CONTRACT_BALANCE = "contractBalance";
    public static final String FIELD_CURRENCY = "currency";
    public static final String FIELD_CURRENCY_ID = "currencyId";
    public static final String FIELD_CONTRACT_CURRENCY_ID = "contractCurrencyId";
    public static final String FIELD_CONTRACT_CURRENCY = "contractCurrency";


     @Id
     @GeneratedValue
     private Long tempId;

     @Length(max = 300)
     private String uuidStr;

     @Length(max = 100)
     private String writeOffType;

     @Length(max = 300)
     private String transactionCategory;

     @Length(max = 4000)
     private String transactionType;

     private Date writeOffDate;

     private Double writeOffDueAmount;

     private Double writeOffPrincipal;

     private Double writeOffInterest;

     private Long contractId;

     private Long cashflowId;

     @Length(max = 100)
     private String description;

     private String depositDeduction;
     private Long times;

    private Long cfType;

    private Long cfItem;


    @Length(max = 200)
    private String contractNumber;

    private Long companyId;

    private Date proposedLaunchDate;

    @Length(max = 200)
    private String ppContractNumber;

    @Length(max = 200)
    private String ppContractName;

    private Double sumToufangAmount;

    private Double loanTotalAmount;

    private Long projectId;

    @Length(max = 200)
    private String projectName;

    private Double financeAmount;

    @Length(max = 200)
    private String unitName;

    private Long unitId;

    private Long bpId;

    @Length(max = 200)
    private String bpName;

    private Double contractBalance;

    @Length(max = 200)
    private String currency;

    private String currencyId;

    private String contractCurrencyId;

    @Length(max = 200)
    private String contractCurrency;

    @Transient
    private String bpBankAccountNum;
    @Transient
    private String bpBankAccountName;
    @Transient
    private String bpBankBranchName;



     /*public void setTempId(Long tempId){
         this.tempId = tempId;
     }

     public Long getTempId(){
         return tempId;
     }

     public void setUuidStr(String uuidStr){
         this.uuidStr = uuidStr;
     }

     public String getUuidStr(){
         return uuidStr;
     }

     public void setWriteOffType(String writeOffType){
         this.writeOffType = writeOffType;
     }

     public String getWriteOffType(){
         return writeOffType;
     }

     public void setTransactionCategory(String transactionCategory){
         this.transactionCategory = transactionCategory;
     }

     public String getTransactionCategory(){
         return transactionCategory;
     }

     public void setTransactionType(String transactionType){
         this.transactionType = transactionType;
     }

     public String getTransactionType(){
         return transactionType;
     }

     public void setWriteOffDate(Date writeOffDate){
         this.writeOffDate = writeOffDate;
     }

     public Date getWriteOffDate(){
         return writeOffDate;
     }

     public void setWriteOffDueAmount(Long writeOffDueAmount){
         this.writeOffDueAmount = writeOffDueAmount;
     }

     public Long getWriteOffDueAmount(){
         return writeOffDueAmount;
     }

     public void setWriteOffPrincipal(Long writeOffPrincipal){
         this.writeOffPrincipal = writeOffPrincipal;
     }

     public Long getWriteOffPrincipal(){
         return writeOffPrincipal;
     }

     public void setWriteOffInterest(Long writeOffInterest){
         this.writeOffInterest = writeOffInterest;
     }

     public Long getWriteOffInterest(){
         return writeOffInterest;
     }

     public void setContractId(Long contractId){
         this.contractId = contractId;
     }

     public Long getContractId(){
         return contractId;
     }

     public void setCashflowId(Long cashflowId){
         this.cashflowId = cashflowId;
     }

     public Long getCashflowId(){
         return cashflowId;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }*/

     }
