package com.hand.hls.archive.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.Data;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

@ExtensionAttribute(disable = true)
@Table(name = "jc_archive_borrow")
@Data
public class HlsCusArchiveBorrow extends BaseDTO {

    public static final String FIELD_BORROW_ID = "borrowId";
    public static final String FIELD_PROJECT_ID = "projectId";
    public static final String FIELD_ELEMENT_CLASS_FLAG = "elementClassFlag";
    public static final String FIELD_MANAGEMENT_CLASS_FLAG = "managementClassFlag";
    public static final String FIELD_WARRANT_CLASS_FLAG = "warrantClassFlag";
    public static final String FIELD_GENERAL_CLASS_FLAG = "generalClassFlag";
    public static final String FIELD_BORROW_DATE = "borrowDate";
    public static final String FIELD_BORROW_END_DATE = "borrowEndDate";
    public static final String FIELD_APPLY_REASON = "applyReason";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_BORROW_RETURN_STATUS = "borrowReturnStatus";
    public static final String FIELD_RETURN_DATE = "returnDate";
    public static final String FIELD_PROCESS_INSTANCE_ID = "processInstanceId";
    public static final String FIELD_AUTHORITY_RULE_STRING = "authorityRuleString";


    @Id
    @GeneratedValue
    private Long borrowId;

    private Long projectId; //项目ID

    @Length(max = 1)
    private String elementClassFlag; //要件类

    @Length(max = 1)
    private String managementClassFlag; //管理类

    @Length(max = 1)
    private String warrantClassFlag; //权证类

    @Length(max = 1)
    private String generalClassFlag; //综合类

    private Date borrowDate; //借阅日期

    private Date borrowEndDate; //预计归还日期

    @Length(max = 2000)
    private String applyReason; //申请原因

    @Length(max = 2000)
    private String description; //描述/备注

    @Length(max = 200)
    private String borrowReturnStatus; //借阅归还状态

    private Date returnDate; //归还时间

    private Long processInstanceId; //审批通过工作流ID

    private String authorityRuleString; //权限字段

    private Long employeeId;

    private Long unitId;

    @Transient
    private String employeeIdN;

    @Transient
    private String unitIdN;

    @Transient
    private String projectNumber;

    @Transient
    private String projectName;

    @Transient
    private String bpName;

    @Transient
    private String borrowReturnStatusN;


}
