package com.hand.hls.gld.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@ExtensionAttribute(disable = true)
@Table(name = "gld_set_of_books")
public class SetOfBooks extends BaseDTO {
    @Id
    @GeneratedValue
    private Long setOfBooksId; //帐套ID

    @NotEmpty
    private String setOfBooksCode; //帐套代码

    private String setOfBooksName; //帐套名称

    private Long periodSetId; //期间表ID

    private Long accountSetId; //科目表ID

    private String functionalCurrency; //本位币

    private String enabledFlag; //启用标志

    @Transient
    private String periodSetName;
    @Transient
    private String accountSetName;

    @Transient
    private String functionalCurrencyCn;

    @Transient
    private String accountSetIdN;

    @Transient
    private String functionalCurrencyN;


    public void setSetOfBooksId(Long setOfBooksId) {
        this.setOfBooksId = setOfBooksId;
    }

    public Long getSetOfBooksId() {
        return setOfBooksId;
    }

    public void setSetOfBooksCode(String setOfBooksCode) {
        this.setOfBooksCode = setOfBooksCode;
    }

    public String getSetOfBooksCode() {
        return setOfBooksCode;
    }

    public void setSetOfBooksName(String setOfBooksName) {
        this.setOfBooksName = setOfBooksName;
    }

    public String getSetOfBooksName() {
        return setOfBooksName;
    }

    public void setPeriodSetId(Long periodSetId) {
        this.periodSetId = periodSetId;
    }

    public Long getPeriodSetId() {
        return periodSetId;
    }

    public void setAccountSetId(Long accountSetId) {
        this.accountSetId = accountSetId;
    }

    public Long getAccountSetId() {
        return accountSetId;
    }

    public void setFunctionalCurrency(String functionalCurrency) {
        this.functionalCurrency = functionalCurrency;
    }

    public String getFunctionalCurrency() {
        return functionalCurrency;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

    public String getPeriodSetName() {
        return periodSetName;
    }

    public void setPeriodSetName(String periodSetName) {
        this.periodSetName = periodSetName;
    }

    public String getAccountSetName() {
        return accountSetName;
    }

    public void setAccountSetName(String accountSetName) {
        this.accountSetName = accountSetName;
    }

    public String getFunctionalCurrencyCn() {
        return functionalCurrencyCn;
    }

    public void setFunctionalCurrencyCn(String functionalCurrencyCn) {
        this.functionalCurrencyCn = functionalCurrencyCn;
    }

    public String getAccountSetIdN() {
        return accountSetIdN;
    }

    public void setAccountSetIdN(String accountSetIdN) {
        this.accountSetIdN = accountSetIdN;
    }

    public String getFunctionalCurrencyN() {
        return functionalCurrencyN;
    }

    public void setFunctionalCurrencyN(String functionalCurrencyN) {
        this.functionalCurrencyN = functionalCurrencyN;
    }
}
