package com.hand.hls.bp.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "hls_bp_shareholder_info_ht")
public class BpShareholderInfoHt extends BaseDTO {

     public static final String FIELD_SHAREHOLDER_LN_ID = "shareholderLnId";
     public static final String FIELD_SHAREHOLDER_INFORMATION_ID = "shareholderInformationId";
     public static final String FIELD_BP_ID = "bpId";
     public static final String FIELD_SHAREHOLDER_TYPE = "shareholderType";
     public static final String FIELD_SHAREHOLDER_NAME = "shareholderName";
     public static final String FIELD_SUBSCRIPTION_AMOMON = "subscriptionAmomon";
     public static final String FIELD_SUBSCRIPTION_PERCEN = "subscriptionPercen";
     public static final String FIELD_SUBSCRIPTION_TIME = "subscriptionTime";
     public static final String FIELD_SUBSCRIPTION_PAYMET = "subscriptionPaymet";


     @Id
     @GeneratedValue
     private Long shareholderLnId;

     private Long shareholderInformationId;

     private Long bpId; //商业伙伴ID

     @Length(max = 500)
     private String shareholderType; //股东类型

     @Length(max = 500)
     private String shareholderName; //股东名称

     private Double subscriptionAmomon; //认缴金额

     @Length(max = 50)
     private String subscriptionPercen; //所占比例

     private Date subscriptionTime; //认缴时间

     @Length(max = 255)
     private String subscriptionPaymet; //认缴形式


     public void setShareholderLnId(Long shareholderLnId){
         this.shareholderLnId = shareholderLnId;
     }

     public Long getShareholderLnId(){
         return shareholderLnId;
     }

     public void setShareholderInformationId(Long shareholderInformationId){
         this.shareholderInformationId = shareholderInformationId;
     }

     public Long getShareholderInformationId(){
         return shareholderInformationId;
     }

     public void setBpId(Long bpId){
         this.bpId = bpId;
     }

     public Long getBpId(){
         return bpId;
     }

     public void setShareholderType(String shareholderType){
         this.shareholderType = shareholderType;
     }

     public String getShareholderType(){
         return shareholderType;
     }

     public void setShareholderName(String shareholderName){
         this.shareholderName = shareholderName;
     }

     public String getShareholderName(){
         return shareholderName;
     }

    public Double getSubscriptionAmomon() {
        return subscriptionAmomon;
    }

    public void setSubscriptionAmomon(Double subscriptionAmomon) {
        this.subscriptionAmomon = subscriptionAmomon;
    }

    public void setSubscriptionPercen(String subscriptionPercen){
         this.subscriptionPercen = subscriptionPercen;
     }

     public String getSubscriptionPercen(){
         return subscriptionPercen;
     }

     public void setSubscriptionTime(Date subscriptionTime){
         this.subscriptionTime = subscriptionTime;
     }

     public Date getSubscriptionTime(){
         return subscriptionTime;
     }

     public void setSubscriptionPaymet(String subscriptionPaymet){
         this.subscriptionPaymet = subscriptionPaymet;
     }

     public String getSubscriptionPaymet(){
         return subscriptionPaymet;
     }

     }
