package com.hand.hls.bp.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "hls_bp_customer_relationship")
public class HlsBpCustomerRelationship extends BaseDTO {

     public static final String FIELD_RELATIONSHIP_ID = "relationshipId";
     public static final String FIELD_BP_ID = "bpId";
     public static final String FIELD_CUSTOMER_RELATIONSHIP = "customerRelationship";
     public static final String FIELD_COMPANY_NAME = "companyName";
     public static final String FIELD_LEGAL_PERSON_NAME = "legalPersonName";
     public static final String FIELD_REGISTERED_CAPITAL = "registeredCapital";
     public static final String FIELD_INCORPORATION_DATE = "incorporationDate";
     public static final String FIELD_ENTERPRISE_STATUS = "enterpriseStatus";
     public static final String FIELD_R_BP_ID = "rBpId";


     @Id
     @GeneratedValue
     private Long relationshipId; //主键ID

     private Long bpId; //商业伙伴ID

     @Length(max = 50)
     private String customerRelationship; //客户关系

     @Length(max = 255)
     private String companyName; //公司名称

     @Length(max = 50)
     private String legalPersonName; //法人名称

     private Double registeredCapital; //注册资本

     private Date incorporationDate; //成立日期

     @Length(max = 100)
     private String enterpriseStatus; //企业状态

     private Long rBpId; //关联法人（相关客户编号）
     @Transient
     private String rBpName;
     @Transient
     private String rBpCode;
     @Transient
     private String customerRelationshipN;
     @Transient
     private String rBpIdN;


    public String getrBpIdN() {
        return rBpIdN;
    }

    public void setrBpIdN(String rBpIdN) {
        this.rBpIdN = rBpIdN;
    }

    public Long getrBpId() {
        return rBpId;
    }

    public void setrBpId(Long rBpId) {
        this.rBpId = rBpId;
    }

    public String getrBpName() {
        return rBpName;
    }

    public void setrBpName(String rBpName) {
        this.rBpName = rBpName;
    }

    public String getrBpCode() {
        return rBpCode;
    }

    public void setrBpCode(String rBpCode) {
        this.rBpCode = rBpCode;
    }

    public String getCustomerRelationshipN() {
        return customerRelationshipN;
    }

    public void setCustomerRelationshipN(String customerRelationshipN) {
        this.customerRelationshipN = customerRelationshipN;
    }

    public void setRelationshipId(Long relationshipId){
         this.relationshipId = relationshipId;
     }

     public Long getRelationshipId(){
         return relationshipId;
     }

     public void setBpId(Long bpId){
         this.bpId = bpId;
     }

     public Long getBpId(){
         return bpId;
     }

     public void setCustomerRelationship(String customerRelationship){
         this.customerRelationship = customerRelationship;
     }

     public String getCustomerRelationship(){
         return customerRelationship;
     }

     public void setCompanyName(String companyName){
         this.companyName = companyName;
     }

     public String getCompanyName(){
         return companyName;
     }

     public void setLegalPersonName(String legalPersonName){
         this.legalPersonName = legalPersonName;
     }

     public String getLegalPersonName(){
         return legalPersonName;
     }

    public Double getRegisteredCapital() {
        return registeredCapital;
    }

    public void setRegisteredCapital(Double registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    public void setIncorporationDate(Date incorporationDate){
         this.incorporationDate = incorporationDate;
     }

     public Date getIncorporationDate(){
         return incorporationDate;
     }

     public void setEnterpriseStatus(String enterpriseStatus){
         this.enterpriseStatus = enterpriseStatus;
     }

     public String getEnterpriseStatus(){
         return enterpriseStatus;
     }

     public void setRBpId(Long rBpId){
         this.rBpId = rBpId;
     }

     public Long getRBpId(){
         return rBpId;
     }

     }
