package com.hand.hls.bp.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "hls_bp_litigation_final")
public class HlsBpLitigationFinal extends BaseDTO {

     public static final String FIELD_FINAN_ID = "finanId";
     public static final String FIELD_BP_ID = "bpId";
     public static final String FIELD_CASE_CODE = "caseCode";
     public static final String FIELD_CASE_FINAL_TIME = "caseFinalTime";
     public static final String FIELD_CASE_CREATE_TIME = "caseCreateTime";
     public static final String FIELD_EXEC_COURT_NAME = "execCourtName";
     public static final String FIELD_EXEC_MONEY = "execMoney";
     public static final String FIELD_Z_NAME = "zName";


     @Id
     @GeneratedValue
     private Long finanId;

     private Long bpId;

     @Length(max = 100)
     private String caseCode; //案号

     private Date caseFinalTime; //终本日期

     private Date caseCreateTime; //立案时间

     @Length(max = 100)
     private String execCourtName; //执行法院

     @Length(max = 100)
     private String execMoney; //执行标的

     @Length(max = 255)
     private String zName; //被执行人名称


     public void setFinanId(Long finanId){
         this.finanId = finanId;
     }

     public Long getFinanId(){
         return finanId;
     }

     public void setBpId(Long bpId){
         this.bpId = bpId;
     }

     public Long getBpId(){
         return bpId;
     }

     public void setCaseCode(String caseCode){
         this.caseCode = caseCode;
     }

     public String getCaseCode(){
         return caseCode;
     }

     public void setCaseFinalTime(Date caseFinalTime){
         this.caseFinalTime = caseFinalTime;
     }

     public Date getCaseFinalTime(){
         return caseFinalTime;
     }

     public void setCaseCreateTime(Date caseCreateTime){
         this.caseCreateTime = caseCreateTime;
     }

     public Date getCaseCreateTime(){
         return caseCreateTime;
     }

     public void setExecCourtName(String execCourtName){
         this.execCourtName = execCourtName;
     }

     public String getExecCourtName(){
         return execCourtName;
     }

     public void setExecMoney(String execMoney){
         this.execMoney = execMoney;
     }

     public String getExecMoney(){
         return execMoney;
     }

     public void setZName(String zName){
         this.zName = zName;
     }

     public String getZName(){
         return zName;
     }

     }
