package com.hand.hls.bp.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "hls_bp_shareholder_info")
public class HlsBpShareholderInfo extends BaseDTO {

     public static final String FIELD_SHAREHOLDER_LN_ID = "shareholderLnId";
     public static final String FIELD_SHAREHOLDER_INFORMATION_ID = "shareholderInformationId";
     public static final String FIELD_BP_ID = "bpId";
     public static final String FIELD_SHAREHOLDER_NAME = "shareholderName";
     public static final String FIELD_ALIAS = "alias";
     public static final String FIELD_AMOMON = "amomon";
     public static final String FIELD_SUB_TIME = "subTime";
     public static final String FIELD_PAYMET = "paymet";
     public static final String FIELD_PERCENT = "percent";


     @Id
     @GeneratedValue
     private Long shareholderLnId; //主键

     private Long shareholderInformationId; //外键

     private Long bpId; //商业伙伴ID

     @Length(max = 255)
     private String shareholderName; //股东名称

     @Length(max = 100)
     private String alias; //简称

     private Double amomon; //出资金额

     private Date subTime; //出资时间

     @Length(max = 50)
     private String paymet; //出资方式

     @Length(max = 50)
     private String percent; //占比


     public void setShareholderLnId(Long shareholderLnId){
         this.shareholderLnId = shareholderLnId;
     }

     public Long getShareholderLnId(){
         return shareholderLnId;
     }

     public void setShareholderInformationId(Long shareholderInformationId){
         this.shareholderInformationId = shareholderInformationId;
     }

     public Long getShareholderInformationId(){
         return shareholderInformationId;
     }

     public void setBpId(Long bpId){
         this.bpId = bpId;
     }

     public Long getBpId(){
         return bpId;
     }

     public void setShareholderName(String shareholderName){
         this.shareholderName = shareholderName;
     }

     public String getShareholderName(){
         return shareholderName;
     }

     public void setAlias(String alias){
         this.alias = alias;
     }

     public String getAlias(){
         return alias;
     }

    public Double getAmomon() {
        return amomon;
    }

    public void setAmomon(Double amomon) {
        this.amomon = amomon;
    }

    public void setSubTime(Date subTime){
         this.subTime = subTime;
     }

     public Date getSubTime(){
         return subTime;
     }

     public void setPaymet(String paymet){
         this.paymet = paymet;
     }

     public String getPaymet(){
         return paymet;
     }

     public void setPercent(String percent){
         this.percent = percent;
     }

     public String getPercent(){
         return percent;
     }

     }
