package com.hand.hls.bp.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Data;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@ExtensionAttribute(disable=true)
@Table(name = "HLS_BP_MASTER_BUSINESS_CONDITION")
@Data
public class HlsBpMasterBusinessCondition extends BaseDTO {

     public static final String FIELD_CONDITION_ID = "conditionId";
     public static final String FIELD_BP_ID = "bpId";
     public static final String FIELD_ORDER_GROWING_TRENDS = "orderGrowingTrends";
     public static final String FIELD_ORDER_INDUSTRY_AVG_LEVEL = "orderIndustryAvgLevel";
     public static final String FIELD_ORDER_COMMENT = "orderComment";
     public static final String FIELD_ORDER_FLAG = "orderFlag";
     public static final String FIELD_ACCOUNT_BANK = "accountBank";
     public static final String FIELD_BANK_ACCOUNT = "bankAccount";
     public static final String FIELD_BANK_GROWING_TRENDS = "bankGrowingTrends";
     public static final String FIELD_BANK_COMMENT = "bankComment";
     public static final String FIELD_BANK_FLAG = "bankFlag";
     public static final String FIELD_SALE_GROWING_TRENDS = "saleGrowingTrends";
     public static final String FIELD_SALE_COMMENT = "saleComment";
     public static final String FIELD_SALE_FLAG = "saleFlag";
     public static final String FIELD_RECEIVE_PAY_GROWING_TRENDS = "receivePayGrowingTrends";
     public static final String FIELD_RECEIVE_PAY_COMMENT = "receivePayComment";
     public static final String FIELD_RECEIVE_FLAG = "receiveFlag";
     public static final String FIELD_PAY_FLAG = "payFlag";
     public static final String FIELD_HYDROPOWER_GROWING_TRENDS = "hydropowerGrowingTrends";
     public static final String FIELD_HYDROPOWER_COMMENT = "hydropowerComment";
     public static final String FIELD_WATER_FLAG = "waterFlag";
     public static final String FIELD_ELECTRICITY_FLAG = "electricityFlag";
     public static final String FIELD_TAX_GROWING_TRENDS = "taxGrowingTrends";
     public static final String FIELD_TAX_COMMENT = "taxComment";
     public static final String FIELD_TAX_FLAG = "taxFlag";


     @Id
     @GeneratedValue
     private Long conditionId;

     private Long bpId;

     @Length(max = 1000)
     private String orderGrowingTrends;

     @Length(max = 4000)
     private String orderIndustryAvgLevel;

     @Length(max = 4000)
     private String orderComment;

     @Length(max = 20)
     private String orderFlag;

     @Length(max = 200)
     private String accountBank;

     @Length(max = 200)
     private String bankAccount;

     @Length(max = 1000)
     private String bankGrowingTrends;

     @Length(max = 4000)
     private String bankComment;

     @Length(max = 20)
     private String bankFlag;

     @Length(max = 1000)
     private String saleGrowingTrends;

     @Length(max = 4000)
     private String saleComment;

     @Length(max = 20)
     private String saleFlag;

     @Length(max = 1000)
     private String receivePayGrowingTrends;

     @Length(max = 4000)
     private String receivePayComment;

     @Length(max = 20)
     private String receiveFlag;

     @Length(max = 20)
     private String payFlag;

     @Length(max = 1000)
     private String hydropowerGrowingTrends;

     @Length(max = 4000)
     private String hydropowerComment;

     @Length(max = 20)
     private String waterFlag;

     @Length(max = 20)
     private String electricityFlag;

     @Length(max = 1000)
     private String taxGrowingTrends;

     @Length(max = 4000)
     private String taxComment;

     @Length(max = 20)
     private String taxFlag;

     @Transient
     private String orderFlagN;
     @Transient
     private String bankFlagN;
     @Transient
     private String saleFlagN;
     @Transient
     private String receiveFlagN;
     @Transient
     private String payFlagN;
     @Transient
     private String waterFlagN;
     @Transient
     private String electricityFlagN;
     @Transient
     private String taxFlagN;

     }
